function lesson(data) {
  return {
    course: "js", category: "Arrays", preserveInput: true, ...data,
    starter: `function ${data.functionName}(${data.parameter}) {\n  // Schreibe hier deine Lösung.\n}\n\nconsole.log(${data.functionName}(${JSON.stringify(data.tests[0].input)}));`,
    example: `${data.solution}\n\nconsole.log(${data.functionName}(${JSON.stringify(data.tests[0].input)}));`,
  };
}

export const arrayQueryLessons = [
  lesson({
    id: "js-array-find", name: ".find()", title: "Mit find den ersten passenden Wert auswählen",
    description: "find liefert das erste Element, das deine Bedingung erfüllt. Anders als findIndex liefert es den Wert selbst und anders als filter keine Liste aller Treffer.",
    syntax: "const wert = [8, 0, 12].find(zahl => zahl >= 0); // 8\nconst fehlt = [1, 2].find(zahl => zahl >= 5); // undefined\nconst ergebnis = fehlt ?? null; // null",
    parts: [["zahl => zahl >= grenze", "Ein Callback prüft für jedes Element, ob es die Grenze erreicht."], [".find(callback)", "Sucht von links nach rechts und stoppt beim ersten Treffer."], ["undefined", "Rückgabewert, wenn kein Element passt."], ["?? null", "Ersetzt einen fehlenden Wert durch null und erhält gültige Treffer wie 0."]],
    note: "find liefert den ersten Treffer in der vorhandenen Reihenfolge, nicht den kleinsten passenden Wert. Sortieren ist hier weder nötig noch verlangt.",
    detail: "Die Eingabe {zahlen, grenze} enthält ein dichtes Array endlicher Zahlen und eine endliche Zahl als Grenze. Es gibt keine undefined-Elemente, daher steht undefined hier eindeutig für keinen Treffer. Ein Objekt als Treffer würde über dieselbe Referenz zurückgegeben; find erzeugt keine tiefe Kopie. Die Methode liest die Liste, der Callback soll sie nicht verändern.",
    functionName: "ersterAbGrenze", parameter: "daten",
    task: "Schreibe ersterAbGrenze(daten). Gib die erste Zahl aus daten.zahlen zurück, die mindestens daten.grenze beträgt. Gib bei keinem Treffer null zurück. Verändere die Eingabe nicht.",
    tests: [{input:{zahlen:[8,3,12],grenze:3},expected:8},{input:{zahlen:[-2,0,4],grenze:0},expected:0},{input:{zahlen:[1,2],grenze:5},expected:null},{input:{zahlen:[],grenze:0},expected:null},{input:{zahlen:[-8,-3,-1],grenze:-3},expected:-3},{input:{zahlen:[1,2.5,3],grenze:2.5},expected:2.5}],
    hints: ["Nutze find mit zahl => zahl >= daten.grenze.", "Wandle nur einen fehlenden Treffer um: ?? null erhält auch die Zahl 0. || null würde 0 verlieren."],
    solution: "function ersterAbGrenze(daten) {\n  return daten.zahlen.find(zahl => zahl >= daten.grenze) ?? null;\n}",
    explanation: "Bei [8,3,12] und Grenze 3 trifft schon 8. find beendet dort die Suche und gibt 8 zurück, nicht den Index 0 oder alle drei Zahlen. Bei [-2,0,4] und Grenze 0 ist 0 der erste Treffer. ?? lässt ihn unverändert; nur undefined wird hier zu null.",
  }),
  lesson({
    id: "js-array-some", name: ".some()", title: "Mit some prüfen, ob wenigstens ein Artikel verfügbar ist",
    description: "some beantwortet eine Ja/Nein-Frage: Erfüllt mindestens ein Element die Bedingung? Du brauchst keine vollständige gefilterte Liste, wenn dich nur die Existenz eines Treffers interessiert.",
    syntax: "const verfuegbar = artikel.some(eintrag => eintrag.bestand > 0);\n// [{bestand: 0}, {bestand: 3}] → true\n// [] → false",
    parts: [[".some(callback)", "Gibt true zurück, sobald ein Callback einen truthy Wert liefert."], ["eintrag.bestand > 0", "Prüft die Menge statt die Existenz des Artikelobjekts."], ["Kurzschluss", "Nach dem ersten Treffer werden die weiteren Elemente nicht mehr geprüft."], ["Leeres Array", "Ohne Elemente gibt es keinen Treffer: some ergibt false."]],
    note: "Ein Array ist selbst truthy, auch []. filter(...) als Bedingung sagt daher nicht zuverlässig aus, ob ein Treffer existiert. some liefert direkt einen Boolean.",
    detail: "Jeder Artikel besitzt einen Namen und einen nichtnegativen ganzzahligen Bestand. Die Aufgabe meldet Verfügbarkeit, sobald irgendein Bestand größer als 0 ist. Ein Bestand von 0 bedeutet ausverkauft. Verändere keine Artikel. some kann im schlimmsten Fall alle n Elemente prüfen: O(n).",
    functionName: "hatVerfuegbareArtikel", parameter: "artikel",
    task: "Schreibe hatVerfuegbareArtikel(artikel). Gib true zurück, wenn mindestens ein Artikel einen Bestand größer als 0 hat, sonst false. Verändere die Eingabe nicht.",
    tests: [{input:[{name:"Stift",bestand:0},{name:"Heft",bestand:3}],expected:true},{input:[{name:"Stift",bestand:0}],expected:false},{input:[],expected:false},{input:[{name:"Heft",bestand:2},{name:"Buch",bestand:0}],expected:true},{input:[{name:"Buch",bestand:1}],expected:true},{input:[{name:"A",bestand:0},{name:"B",bestand:0}],expected:false}],
    hints: ["Du suchst nicht alle Artikel, sondern nur die Antwort auf eine Existenzfrage.", "Gib artikel.some(eintrag => eintrag.bestand > 0) zurück."],
    solution: "function hatVerfuegbareArtikel(artikel) {\n  return artikel.some(eintrag => eintrag.bestand > 0);\n}",
    explanation: "Beim ersten Beispiel scheitert die Bedingung für den Stift, trifft aber auf das Heft zu: some liefert true. Für ein leeres Array liefert es false. every wäre hier falsch, weil dann alle Artikel verfügbar sein müssten.",
  }),
  lesson({
    id: "js-array-every", name: ".every()", title: "Mit every prüfen, ob alle Werte eine Regel erfüllen",
    description: "every prüft eine Bedingung für alle Elemente. So kannst du beispielsweise feststellen, ob eine Zahlenliste ausschließlich nichtnegative Werte enthält.",
    syntax: "const gueltig = zahlen.every(zahl => zahl >= 0);\n// [0, 2, 5] → true\n// [0, -1, 5] → false\n// [] → true",
    parts: [[".every(callback)", "Gibt false zurück, sobald ein Element die Bedingung nicht erfüllt."], [">= 0", "Null ist hier ausdrücklich erlaubt; > 0 wäre eine andere Regel."], ["Leeres Array", "Kein Element verletzt die Regel, deshalb ergibt der Aufruf von every auf [] true."], ["zahlen.length > 0", "Eine zusätzliche Bedingung, falls eine Anwendung außerdem mindestens einen Eintrag verlangt."]],
    note: "Auf einem leeren Array ergibt every true und some false. Wenn ein Formular mindestens eine Eingabe braucht, prüfe die Länge zusätzlich. Diese Aufgabe verlangt ausdrücklich nur die Regel für die vorhandenen Zahlen.",
    detail: "Die Liste enthält ausschließlich endliche Zahlen und keine Lücken. Alle müssen >= 0 sein. Negative Zahlen und auch negative Dezimalwerte verletzen die Regel. every gibt immer einen Boolean zurück und verändert die Liste selbst nicht. Die Worst-Case-Laufzeit ist O(n).",
    functionName: "alleNichtnegativ", parameter: "zahlen",
    task: "Schreibe alleNichtnegativ(zahlen). Gib true zurück, wenn jede vorhandene Zahl mindestens 0 ist, sonst false. Für [] ist das Ergebnis true. Verändere die Liste nicht.",
    tests: [{input:[0,2,5],expected:true},{input:[0,-1,5],expected:false},{input:[],expected:true},{input:[0],expected:true},{input:[-0.5],expected:false},{input:[2.5,1],expected:true}],
    hints: ["Nutze every und die Bedingung zahl >= 0.", "Füge hier keine Mindestlänge hinzu: Für die leere Liste ist true verlangt."],
    solution: "function alleNichtnegativ(zahlen) {\n  return zahlen.every(zahl => zahl >= 0);\n}",
    explanation: "Bei [0,-1,5] trifft die Regel auf 0 zu, aber nicht auf -1. every liefert sofort false; 5 muss nicht mehr geprüft werden. Bei [] findet es keinen Verstoß und liefert true. some würde dagegen schon die erste nichtnegative Zahl als ausreichenden Treffer betrachten.",
  }),
  lesson({
    id: "js-array-reduce", name: ".reduce()", title: "Mit reduce den Gesamtwert eines Warenkorbs berechnen",
    description: "reduce fasst eine Liste zu einem Ergebnis zusammen. Ein Akkumulator hält den bisherigen Zwischenstand; jeder Callback gibt den nächsten Zwischenstand zurück.",
    syntax: "const gesamt = warenkorb.reduce(\n  (summe, artikel) => summe + artikel.preisCent * artikel.menge,\n  0\n);",
    parts: [["summe", "Der Akkumulator: beginnt bei 0 und erhält danach den letzten Rückgabewert."], ["artikel", "Der aktuelle Eintrag aus der Liste."], ["preisCent * menge", "Berechnet den Wert dieser Position, einschließlich mehrerer Stücke."], ["return / implizite Rückgabe", "Gibt den neuen Zwischenstand zurück. Mit { } brauchst du ein ausdrückliches return."], ["0 als Startwert", "Gibt Typ und Anfangswert vor und macht einen leeren Warenkorb zu 0."]],
    note: "Ohne Startwert verwendet reduce das erste Element als Akkumulator und wirft bei [] einen TypeError. Bei einer Liste von Artikelobjekten ist dieses erste Objekt zudem keine passende Zahlensumme.",
    detail: "Jeder Artikel besitzt name, preisCent und menge. Preis und Menge sind nichtnegative ganze Zahlen; alle Produkte und Summen liegen im sicheren Ganzzahlbereich von JavaScript. Cent-Beträge vermeiden hier Rundungsprobleme mit Dezimalpreisen. Die Ausgabe ist eine Zahl in Cent, kein formatierter Euro-String. Keinen Artikel verändern. reduce verarbeitet die n Einträge in O(n).",
    functionName: "warenkorbSumme", parameter: "warenkorb",
    task: "Schreibe warenkorbSumme(warenkorb). Addiere für jeden Artikel preisCent * menge und gib die Gesamtsumme in Cent zurück. Ein leerer Warenkorb ergibt 0. Verändere keine Eingabedaten.",
    tests: [{input:[{name:"Heft",preisCent:250,menge:2},{name:"Stift",preisCent:120,menge:3}],expected:860},{input:[],expected:0},{input:[{name:"Buch",preisCent:1299,menge:1}],expected:1299},{input:[{name:"A",preisCent:500,menge:0},{name:"B",preisCent:0,menge:4}],expected:0},{input:[{name:"A",preisCent:1,menge:3},{name:"B",preisCent:99,menge:2}],expected:201},{input:[{name:"A",preisCent:10,menge:2},{name:"B",preisCent:10,menge:2}],expected:40}],
    hints: ["Beginne reduce mit dem Startwert 0.", "Der Callback muss summe + artikel.preisCent * artikel.menge zurückgeben. Summiere nicht nur die Einzelpreise."],
    solution: "function warenkorbSumme(warenkorb) {\n  return warenkorb.reduce(\n    (summe, artikel) => summe + artikel.preisCent * artikel.menge,\n    0\n  );\n}",
    explanation: "Im Beispiel startet summe bei 0. Das Heft ergibt 250 * 2 = 500, also ist der nächste Akkumulator 500. Die Stifte ergeben 120 * 3 = 360; der nächste Akkumulator ist 860. reduce gibt den letzten Wert zurück. Bei [] wird kein Callback aufgerufen und der Startwert 0 zurückgegeben.",
  }),
];
