// Jede Aufgabe bekommt unterschiedliche Eingaben und echte Grenzfälle.
function lesson(data) {
  return {
    course: "js",
    preserveInput: true,
    ...data,
    starter: `function ${data.functionName}(${data.parameter}) {\n  // Schreibe hier deine Lösung.\n}\n\nconsole.log(${data.functionName}(${JSON.stringify(data.tests[0].input)}));`,
    example: `${data.solution}\n\nconsole.log(${data.functionName}(${JSON.stringify(data.tests[0].input)}));`,
  };
}

export const foundations = [
  lesson({
    id: "js-variables", category: "Grundlagen", name: "let & const",
    title: "Werte speichern mit let und const",
    description: "Variablen geben Werten einen Namen. const verhindert eine neue Zuweisung; let erlaubt sie.",
    syntax: "const start = 10;\nlet stand = start;\nstand = stand + 5;",
    parts: [["const", "Dieser Name darf im selben Gültigkeitsbereich nicht neu zugewiesen werden."], ["let", "Dieser Name darf später einen anderen Wert erhalten."], ["=", "Weist den Wert rechts dem Namen links zu. Es ist kein Vergleich."]],
    note: "const macht ein Objekt oder Array nicht unveränderlich. Es schützt die Bindung des Namens.",
    detail: "Bei stand = stand + 5 wird zuerst der alte Wert gelesen und 5 addiert. Danach ersetzt das Ergebnis den bisherigen Wert. Verwende const, wenn du keine neue Zuweisung brauchst.",
    functionName: "neuerStand", parameter: "start",
    task: "Schreibe neuerStand(start). Speichere den Zahlenwert in einer lokalen Variable, erhöhe ihn um 5 und gib das Ergebnis zurück. Die Funktion wird mit verschiedenen Zahlen geprüft.",
    tests: [{input:10,expected:15},{input:0,expected:5},{input:-8,expected:-3}],
    hints: ["Mit let stand = start legst du einen veränderbaren Wert an.", "Erhöhe stand um 5 und gib ihn mit return zurück."],
    solution: "function neuerStand(start) {\n  let stand = start;\n  stand = stand + 5;\n  return stand;\n}",
    explanation: "start ist der Parameter. let legt stand an; die zweite Zuweisung berechnet den neuen Wert. return liefert ihn an den Aufrufer. Die Tests prüfen das Ergebnis; sie schreiben dir keinen bestimmten Lösungsstil vor.",
  }),
  lesson({
    id: "js-arithmetic", category: "Operatoren", name: "+ − * /",
    title: "Rechnen und die Reihenfolge verstehen",
    description: "+ addiert Zahlen, - subtrahiert, * multipliziert und / dividiert. Klammern bestimmen, was zuerst passiert.",
    syntax: "(preis * anzahl) - rabatt",
    parts: [["*", "Multiplikation wird vor Addition und Subtraktion ausgeführt."], ["()", "Der eingeklammerte Ausdruck wird zuerst ausgewertet."], ["-", "Zieht den rechten Zahlenwert vom linken ab."]],
    note: "Mit Strings kann + Texte verbinden: '2' + 3 ergibt '23'. Die Eingaben dieser Aufgabe sind Zahlen.",
    detail: "2 + 3 * 4 ergibt 14; (2 + 3) * 4 ergibt 20. JavaScript-Zahlen können Rundungsfehler haben, etwa bei 0.1 + 0.2. Für Geld nutzen wir hier ganze Centbeträge.",
    functionName: "gesamtPreis", parameter: "kauf",
    task: "Schreibe gesamtPreis(kauf). kauf enthält preis, anzahl und rabatt in ganzen Centbeträgen. Gib preis × anzahl minus rabatt zurück.",
    tests: [{input:{preis:500,anzahl:3,rabatt:100},expected:1400},{input:{preis:250,anzahl:0,rabatt:0},expected:0},{input:{preis:120,anzahl:2,rabatt:40},expected:200}],
    hints: ["Du liest eine Eigenschaft mit kauf.preis.", "Multipliziere zuerst Preis und Anzahl, dann ziehe den Rabatt ab."],
    solution: "function gesamtPreis(kauf) {\n  return kauf.preis * kauf.anzahl - kauf.rabatt;\n}",
    explanation: "Der Punkt liest Eigenschaften des Eingabeobjekts. * wird vor - ausgewertet. return liefert den berechneten Centbetrag; das Objekt bleibt unverändert.",
  }),
  lesson({
    id: "js-remainder", category: "Operatoren", name: "%",
    title: "Den Divisionsrest mit % berechnen",
    description: "% gibt den Rest einer Division zurück. Damit kannst du zum Beispiel gerade Zahlen erkennen.",
    syntax: "zahl % 2 === 0",
    parts: [["%", "Restoperator: 7 % 2 ergibt 1."], ["2", "Der Divisor, durch den geteilt wird."], ["=== 0", "Prüft, ob kein Rest übrig bleibt."]],
    note: "Bei negativen Zahlen kann auch der Rest negativ sein. Gerade negative Zahlen haben trotzdem Rest 0.",
    detail: "8 lässt sich in vier Zweiergruppen aufteilen, ohne Rest. Bei 9 bleibt 1 übrig. % bedeutet in JavaScript nicht Prozentrechnung.",
    functionName: "istGerade", parameter: "zahl",
    task: "Schreibe istGerade(zahl). Gib für gerade ganze Zahlen true und für ungerade false zurück.",
    tests: [{input:8,expected:true},{input:9,expected:false},{input:0,expected:true},{input:-6,expected:true},{input:-3,expected:false}],
    hints: ["Berechne zahl % 2.", "Vergleiche den Rest mit 0."],
    solution: "function istGerade(zahl) {\n  return zahl % 2 === 0;\n}",
    explanation: "% berechnet zuerst den Rest. === vergleicht ihn mit 0 und erzeugt einen Boolean, den return zurückgibt.",
  }),
  lesson({
    id: "js-comparisons", category: "Operatoren", name: ">= & !",
    title: "Grenzen vergleichen und Aussagen umkehren",
    description: "Vergleiche erzeugen true oder false. >= bedeutet größer oder gleich; ! kehrt den Wahrheitswert um.",
    syntax: "!(alter >= 18)",
    parts: [[">=", "Bezieht die Grenze selbst mit ein: 18 >= 18 ist true."], ["!", "Aus true wird false, aus false wird true."], ["()", "Fasst den Vergleich zusammen, bevor ! angewendet wird."]],
    note: "> ist strenger als >=. Teste die Grenze selbst und jeweils einen Wert darunter und darüber.",
    detail: "! wandelt seinen Operanden zunächst in einen Boolean um und negiert ihn. Hier negierst du einen Vergleich, der bereits ein Boolean ist. Die Eingabe ist ein Zahlenwert.",
    functionName: "istMinderjaehrig", parameter: "alter",
    task: "Schreibe istMinderjaehrig(alter). Gib true für Alter unter 18 zurück, sonst false.",
    tests: [{input:17,expected:true},{input:18,expected:false},{input:19,expected:false},{input:0,expected:true}],
    hints: ["Prüfe zuerst, ob alter >= 18 ist.", "Drehe dieses Ergebnis mit ! um. alter < 18 wäre ebenfalls korrekt."],
    solution: "function istMinderjaehrig(alter) {\n  return !(alter >= 18);\n}",
    explanation: "Der Vergleich schließt 18 ein. ! macht aus dem Ergebnis die gegenteilige Aussage. So wird die Grenze 18 korrekt als nicht minderjährig erkannt.",
  }),
  lesson({
    id: "js-if", category: "Kontrollfluss", name: "if / else",
    title: "Entscheidungen treffen mit if und else",
    description: "if führt einen Block nur bei einer wahren Bedingung aus. else ist der alternative Weg.",
    syntax: "if (bedingung) {\n  return ersterWert;\n} else {\n  return andererWert;\n}",
    parts: [["if", "Prüft die Bedingung in Klammern."], ["{}", "Fasst Anweisungen zu einem Block zusammen."], ["else", "Wird ausgeführt, wenn die if-Bedingung falsch ist."]],
    note: "return beendet den Funktionsaufruf sofort. Ein else nach einem return ist daher oft optional.",
    detail: "Ein häufiger Fehler ist = statt === in einer Bedingung: = weist einen Wert zu. Für Zahlenbereiche sind <, <=, > und >= passende Vergleiche.",
    functionName: "versand", parameter: "warenwert",
    task: "Schreibe versand(warenwert). Ab 5000 Cent Warenwert ist der Versand kostenlos (0); darunter kostet er 499 Cent.",
    tests: [{input:4999,expected:499},{input:5000,expected:0},{input:9000,expected:0},{input:0,expected:499}],
    hints: ["Die Grenze gehört zum kostenlosen Versand: >= 5000.", "Gib im if-Block 0 und im anderen Fall 499 zurück."],
    solution: "function versand(warenwert) {\n  if (warenwert >= 5000) {\n    return 0;\n  } else {\n    return 499;\n  }\n}",
    explanation: "if wählt anhand des Warenwerts einen Weg. Genau 5000 erfüllt >=. Beide Wege liefern ausdrücklich einen Zahlenwert zurück.",
  }),
  lesson({
    id: "js-for", category: "Schleifen", name: "for & +=",
    title: "Wiederholungen mit einer for-Schleife",
    description: "Eine for-Schleife wiederholt ihren Block, solange ihre Bedingung wahr ist. Ein Zähler steuert die Wiederholungen.",
    syntax: "for (let i = 0; i < zahlen.length; i++) {\n  summe += zahlen[i];\n}",
    parts: [["let i = 0", "Startet bei Arrayindex 0, dem ersten Element."], ["i < zahlen.length", "Prüft vor jedem Durchlauf, ob noch ein Element vorhanden ist."], ["i++", "Erhöht den Zähler nach dem Block um 1."], ["+=", "summe += wert ist hier kurz für summe = summe + wert."]],
    note: "Der letzte gültige Index ist length - 1. <= length würde auch einen ungültigen Index lesen.",
    detail: "zahlen[i] liest das Element an Position i. Bei einem leeren Array ist 0 < 0 falsch: Der Block läuft kein einziges Mal. Eine falsche Abbruchbedingung kann eine Endlosschleife erzeugen.",
    functionName: "summe", parameter: "zahlen",
    task: "Schreibe summe(zahlen). Addiere alle Zahlen und gib das Ergebnis zurück. Für ein leeres Array ist die Summe 0. Verändere das Eingabe-Array nicht.",
    tests: [{input:[2,4,6],expected:12},{input:[],expected:0},{input:[-3,8,-5],expected:0},{input:[7],expected:7}],
    hints: ["Lege vor der Schleife let ergebnis = 0 an.", "Addiere jedes zahlen[i] und gib erst nach der Schleife das Ergebnis zurück."],
    solution: "function summe(zahlen) {\n  let ergebnis = 0;\n  for (let i = 0; i < zahlen.length; i++) {\n    ergebnis += zahlen[i];\n  }\n  return ergebnis;\n}",
    explanation: "ergebnis beginnt bei 0. Jeder Durchlauf addiert ein Element; erst nach allen Durchläufen liefert return die Summe. Auch die leere Eingabe ergibt so 0.",
  }),
  lesson({
    id: "js-return", category: "Funktionen", name: "function & return",
    title: "Funktionen aufrufen und Ergebnisse zurückgeben",
    description: "Eine Funktion bündelt Arbeit. Parameter nehmen Eingaben an; return gibt ein Ergebnis an den Aufrufer zurück.",
    syntax: "function quadrat(zahl) {\n  return zahl * zahl;\n}\nconst ergebnis = quadrat(4);",
    parts: [["function", "Deklariert eine Funktion mit Namen und Parametern."], ["zahl", "Parameter: erhält bei jedem Aufruf den übergebenen Wert."], ["return", "Liefert einen Wert zurück und beendet diesen Aufruf."], ["quadrat(4)", "Aufruf mit dem Argument 4. Der Rückgabewert ist 16."]],
    note: "console.log zeigt etwas an, gibt es aber nicht als Funktionsergebnis zurück. Ohne return erhält der Aufrufer undefined.",
    detail: "Ein Parametername ist lokal in der Funktion verfügbar. Aufrufe können unterschiedliche Argumente übergeben. Code nach einem ausgeführten return wird in diesem Aufruf nicht mehr erreicht.",
    functionName: "quadrat", parameter: "zahl",
    task: "Schreibe quadrat(zahl). Gib zahl mal zahl zurück; bloßes Ausgeben mit console.log reicht nicht.",
    tests: [{input:4,expected:16},{input:-3,expected:9},{input:0,expected:0},{input:1.5,expected:2.25}],
    hints: ["Nutze den Parameter statt einer festen Zahl.", "return zahl * zahl; liefert das Ergebnis zurück."],
    solution: "function quadrat(zahl) {\n  return zahl * zahl;\n}",
    explanation: "Der Parameter wird bei jedem Aufruf neu gesetzt. * berechnet das Quadrat; return übergibt es an den Aufrufer. Auch negative Zahlen werden beim Quadrieren positiv.",
  }),
  lesson({
    id: "js-objects", category: "Objekte", name: "Objekte & .",
    title: "Zusammengehörige Daten als Objekt",
    description: "Objekte speichern benannte Eigenschaften. Der Punkt liest eine Eigenschaft; ein Objektliteral mit {} erzeugt ein Objekt.",
    syntax: "const person = { name: 'Mira', alter: 20 };\nperson.name;",
    parts: [["{}", "Objektliteral: legt Eigenschaften mit Namen und Werten an."], ["name: 'Mira'", "Der Doppelpunkt verbindet Eigenschaft und Wert."], ["person.name", "Liest die Eigenschaft name des Objekts."]],
    note: "Eine fehlende Eigenschaft ergibt undefined. Das Lesen verändert das Objekt nicht.",
    detail: "Objekte können Strings, Zahlen, Arrays und weitere Objekte enthalten. Eine const-Bindung verhindert person = anderesObjekt, aber nicht person.alter = 21.",
    functionName: "profil", parameter: "person",
    task: "Schreibe profil(person). Gib ein neues Objekt mit name aus der Eingabe und volljaehrig zurück. volljaehrig ist ab einem Alter von 18 true. Verändere person nicht.",
    tests: [{input:{name:"Mira",alter:20},expected:{name:"Mira",volljaehrig:true}},{input:{name:"Ali",alter:17},expected:{name:"Ali",volljaehrig:false}},{input:{name:"Jo",alter:18},expected:{name:"Jo",volljaehrig:true}}],
    hints: ["Ein neues Objekt kannst du direkt hinter return mit { ... } erzeugen.", "Die Werte sind person.name und person.alter >= 18."],
    solution: "function profil(person) {\n  return { name: person.name, volljaehrig: person.alter >= 18 };\n}",
    explanation: "Die Funktion liest zwei Eigenschaften, wertet den Vergleich aus und erzeugt ein neues Objekt. Die Eingabe bleibt erhalten.",
  }),
  lesson({
    id: "js-nullish", category: "Operatoren", name: "??",
    title: "Fehlende Werte ersetzen mit ??",
    description: "?? nimmt den rechten Ersatzwert nur dann, wenn der linke Wert null oder undefined ist.",
    syntax: "einstellungen.limit ?? 10",
    parts: [["??", "Nullish-Coalescing-Operator: prüft gezielt null und undefined."], ["limit", "Die gelesene Eigenschaft kann auch fehlen."], ["10", "Ersatzwert, falls links kein Wert vorhanden ist."]],
    note: "0, false und ein leerer String bleiben erhalten. || würde diese falsy Werte ebenfalls ersetzen.",
    detail: "null steht oft für absichtlich keinen Wert; undefined für einen nicht gesetzten Wert. Der Ausdruck rechts von ?? wird nur ausgewertet, wenn links null oder undefined steht.",
    functionName: "limitLesen", parameter: "einstellungen",
    task: "Schreibe limitLesen(einstellungen). Gib einstellungen.limit zurück. Fehlt limit oder ist es null, gib 10 zurück. Der Wert 0 muss erhalten bleiben.",
    tests: [{input:{limit:3},expected:3},{input:{},expected:10},{input:{limit:null},expected:10},{input:{limit:0},expected:0}],
    hints: ["Mit || würde limit: 0 fälschlich zu 10.", "return einstellungen.limit ?? 10;"],
    solution: "function limitLesen(einstellungen) {\n  return einstellungen.limit ?? 10;\n}",
    explanation: "Die Punktnotation liest limit. ?? ersetzt ausschließlich null und undefined. Eine erlaubte Grenze von 0 wird deshalb korrekt zurückgegeben.",
  }),
  lesson({
    id: "js-template", category: "Strings", name: "Template-Strings",
    title: "Texte mit Werten zusammensetzen",
    description: "Template-Strings stehen zwischen Backticks. ${...} setzt den Wert eines Ausdrucks in den Text ein.",
    syntax: "`Hallo ${person.name}!`",
    parts: [["`...`", "Backticks markieren einen Template-String."], ["${...}", "Wertet den Ausdruck aus und fügt ihn als Text ein."], ["person.name", "Liest hier den Namen aus einem Objekt."]],
    note: "Normale Anführungszeichen ersetzen ${...} nicht. Achte auf Leerzeichen und Satzzeichen.",
    detail: "Im Platzhalter können auch Rechnungen oder Funktionsaufrufe stehen. Für HTML ist erzeugter Text nicht automatisch sicher: Benutzereingaben sollten als Text dargestellt werden.",
    functionName: "begruessen", parameter: "person",
    task: "Schreibe begruessen(person). Gib exakt 'Hallo NAME! Du bist ALTER Jahre alt.' zurück, mit den Werten name und alter aus person.",
    tests: [{input:{name:"Mira",alter:20},expected:"Hallo Mira! Du bist 20 Jahre alt."},{input:{name:"Ali",alter:0},expected:"Hallo Ali! Du bist 0 Jahre alt."},{input:{name:"Léa",alter:31},expected:"Hallo Léa! Du bist 31 Jahre alt."}],
    hints: ["Nutze Backticks statt normaler Anführungszeichen.", "Setze person.name und person.alter jeweils in ${...}."],
    solution: "function begruessen(person) {\n  return `Hallo ${person.name}! Du bist ${person.alter} Jahre alt.`;\n}",
    explanation: "Beide Platzhalter werden ausgewertet und in Text umgewandelt. Der übrige Text bleibt unverändert. Die Funktion gibt den fertigen String zurück.",
  }),
  lesson({
    id: "js-push", category: "Arrays", name: ".push() & Spread",
    title: "Arrays kopieren und mit push erweitern",
    description: ".push() hängt Elemente an ein bestehendes Array an. Es verändert das Array und gibt dessen neue Länge zurück.",
    syntax: "const kopie = [...daten.liste];\nconst laenge = kopie.push(daten.wert);",
    parts: [["[...liste]", "Erzeugt eine flache Kopie der Elemente in einem neuen Array."], [".push(wert)", "Hängt wert am Ende an und verändert dieses Array."], ["laenge", "Der Rückgabewert von push ist eine Zahl, nicht das Array."]],
    note: "Eine flache Kopie teilt enthaltene Objekte mit dem Original. Hier kopierst du nur Arrays mit Zahlen.",
    detail: "const liste = [1]; liste.push(2) ist erlaubt: Die Bindung bleibt gleich, der Arrayinhalt ändert sich. return liste.push(2) gäbe die Länge 2 zurück, nicht [1, 2].",
    functionName: "anhaengen", parameter: "daten",
    task: "Schreibe anhaengen(daten). Gib eine Kopie von daten.liste mit daten.wert am Ende zurück. Das ursprüngliche Array darf nicht verändert werden.",
    tests: [{input:{liste:[1,2],wert:3},expected:[1,2,3]},{input:{liste:[],wert:0},expected:[0]},{input:{liste:[-1],wert:-1},expected:[-1,-1]}],
    hints: ["Kopiere zuerst die Liste mit [...daten.liste].", "Rufe push auf der Kopie auf, gib danach die Kopie zurück."],
    solution: "function anhaengen(daten) {\n  const kopie = [...daten.liste];\n  kopie.push(daten.wert);\n  return kopie;\n}",
    explanation: "Spread kopiert die Zahlen in ein neues Array. push verändert nur diese Kopie. Der Rückgabewert von push wird nicht benötigt; return gibt das Array zurück.",
  }),
  lesson({
    id: "js-budget", category: "Projekte", name: "Budget-Rechner",
    title: "Miniprojekt: Deinen Budget-Rechner bauen",
    description: "Verbinde Objekte, Arrays, Schleifen, Rechnungen und eine Entscheidung zu einer kleinen Anwendung.",
    syntax: "budgetBericht({ budget: 5000, ausgaben: [1200, 800] })",
    parts: [["budget", "Verfügbarer Betrag in ganzen Cent."], ["ausgaben", "Array mit Ausgaben in ganzen Cent."], ["Bericht", "Neues Objekt mit gesamt, rest und imBudget."]],
    note: "Plane zuerst: Eingabe lesen → Ausgaben summieren → Rest berechnen → Ergebnis zurückgeben.",
    detail: "Baue die Funktion schrittweise. Prüfe zuerst die Summe, danach den Rest und zuletzt die Budgetgrenze. Schreibe zusätzlich eigene console.log-Aufrufe für eine leere Liste und ein überschrittenes Budget.",
    functionName: "budgetBericht", parameter: "daten",
    task: "Schreibe budgetBericht(daten). Summiere daten.ausgaben zu gesamt. rest ist daten.budget minus gesamt. imBudget ist true, wenn rest mindestens 0 ist. Gib ein neues Objekt mit gesamt, rest und imBudget zurück. Verändere die Eingabe nicht.",
    tests: [{input:{budget:5000,ausgaben:[1200,800]},expected:{gesamt:2000,rest:3000,imBudget:true}},{input:{budget:1000,ausgaben:[600,500]},expected:{gesamt:1100,rest:-100,imBudget:false}},{input:{budget:0,ausgaben:[]},expected:{gesamt:0,rest:0,imBudget:true}},{input:{budget:700,ausgaben:[300,400]},expected:{gesamt:700,rest:0,imBudget:true}}],
    hints: ["Beginne mit let gesamt = 0 und addiere jeden Eintrag der Ausgabenliste.", "Berechne const rest = daten.budget - gesamt. Der Vergleich rest >= 0 ergibt imBudget."],
    solution: "function budgetBericht(daten) {\n  let gesamt = 0;\n  for (let i = 0; i < daten.ausgaben.length; i++) {\n    gesamt += daten.ausgaben[i];\n  }\n  const rest = daten.budget - gesamt;\n  return { gesamt, rest, imBudget: rest >= 0 };\n}",
    explanation: "Die Schleife summiert beliebig viele Ausgaben; eine leere Liste ergibt 0. Subtraktion berechnet den Rest. >= schließt ein genau ausgeschöpftes Budget ein. Das neue Berichtsobjekt verbindet alle Teilergebnisse. Als eigene Erweiterung kannst du die größte Ausgabe berechnen.",
  }),
];
