function lesson(data) {
  return {
    course: "js", category: "Ein-/Ausgabe & Dateien", preserveInput: true, ...data,
    starter: `function ${data.functionName}(${data.parameter}) {\n  // Schreibe hier deine Lösung.\n}\n\nconsole.log(${data.functionName}(${JSON.stringify(data.tests[0].input)}));`,
    example: `${data.solution}\n\nconsole.log(${data.functionName}(${JSON.stringify(data.tests[0].input)}));`,
  };
}

export const ioLessons = [
  lesson({
    id: "js-input-trim", name: ".trim() & Eingaben", title: "Texteingaben bereinigen und prüfen",
    description: "Eingaben aus Textfeldern sind Strings. .trim() entfernt Leerraum am Anfang und Ende, damit du leere Eingaben zuverlässig erkennst.",
    syntax: "const name = eingabe.trim();\nif (name.length === 0) { return 'Name fehlt'; }",
    parts: [[".trim()", "Gibt einen neuen String ohne äußere Leerzeichen, Tabs und Zeilenumbrüche zurück."], [".length", "Länge des Strings in UTF-16-Codeeinheiten."], ["return", "Liefert hier die Fehlermeldung oder die Begrüßung an den Aufrufer."]],
    note: "Leerzeichen innerhalb des Namens bleiben erhalten. trim verändert den ursprünglichen String nicht.",
    detail: "Ein HTML-Eingabefeld liest du über input.value, ein React-Feld typischerweise über event.target.value. Für Zahleneingaben brauchst du anschließend eine geprüfte Umwandlung. console.log zeigt Werte in der Entwicklerkonsole; sichtbare App-Ausgabe braucht ein Oberflächenelement.",
    functionName: "eingabeBegruessen", parameter: "eingabe",
    task: "Schreibe eingabeBegruessen(eingabe). Entferne äußeren Leerraum. Ist der verbleibende Name leer, gib 'Name fehlt' zurück. Sonst gib 'Hallo NAME!' zurück. Die Eingabe ist immer ein String.",
    tests: [{input:"  Mira  ",expected:"Hallo Mira!"},{input:" \t\n ",expected:"Name fehlt"},{input:"",expected:"Name fehlt"},{input:"Ali Can",expected:"Hallo Ali Can!"}],
    hints: ["Speichere eingabe.trim() in einer neuen Variable.", "Prüfe name.length === 0, bevor du die Begrüßung erzeugst."],
    solution: "function eingabeBegruessen(eingabe) {\n  const name = eingabe.trim();\n  if (name.length === 0) return 'Name fehlt';\n  return `Hallo ${name}!`;\n}",
    explanation: "trim bereinigt die Ränder. Die Längenprüfung erkennt auch eine ursprünglich nur aus Leerraum bestehende Eingabe. Der innere Abstand in 'Ali Can' wird erhalten.",
  }),
  lesson({
    id: "js-text-lines", name: ".split() & Textdateien", title: "Textdateien in Zeilen zerlegen",
    description: "Nach dem Lesen einer Textdatei verarbeitest du ihren Inhalt als String. .split() zerlegt ihn an einem Trennzeichen oder regulären Ausdruck in ein Array.",
    syntax: "const text = await datei.text();\nconst zeilen = text.split(/\\r?\\n/);",
    parts: [["datei.text()", "Browser-File-Methode: liefert ein Promise für den Textinhalt."], ["await", "Wartet in einer async-Funktion auf das Promise-Ergebnis."], [".split(/\\r?\\n/)", "Trennt sowohl LF-Zeilenumbrüche als auch Windows-CRLF."], [".filter(...) ", "Kann anschließend unerwünschte Zeilen entfernen."]],
    note: "Dateien wählst du im Browser selbst aus. Der Code-Spielplatz erhält hier bereits den Text; echte Dateien kannst du im Datei-Labor unter der Lektion öffnen.",
    detail: "LF ist \\n, CRLF ist \\r\\n. Im regulären Ausdruck bedeutet ? hier: Das vorherige Zeichen ist optional; es ist kein ternärer Operator. split liefert auch leere Einträge, beispielsweise nach einem abschließenden Zeilenumbruch. text() liest die gewählte Datei, ohne sie zu verändern.",
    functionName: "nichtLeereZeilen", parameter: "text",
    task: "Schreibe nichtLeereZeilen(text). Zerlege den Text in Zeilen, entferne äußeren Leerraum jeder Zeile und behalte nur nicht leere Zeilen. Unterstütze LF und CRLF. Gib ein Array mit Strings zurück.",
    tests: [{input:" Hallo \n\n Welt \n",expected:["Hallo","Welt"]},{input:"A\r\n B \r\n",expected:["A","B"]},{input:"",expected:[]},{input:" \t\n ",expected:[]}],
    hints: ["Beginne mit text.split(/\\r?\\n/).", "Bereinige mit map und trim; entferne anschließend leere Strings mit filter."],
    solution: "function nichtLeereZeilen(text) {\n  return text.split(/\\r?\\n/)\n    .map(zeile => zeile.trim())\n    .filter(zeile => zeile.length > 0);\n}",
    explanation: "split erzeugt die Zeilenliste. map bereinigt jede Zeile; filter entfernt Einträge ohne Text. So gehen weder CRLF noch leere Abschlusszeilen als Nutzdaten in das Ergebnis ein.",
  }),
  lesson({
    id: "js-json-parse", name: "JSON.parse() & try/catch", title: "JSON einlesen und Lesefehler behandeln",
    description: "JSON.parse(text) verwandelt JSON-Text in JavaScript-Daten. Ungültiges JSON wirft einen Fehler, den try/catch abfangen kann.",
    syntax: "try {\n  return JSON.parse(text);\n} catch (fehler) {\n  return 'Ungültiges JSON';\n}",
    parts: [["JSON.parse(text)", "Liest den JSON-Text; führt ihn nicht als Programm aus."], ["try", "Umschließt den Vorgang, bei dem ein Fehler auftreten kann."], ["catch (fehler)", "Wird bei einem geworfenen Fehler ausgeführt."], ["Array.isArray(wert)", "Prüft hier zusätzlich die erwartete Datenstruktur."]],
    note: "Gültiges JSON ist nicht automatisch die passende Eingabe: Auch 42 und null sind gültiges JSON. Prüfe deshalb zusätzlich die benötigte Struktur.",
    detail: "JSON verlangt doppelte Anführungszeichen für Strings und Eigenschaftsnamen. Kommentare und ein Komma nach dem letzten Element sind nicht erlaubt. JSON.parse('{broken') wirft einen SyntaxError. eval ist für das Einlesen von Daten weder nötig noch passend.",
    functionName: "namenEinlesen", parameter: "text",
    task: "Schreibe namenEinlesen(text). Lies JSON ein. Nur ein Array, dessen Elemente alle Strings sind, ist erlaubt; gib dieses Array zurück. Bei ungültigem JSON oder falscher Datenstruktur gib 'Ungültige Namensliste' zurück.",
    tests: [{input:'["Mira","Ali"]',expected:["Mira","Ali"]},{input:'[]',expected:[]},{input:'{"name":"Mira"}',expected:"Ungültige Namensliste"},{input:'["Mira",3]',expected:"Ungültige Namensliste"},{input:'{broken',expected:"Ungültige Namensliste"},{input:'null',expected:"Ungültige Namensliste"}],
    hints: ["Rufe JSON.parse innerhalb eines try-Blocks auf.", "Prüfe Array.isArray(daten) und daten.every(name => typeof name === 'string'). Verwende dieselbe Fehlermeldung bei unpassenden Daten und im catch."],
    solution: "function namenEinlesen(text) {\n  try {\n    const daten = JSON.parse(text);\n    if (Array.isArray(daten) && daten.every(name => typeof name === 'string')) {\n      return daten;\n    }\n  } catch (fehler) {\n    return 'Ungültige Namensliste';\n  }\n  return 'Ungültige Namensliste';\n}",
    explanation: "parse übernimmt die Syntaxprüfung; der anschließende Vergleich prüft die fachliche Struktur. every ist auch bei einem leeren Array true. try/catch verhindert, dass ein Tippfehler im JSON den gesamten Ablauf beendet.",
  }),
  lesson({
    id: "js-json-stringify", name: "JSON.stringify()", title: "Daten als JSON ausgeben und speichern",
    description: "JSON.stringify(daten) erzeugt einen JSON-String. Mit einem dritten Argument kannst du lesbare Einrückung hinzufügen.",
    syntax: "const text = JSON.stringify(daten, null, 2);\nconst datei = new Blob([text], { type: 'application/json' });",
    parts: [["JSON.stringify", "Serialisiert passende JavaScript-Daten zu JSON-Text."], ["null", "Keine Ersetzungsfunktion oder Eigenschaftsauswahl."], ["2", "Zwei Leerzeichen Einrückung."], ["Blob", "Browser-Objekt für Dateiinhalte; der Download schreibt nicht beliebig auf die Festplatte."]],
    note: "undefined, Funktionen und zyklische Objekte lassen sich nicht wie gewöhnliche JSON-Daten speichern. BigInt kann einen Fehler auslösen.",
    detail: "In Objekten werden Eigenschaften mit undefined weggelassen; in Arrays werden solche Werte zu null. Zyklische Verweise verursachen einen Fehler. Für die Übung erhältst du JSON-kompatible Daten. Das Datei-Labor erzeugt daraus einen Download mit Blob, URL.createObjectURL und einem Download-Link.",
    functionName: "alsJsonDatei", parameter: "daten",
    task: "Schreibe alsJsonDatei(daten). Gib den JSON-Text mit zwei Leerzeichen Einrückung zurück. Die Eingabe ist JSON-kompatibel und soll unverändert bleiben. Die Tests vergleichen den Text einschließlich Zeilenumbrüchen.",
    tests: [{input:{name:"Mira",aktiv:true},expected:'{\n  "name": "Mira",\n  "aktiv": true\n}'},{input:[1,2],expected:'[\n  1,\n  2\n]'},{input:{},expected:'{}'},{input:"Hallo",expected:'"Hallo"'}],
    hints: ["Gib den Rückgabewert von JSON.stringify zurück.", "Verwende JSON.stringify(daten, null, 2)."],
    solution: "function alsJsonDatei(daten) {\n  return JSON.stringify(daten, null, 2);\n}",
    explanation: "Die Funktion liefert Text statt des ursprünglichen Objekts. Der dritte Parameter formatiert verschachtelte Inhalte lesbar. Der Dateidownload ist ein eigener Browser-Schritt und wird im Datei-Labor ausprobiert.",
  }),
  lesson({
    id: "js-csv-read", name: "CSV lesen mit split", title: "Einfache CSV-Daten einlesen",
    description: "CSV speichert Tabellen als Text: Zeilen stehen untereinander, Felder sind durch ein Trennzeichen getrennt.",
    syntax: "text.split(/\\r?\\n/).map(zeile => zeile.split(','))",
    parts: [[".split(/\\r?\\n/)", "Zerlegt die Tabelle in Textzeilen."], [".split(',')", "Zerlegt eine einfache Zeile in Felder."], ["String-Felder", "CSV selbst unterscheidet hier keine Zahlen-, Boolean- oder Texttypen."]],
    note: "Diese Einstiegsübung verarbeitet nur einfache CSV ohne Anführungszeichen oder Kommas innerhalb eines Felds. Allgemeines CSV braucht einen richtigen Parser.",
    detail: "'name,alter\\nMira,20' ergibt zwei Zeilen mit je zwei Strings. 20 bleibt '20', bis du es ausdrücklich umwandelst. Das Datei-Labor unterstützt zusätzlich korrekt zitierte Felder mit Kommas, Anführungszeichen und Zeilenumbrüchen.",
    functionName: "einfacheCsvLesen", parameter: "text",
    task: "Schreibe einfacheCsvLesen(text). Zerlege LF-/CRLF-Zeilen und jedes Feld an Kommas. Entferne äußeren Leerraum jedes Felds und überspringe vollständig leere Textzeilen. Gib ein Array von Zeilenarrays zurück. Die Testdaten enthalten keine Anführungszeichen und keine Kommas innerhalb eines Felds.",
    tests: [{input:"name,alter\nMira,20",expected:[["name","alter"],["Mira","20"]]},{input:" a , b \r\n1, 2\r\n",expected:[["a","b"],["1","2"]]},{input:"",expected:[]},{input:"a,,c",expected:[["a","","c"]]}],
    hints: ["Zerlege zuerst die Zeilen und entferne solche, deren trim-Ergebnis leer ist.", "Zerlege jede verbleibende Zeile mit split(',') und bereinige die Felder mit trim."],
    solution: "function einfacheCsvLesen(text) {\n  return text.split(/\\r?\\n/)\n    .filter(zeile => zeile.trim().length > 0)\n    .map(zeile => zeile.split(',').map(feld => feld.trim()));\n}",
    explanation: "Die äußere map verarbeitet Zeilen, die innere map einzelne Felder. Leere Felder bleiben erhalten, damit die Spaltenpositionen stimmen. Nur vollständig leere Textzeilen werden übersprungen.",
  }),
  lesson({
    id: "js-csv-write", name: ".join() & CSV erstellen", title: "Tabellendaten als CSV-Text erzeugen",
    description: ".join(trennzeichen) verbindet Arrayelemente zu einem String. Eine CSV-Ausgabe verbindet erst Felder, dann Zeilen.",
    syntax: "zeilen.map(zeile => zeile.join(',')).join('\\n')",
    parts: [["zeile.join(',')", "Verbindet die Felder einer Zeile durch Kommas."], [".map(...) ", "Erzeugt für jede Tabellenzeile einen Text."], [".join('\\n')", "Verbindet die Textzeilen durch Zeilenumbrüche."]],
    note: "Auch diese Aufgabe bleibt bei einfachen Feldern ohne Kommas, Anführungszeichen oder Zeilenumbrüche. Das Datei-Labor maskiert solche Sonderzeichen beim CSV-Download.",
    detail: "join gibt einen neuen String zurück und verändert das Array nicht. Für allgemeines CSV müssen Felder mit Kommas oder Zeilenumbrüchen in doppelte Anführungszeichen gesetzt werden. Ein Anführungszeichen im Feld wird dabei verdoppelt.",
    functionName: "einfacheCsvSchreiben", parameter: "zeilen",
    task: "Schreibe einfacheCsvSchreiben(zeilen). Verbinde die String-Felder jeder Zeile durch Kommas und die Zeilen durch LF-Zeilenumbrüche. Erzeuge keinen zusätzlichen Zeilenumbruch am Ende. Die Felder enthalten keine CSV-Sonderzeichen. Bei leerer Tabelle gib '' zurück.",
    tests: [{input:[["name","alter"],["Mira","20"]],expected:"name,alter\nMira,20"},{input:[],expected:""},{input:[["a","","c"]],expected:"a,,c"},{input:[["Hallo Welt"]],expected:"Hallo Welt"}],
    hints: ["map und join(',') erzeugen die einzelnen Zeilentexte.", "Verbinde diese mit join('\\n')."],
    solution: "function einfacheCsvSchreiben(zeilen) {\n  return zeilen.map(zeile => zeile.join(',')).join('\\n');\n}",
    explanation: "Der erste join setzt Kommas nur zwischen Feldern, der zweite Zeilenumbrüche nur zwischen Zeilen. Deshalb entsteht kein zusätzlicher Abschlussumbruch. Die Eingabe wird nur gelesen.",
  }),
];
