function lesson(data) {
  return {
    course: "js", category: "Stack & Queue", preserveInput: true, ...data,
    starter: `function ${data.functionName}(${data.parameter}) {\n  // Schreibe hier deine Lösung.\n}\n\nconsole.log(${data.functionName}(${JSON.stringify(data.tests[0].input)}));`,
    example: `${data.solution}\n\nconsole.log(${data.functionName}(${JSON.stringify(data.tests[0].input)}));`,
  };
}

export const linearStructureLessons = [
  lesson({
    id: "js-stack", name: "Stack: push & pop", title: "Einen Stapel mit push und pop verwenden",
    description: "Ein Stack ist ein Stapel: Der zuletzt abgelegte Wert wird zuerst entnommen. Dieses Prinzip heißt LIFO – Last In, First Out.",
    syntax: "const stapel = [];\nstapel.push('A');\nstapel.push('B');\nconst oben = stapel[stapel.length - 1]; // 'B', bleibt liegen\nconst entfernt = stapel.pop(); // 'B'",
    parts: [[".push(wert)", "Legt einen Wert oben auf den Stapel und gibt die neue Länge zurück."], [".pop()", "Entfernt den obersten Wert und gibt ihn zurück; bei einem leeren Array ergibt sich undefined."], ["stapel.length", "Prüft, wie viele Werte noch auf dem Stapel liegen."], ["stapel[stapel.length - 1]", "Liest den obersten Wert, ohne ihn zu entfernen; oft peek genannt."]],
    note: "JavaScript hat keine eingebaute Stack-Klasse. Hier verwenden wir ein Array mit push und pop. Prüfe die Länge: 0, false und '' sind ebenfalls gültige Werte.",
    detail: "Stacks helfen bei Rückgängig-Funktionen, verschachtelten Klammern oder Tiefensuche. push und pop verändern das verwendete Array. Mit einer Kopie der Eingabe kannst du arbeiten, ohne die Originaldaten zu verändern. Eine Queue entnimmt dagegen den zuerst eingefügten Wert.",
    functionName: "stapelLeeren", parameter: "werte",
    task: "Schreibe stapelLeeren(werte). Die Liste beschreibt einen Stapel von unten nach oben: Der letzte Wert liegt oben. Gib die entnommenen Werte von oben nach unten in einem neuen Array zurück. Nutze zum Üben eine Kopie und pop, bis der Stapel leer ist. Verändere werte nicht. Alternative korrekte Lösungen sind erlaubt.",
    tests: [{ input: ["A", "B", "C"], expected: ["C", "B", "A"] }, { input: [], expected: [] }, { input: [0, false, ""], expected: ["", false, 0] }, { input: [7], expected: [7] }, { input: [1, 2, 1, 3], expected: [3, 1, 2, 1] }],
    hints: ["Erzeuge const stapel = [...werte] und ein leeres Ergebnisarray.", "Solange stapel.length > 0 ist, lege stapel.pop() im Ergebnis ab."],
    solution: "function stapelLeeren(werte) {\n  const stapel = [...werte];\n  const entnommen = [];\n  while (stapel.length > 0) {\n    entnommen.push(stapel.pop());\n  }\n  return entnommen;\n}",
    explanation: "Die Kopie enthält den Stapel in ursprünglicher Reihenfolge. pop entnimmt jeweils den letzten Wert; push sammelt ihn in der Ausgabe. Die Längenprüfung funktioniert auch bei 0, false oder einem leeren String auf dem Stapel.",
  }),
  lesson({
    id: "js-stack-undo", name: "Stack: Undo", title: "Änderungen mit einem Undo-Stapel zurücknehmen",
    description: "Eine Rückgängig-Funktion speichert frühere Zustände auf einem Stack. Undo stellt den zuletzt gespeicherten Zustand zuerst wieder her.",
    syntax: "verlauf.push(text);\ntext = neuerText;\n// Rückgängig:\nif (verlauf.length > 0) text = verlauf.pop();",
    parts: [["verlauf.push(text)", "Speichert den bisherigen Zustand vor einer Änderung."], ["text = neuerText", "Ersetzt den aktuellen Inhalt."], ["verlauf.pop()", "Entnimmt den zuletzt gesicherten Zustand."], ["Leerer Verlauf", "Ein weiterer Undo-Befehl lässt den aktuellen Text unverändert."]],
    note: "Speichere den Zustand vor der Änderung. Ein leerer String ist ein gültiger früherer Zustand und darf beim Wiederherstellen nicht übersprungen werden.",
    detail: "Die Aufgabe modelliert einen kleinen Texteditor. Jede schreiben-Aktion ersetzt den ganzen Text und speichert den bisherigen Zustand – auch wenn der neue Text gleich ist. undo verbraucht einen Verlaufseintrag. Redo und eine begrenzte Verlaufslänge wären eigene Erweiterungen.",
    functionName: "textMitUndo", parameter: "aktionen",
    task: "Schreibe textMitUndo(aktionen). Beginne mit text = '' und einem leeren Verlauf. Bei {typ: 'schreiben', text: '…'} speichere den aktuellen Text und ersetze ihn. Bei {typ: 'undo'} stelle den letzten Zustand wieder her, falls vorhanden. Gib {text, verlauf} zurück; verlauf steht von ältestem bis neuestem Zustand. Die Eingabe enthält nur diese beiden Aktionstypen und bleibt unverändert.",
    tests: [
      { input: [{ typ: "schreiben", text: "A" }, { typ: "schreiben", text: "AB" }, { typ: "undo" }], expected: { text: "A", verlauf: [""] } },
      { input: [], expected: { text: "", verlauf: [] } },
      { input: [{ typ: "undo" }, { typ: "schreiben", text: "A" }, { typ: "undo" }, { typ: "undo" }], expected: { text: "", verlauf: [] } },
      { input: [{ typ: "schreiben", text: "A" }, { typ: "schreiben", text: "B" }, { typ: "undo" }, { typ: "schreiben", text: "C" }], expected: { text: "C", verlauf: ["", "A"] } },
      { input: [{ typ: "schreiben", text: "A" }, { typ: "schreiben", text: "A" }, { typ: "undo" }], expected: { text: "A", verlauf: [""] } },
    ],
    hints: ["Durchlaufe die Aktionen mit for…of. Sichere bei schreiben zuerst den alten Text.", "Bei undo prüfst du verlauf.length > 0 und weist anschließend verlauf.pop() zu."],
    solution: "function textMitUndo(aktionen) {\n  let text = '';\n  const verlauf = [];\n  for (const aktion of aktionen) {\n    if (aktion.typ === 'schreiben') {\n      verlauf.push(text);\n      text = aktion.text;\n    } else if (verlauf.length > 0) {\n      text = verlauf.pop();\n    }\n  }\n  return { text, verlauf };\n}",
    explanation: "Der Stack speichert frühere Zustände, nicht den neuen Text. Undo entnimmt den neuesten davon. Nach einem Undo kann eine neue Änderung den wiederhergestellten Zustand erneut sichern. Überzählige Undo-Befehle verändern nichts.",
  }),
  lesson({
    id: "js-queue", name: "Queue: push & shift", title: "Eine Warteschlange in Ankunftsreihenfolge abarbeiten",
    description: "Eine Queue ist eine Warteschlange: Der zuerst hinzugefügte Wert wird zuerst entnommen. Das Prinzip heißt FIFO – First In, First Out.",
    syntax: "const warteschlange = [];\nwarteschlange.push('Auftrag A');\nwarteschlange.push('Auftrag B');\nconst naechster = warteschlange.shift(); // 'Auftrag A'",
    parts: [[".push(wert)", "Hängt einen Wert am Ende an: enqueue."], [".shift()", "Entfernt den ersten Wert und gibt ihn zurück: dequeue."], ["warteschlange[0]", "Liest den nächsten Wert, ohne ihn zu entfernen."], ["FIFO", "Erhält die Ankunftsreihenfolge; ein Stack würde die neuesten Werte zuerst entnehmen."]],
    note: "shift verändert das Array und verschiebt die folgenden Indizes. Für kleine Listen ist das anschaulich; viele Entnahmen aus großen Arrays können teuer werden.",
    detail: "Queues passen zu Druckaufträgen, ausstehenden Aufgaben oder Breitensuche. JavaScript stellt keine allgemeine eingebaute Queue-Klasse bereit. Im nächsten Schritt vermeidest du shift mit einem Kopfindex. In dieser Übung wird die Reihenfolge getestet, keine bestimmte Syntax erzwungen.",
    functionName: "auftraegeAbarbeiten", parameter: "auftraege",
    task: "Schreibe auftraegeAbarbeiten(auftraege). Gib alle Aufträge in ihrer Ankunftsreihenfolge in einem neuen Array zurück. Verwende zum Üben eine Kopie als Queue und entnimm mit shift, bis sie leer ist. Verändere die Eingabe nicht; doppelte Aufträge bleiben erhalten.",
    tests: [{ input: ["Druck A", "Druck B", "Druck C"], expected: ["Druck A", "Druck B", "Druck C"] }, { input: [], expected: [] }, { input: [0, false, ""], expected: [0, false, ""] }, { input: ["A", "A", "B"], expected: ["A", "A", "B"] }, { input: [4], expected: [4] }],
    hints: ["Kopiere die Auftragsliste und lege ein leeres Ergebnisarray an.", "Prüfe die Länge und sammle warteschlange.shift() im Ergebnis."],
    solution: "function auftraegeAbarbeiten(auftraege) {\n  const warteschlange = [...auftraege];\n  const erledigt = [];\n  while (warteschlange.length > 0) {\n    erledigt.push(warteschlange.shift());\n  }\n  return erledigt;\n}",
    explanation: "push würde neue Aufträge hinten einreihen, shift entnimmt jeweils vorne. Deshalb bleibt die Reihenfolge erhalten. Die Kopie schützt die Eingabe; eine Wertprüfung statt der Länge würde gültige Werte wie 0 übersehen.",
  }),
  lesson({
    id: "js-queue-head", name: "Queue: Kopfindex", title: "Eine Queue ohne wiederholtes shift verwalten",
    description: "Ein Kopfindex zeigt auf das nächste Element einer Queue. Beim Entnehmen wächst der Index; die restlichen Arrayelemente müssen nicht jedes Mal verschoben werden.",
    syntax: "const werte = [];\nlet kopf = 0;\nwerte.push('A');\nif (kopf < werte.length) {\n  const entnommen = werte[kopf];\n  kopf += 1;\n}\nconst offen = werte.slice(kopf);",
    parts: [["kopf", "Index des nächsten noch nicht entnommenen Werts."], ["kopf < werte.length", "Prüft, ob ein Wert verfügbar ist."], ["werte[kopf++]", "Liest am bisherigen Index und erhöht ihn danach; hier schreiben wir beide Schritte getrennt."], ["werte.slice(kopf)", "Erzeugt ein Array der noch offenen Werte."], ["werte.length - kopf", "Anzahl der noch verfügbaren Werte."]],
    note: "Erhöhe kopf nur bei einer erfolgreichen Entnahme. Ein dequeue auf einer leeren Queue darf spätere enqueue-Werte nicht überspringen.",
    detail: "Ein Array mit shift kann bei vielen Entnahmen wiederholt Elemente verschieben. Mit einem Kopfindex liest du direkt die nächste Position. Verbrauchte Einträge bleiben in dieser einfachen Version im Array; für langlebige Queues folgen später Kompaktierung oder ein Ringpuffer. Die Übung prüft FIFO-Verhalten, keine Laufzeitkomplexität.",
    functionName: "queueProtokoll", parameter: "aktionen",
    task: "Schreibe queueProtokoll(aktionen). Bei {typ: 'enqueue', wert: …} füge den Wert hinten hinzu. Bei {typ: 'dequeue'} entnimm vorne und sammle den Wert in entnommen; ist die Queue leer, sammle null. Gib {entnommen, offen} zurück. Nutze zum Üben push, einen Kopfindex und slice. Nur diese Aktionstypen und Zahlen, Strings oder Booleans werden eingegeben. Die Eingabe bleibt unverändert.",
    tests: [
      { input: [{ typ: "enqueue", wert: "A" }, { typ: "enqueue", wert: "B" }, { typ: "dequeue" }], expected: { entnommen: ["A"], offen: ["B"] } },
      { input: [], expected: { entnommen: [], offen: [] } },
      { input: [{ typ: "dequeue" }, { typ: "enqueue", wert: "A" }, { typ: "dequeue" }, { typ: "dequeue" }], expected: { entnommen: [null, "A", null], offen: [] } },
      { input: [{ typ: "enqueue", wert: 0 }, { typ: "enqueue", wert: false }, { typ: "enqueue", wert: "" }, { typ: "dequeue" }, { typ: "dequeue" }], expected: { entnommen: [0, false], offen: [""] } },
      { input: [{ typ: "enqueue", wert: "A" }, { typ: "dequeue" }, { typ: "enqueue", wert: "B" }, { typ: "enqueue", wert: "B" }, { typ: "dequeue" }], expected: { entnommen: ["A", "B"], offen: ["B"] } },
    ],
    hints: ["Verwalte werte = [], kopf = 0 und entnommen = []. enqueue verwendet push.", "Bei dequeue: Ist kopf < werte.length, sammle werte[kopf] und erhöhe kopf. Sonst sammle null, ohne den Index zu ändern. offen ist werte.slice(kopf)."],
    solution: "function queueProtokoll(aktionen) {\n  const werte = [];\n  let kopf = 0;\n  const entnommen = [];\n  for (const aktion of aktionen) {\n    if (aktion.typ === 'enqueue') {\n      werte.push(aktion.wert);\n    } else if (kopf < werte.length) {\n      entnommen.push(werte[kopf]);\n      kopf += 1;\n    } else {\n      entnommen.push(null);\n    }\n  }\n  return { entnommen, offen: werte.slice(kopf) };\n}",
    explanation: "enqueue hängt am Ende an. dequeue liest vorne am Kopfindex und bewegt diesen nur bei einem vorhandenen Wert weiter. So funktionieren auch leere Entnahmen vor späteren Einfügungen sowie 0 und false. slice kopiert nur die noch offenen Werte in die Ausgabe.",
  }),
];
