function lesson(data) {
  return {
    course: "js", category: "Verkettete Listen", preserveInput: true, ...data,
    starter: `function ${data.functionName}(${data.parameter}) {\n  // Schreibe hier deine Lösung.\n}\n\nconsole.log(${data.functionName}(${JSON.stringify(data.tests[0].input)}));`,
    example: `${data.solution}\n\nconsole.log(${data.functionName}(${JSON.stringify(data.tests[0].input)}));`,
  };
}

function chain(werte) {
  let kopf = null;
  for (let i = werte.length - 1; i >= 0; i -= 1) kopf = { wert: werte[i], next: kopf };
  return kopf;
}

export const linkedStructureLessons = [
  lesson({
    id: "js-stack-brackets", category: "Stack & Queue", name: "Klammern prüfen", title: "Verschachtelte Klammern mit einem Stack prüfen",
    description: "Eine schließende Klammer muss zur zuletzt geöffneten Klammer passen. Ein Stack merkt sich die noch offenen Klammern in genau dieser Reihenfolge.",
    syntax: "const passend = { ')': '(', ']': '[', '}': '{' };\nif (passend[zeichen] !== stapel.pop()) return false;",
    parts: [[".push(zeichen)", "Legt eine öffnende Klammer auf den Stack."], ["passend[zeichen]", "Liest aus einem Objekt die passende öffnende Klammer."], [".pop()", "Entnimmt die zuletzt noch offene Klammer."], ["!==", "Erkennt unterschiedliche Klammerarten oder einen leeren Stack."], ["stapel.length === 0", "Am Ende dürfen keine ungeschlossenen Klammern übrig bleiben."]],
    note: "Nur die Anzahl der Klammern zu zählen reicht nicht: ([)] hat gleich viele öffnende und schließende Klammern, ist aber falsch verschachtelt.",
    detail: "Die Aufgabe prüft die drei Klammerarten (), [] und {} in einem gewöhnlichen Text. Andere Zeichen werden ignoriert. Sie ist kein JavaScript-Parser: Auch Klammern innerhalb von Anführungszeichen oder Kommentaren werden als Klammern behandelt. Eine leere Zeichenfolge ist gültig. Jede Klammer wird einmal verarbeitet; der Stack kann im schlimmsten Fall so groß wie der Text werden.",
    functionName: "klammernGueltig", parameter: "text",
    task: "Schreibe klammernGueltig(text). Gib true zurück, wenn (), [] und {} vollständig und in korrekter Reihenfolge verschachtelt sind, sonst false. Ignoriere alle anderen Zeichen. Jede schließende Klammer muss zur zuletzt geöffneten passen; am Ende muss der Stack leer sein.",
    tests: [{ input: "{[()]}", expected: true }, { input: "([)]", expected: false }, { input: ")(", expected: false }, { input: "(", expected: false }, { input: "", expected: true }, { input: "()[]{}", expected: true }, { input: "(a + [b * c])", expected: true }, { input: "Text ohne Klammern", expected: true }, { input: "[}", expected: false }],
    hints: ["Sammle öffnende Klammern auf einem Stack. Ein Objekt ordnet ')', ']' und '}' ihren Partnern zu.", "Prüfe bei jeder schließenden Klammer passend[zeichen] !== stapel.pop(). Wenn sie nicht passt, gib false zurück. Am Ende prüfst du die Länge."],
    solution: "function klammernGueltig(text) {\n  const stapel = [];\n  const passend = { ')': '(', ']': '[', '}': '{' };\n  for (const zeichen of text) {\n    if ('([{'.includes(zeichen)) {\n      stapel.push(zeichen);\n    } else if (')]}'.includes(zeichen)) {\n      if (passend[zeichen] !== stapel.pop()) return false;\n    }\n  }\n  return stapel.length === 0;\n}",
    explanation: "Öffnende Klammern werden abgelegt. Eine schließende Klammer muss zum obersten Stackeintrag passen; bei leerem Stack ergibt pop undefined und der Vergleich schlägt ebenfalls fehl. Übrig gebliebene offene Klammern machen den Text am Ende ungültig.",
  }),
  lesson({
    id: "js-linked-build", name: "Liste aufbauen", title: "Eine verkettete Liste aus Knoten aufbauen",
    description: "Eine einfach verkettete Liste besteht aus Knoten. Jeder Knoten enthält einen Wert und eine Referenz auf den nächsten Knoten; null markiert das Ende.",
    syntax: "const letzter = { wert: 'B', next: null };\nconst kopf = { wert: 'A', next: letzter };\n// A → B → null",
    parts: [["{ wert, next }", "Ein gewöhnliches JavaScript-Objekt als Knoten."], ["kopf", "Referenz auf den ersten Knoten; bei einer leeren Liste null."], ["next", "Referenz auf den nächsten Knoten, kein Arrayindex."], ["null", "Kennzeichnet ausdrücklich das Ende der Kette."], ["kopf = { wert, next: kopf }", "Setzt einen neuen Knoten vor die bisherige Liste."]],
    note: "next ist hier unser gewählter Eigenschaftsname, keine eingebaute JavaScript-Methode. Durch kopf = neuerKnoten wird die Variable neu zugewiesen; dadurch ändert sich der bisherige Knoten nicht.",
    detail: "In JavaScript werden Objekte über Referenzen verknüpft; du verwaltest keine rohen Speicheradressen. Ein Array erlaubt den Zugriff per Index. In einer verketteten Liste musst du dagegen next-Verweisen folgen. Für viele Alltagssituationen bleiben Arrays einfacher. Diese Übung baut eine endliche Liste ohne Zyklen auf.",
    functionName: "listeBauen", parameter: "werte",
    task: "Schreibe listeBauen(werte). Baue aus den primitiven Werten eine neue Liste mit Knoten {wert, next}. Die Reihenfolge entspricht dem Array. Der letzte Knoten hat next: null; bei leerem Array gib null zurück. Verändere das Array nicht. Tipp: Gehe rückwärts durch die Werte und setze neue Knoten vor den bisherigen Kopf.",
    tests: [{ input: ["A", "B"], expected: { wert: "A", next: { wert: "B", next: null } } }, { input: [], expected: null }, { input: [0, false, ""], expected: { wert: 0, next: { wert: false, next: { wert: "", next: null } } } }, { input: [null], expected: { wert: null, next: null } }, { input: [1, 1, 2], expected: { wert: 1, next: { wert: 1, next: { wert: 2, next: null } } } }],
    hints: ["Beginne mit let kopf = null. Starte die Schleife bei werte.length - 1.", "Solange i >= 0 ist: kopf = { wert: werte[i], next: kopf }. Gib danach kopf zurück."],
    solution: "function listeBauen(werte) {\n  let kopf = null;\n  for (let i = werte.length - 1; i >= 0; i -= 1) {\n    kopf = { wert: werte[i], next: kopf };\n  }\n  return kopf;\n}",
    explanation: "Zuerst entsteht der letzte Knoten mit next: null. Jeder weitere Knoten wird davor gesetzt und verweist auf die bisherige Liste. Weil die Eingabe rückwärts durchlaufen wird, stehen die Knoten am Ende in der ursprünglichen Reihenfolge.",
  }),
  lesson({
    id: "js-linked-read", name: "next durchlaufen", title: "Eine verkettete Liste Knoten für Knoten lesen",
    description: "Du durchläufst eine verkettete Liste, indem du beim Kopf beginnst und wiederholt next liest. Beim Endmarker null endet der Durchlauf.",
    syntax: "let knoten = kopf;\nwhile (knoten !== null) {\n  werte.push(knoten.wert);\n  knoten = knoten.next;\n}",
    parts: [["let knoten = kopf", "Eine bewegliche Referenz auf den aktuell gelesenen Knoten."], ["knoten !== null", "Prüft den Knoten selbst, nicht dessen Wert."], ["knoten.wert", "Liest die Nutzdaten des aktuellen Knotens."], ["knoten = knoten.next", "Wechselt zum nächsten Knoten ohne die Liste zu ändern."]],
    note: "Ein Knoten mit wert: null ist ein vorhandener Knoten. Erst eine Knotenreferenz null markiert das Ende. Auch 0, false und '' dürfen den Durchlauf nicht abbrechen.",
    detail: "Die Eingabe enthält nur gültige endliche Ketten aus {wert, next}; der letzte next-Verweis ist null. Zyklenerkennung und ungültige Knotenschemata folgen später. Zum Lesen des letzten Knotens brauchst du zuerst dessen Wert und erst danach den Wechsel zu next. Das bloße Umsetzen deiner lokalen Referenz verändert keine next-Eigenschaft.",
    functionName: "listeLesen", parameter: "kopf",
    task: "Schreibe listeLesen(kopf). Sammle alle Knotenwerte vom Kopf bis zum Ende in einem neuen Array. Bei kopf === null gib [] zurück. Erhalte auch Werte null, 0, false und ''. Verändere keinen Knoten und keinen next-Verweis.",
    tests: [{ input: { wert: "A", next: { wert: "B", next: null } }, expected: ["A", "B"] }, { input: null, expected: [] }, { input: { wert: 0, next: { wert: false, next: { wert: "", next: null } } }, expected: [0, false, ""] }, { input: { wert: null, next: { wert: 7, next: null } }, expected: [null, 7] }, { input: { wert: 1, next: null }, expected: [1] }],
    hints: ["Erzeuge ein Ergebnisarray und verwende eine lokale Variable knoten für den aktuellen Knoten.", "Solange knoten !== null ist: Sammle knoten.wert, dann gehe zu knoten.next."],
    solution: "function listeLesen(kopf) {\n  const werte = [];\n  let knoten = kopf;\n  while (knoten !== null) {\n    werte.push(knoten.wert);\n    knoten = knoten.next;\n  }\n  return werte;\n}",
    explanation: "Die lokale Referenz wandert durch die Kette, während die Knoten unverändert bleiben. Jeder Wert wird gelesen, bevor next zum folgenden Knoten führt. Die Schleife prüft das Ende der Liste, nicht den Wahrheitswert ihrer Nutzdaten.",
  }),
  lesson({
    id: "js-linked-prepend", name: "Vorne einfügen", title: "Einen neuen Knoten vor eine Liste setzen",
    description: "Vorne einfügen benötigt einen neuen Knoten, dessen next auf den bisherigen Kopf zeigt. Der neue Knoten wird zum Kopf; die bestehende Kette bleibt erhalten.",
    syntax: "const neuerKopf = { wert: neuerWert, next: bisherigerKopf };",
    parts: [["neuer Knoten", "Ein neu erzeugtes Objekt mit wert und next."], ["next: bisherigerKopf", "Verknüpft den neuen Knoten mit der bestehenden Liste."], ["kopf: null", "Auch vor einer leeren Liste funktioniert dieselbe Einfügeoperation."], ["Referenz teilen", "Neue und alte Liste verwenden die bestehenden Knoten gemeinsam."]],
    note: "Vorne einfügen verändert in dieser Aufgabe den alten Kopf nicht. Die bestehenden Knoten werden aber auch nicht tief kopiert: Wenn du sie später mutierst, ist die Änderung über beide Listen sichtbar.",
    detail: "Am bekannten Kopf kannst du ohne Durchlaufen einen Knoten einfügen. Zum Einfügen am Ende müsstest du bei einer Liste ohne gespeicherte Endreferenz zunächst den letzten Knoten suchen. Die Tests prüfen Struktur und unveränderte Eingabe; eine tiefe Kopie mit gleichem Ergebnis wird ebenfalls akzeptiert.",
    functionName: "vorneEinfuegen", parameter: "daten",
    task: "Schreibe vorneEinfuegen(daten). daten enthält {wert, kopf}. Gib einen neuen Knoten {wert: daten.wert, next: daten.kopf} als neuen Kopf zurück. Der alte Kopf und alle bestehenden Knoten bleiben unverändert. kopf darf null sein. Der neue Wert darf ebenfalls null sein.",
    tests: [{ input: { wert: "A", kopf: { wert: "B", next: null } }, expected: { wert: "A", next: { wert: "B", next: null } } }, { input: { wert: 0, kopf: null }, expected: { wert: 0, next: null } }, { input: { wert: null, kopf: { wert: false, next: null } }, expected: { wert: null, next: { wert: false, next: null } } }, { input: { wert: "", kopf: { wert: "B", next: { wert: "C", next: null } } }, expected: { wert: "", next: { wert: "B", next: { wert: "C", next: null } } } }],
    hints: ["Du musst den alten Kopf weder ändern noch durchlaufen.", "Erzeuge ein neues Objekt und verwende daten.kopf als dessen next-Wert."],
    solution: "function vorneEinfuegen(daten) {\n  return { wert: daten.wert, next: daten.kopf };\n}",
    explanation: "Der neue Knoten enthält den neuen Wert und zeigt auf die bisherige Kette. Bei einer leeren Liste wird next automatisch null. Die neue Objektinstanz ergänzt die Struktur, ohne alte Knoten zu überschreiben.",
  }),
  lesson({
    id: "js-linked-search", name: "Wert suchen", title: "Den ersten Treffer in einer verketteten Liste finden",
    description: "Zum Suchen gehst du vom Kopf aus durch die Knoten und vergleichst jeden Wert. Der erste Treffer bestimmt die Position; ohne Treffer ergibt sich -1.",
    syntax: "let position = 0;\nif (knoten.wert === gesucht) return position;\nknoten = knoten.next;\nposition += 1;",
    parts: [["===", "Vergleicht ohne automatische Typumwandlung: 1 und '1' sind verschieden."], ["position", "Zählt ab 0 die bereits durchlaufenen Knoten."], ["return position", "Beendet die Suche beim ersten passenden Knoten."], ["-1", "Kennzeichnet einen fehlenden Treffer; Position 0 ist dagegen ein gültiger Treffer."]],
    note: "Prüfe nicht if (position), um einen Treffer zu erkennen: 0 ist falsy und -1 ist truthy. Ein Treffer liegt bei position >= 0 vor.",
    detail: "Die Eingabe enthält eine gültige endliche Liste mit primitiven JSON-Werten und einen gesuchten primitiven Wert. Die Suche liest Knoten und verändert sie nicht. Anders als beim Array kannst du eine Position nicht direkt anspringen; im schlechtesten Fall musst du alle Knoten durchlaufen. Diese Übung sucht Werte, keine Objektidentitäten.",
    functionName: "listenPosition", parameter: "daten",
    task: "Schreibe listenPosition(daten). daten enthält {kopf, gesucht}. Gib die Position des ersten Knotens zurück, dessen wert mit === zu gesucht passt. Zähle ab 0. Bei einer leeren Liste oder fehlendem Treffer gib -1 zurück. Erhalte die Liste unverändert und unterscheide Zahlen, Strings, Booleans und null.",
    tests: [
      { input: { kopf: chain(["A", "B", "C"]), gesucht: "B" }, expected: 1 },
      { input: { kopf: null, gesucht: "A" }, expected: -1 },
      { input: { kopf: chain(["A", "A", "B"]), gesucht: "A" }, expected: 0 },
      { input: { kopf: chain([1, "1", false, 0, "", null]), gesucht: "1" }, expected: 1 },
      { input: { kopf: chain([1, "1", false, 0, "", null]), gesucht: false }, expected: 2 },
      { input: { kopf: chain([1, "1", false, 0, "", null]), gesucht: 0 }, expected: 3 },
      { input: { kopf: chain([1, "1", false, 0, "", null]), gesucht: "" }, expected: 4 },
      { input: { kopf: chain([1, "1", false, 0, "", null]), gesucht: null }, expected: 5 },
      { input: { kopf: chain(["A", "B"]), gesucht: "X" }, expected: -1 },
    ],
    hints: ["Beginne am Kopf und mit position = 0. Prüfe den Knoten selbst auf null.", "Bei knoten.wert === daten.gesucht gibst du die Position sofort zurück. Sonst gehe weiter und erhöhe sie. Nach der Schleife folgt return -1."],
    solution: "function listenPosition(daten) {\n  let knoten = daten.kopf;\n  let position = 0;\n  while (knoten !== null) {\n    if (knoten.wert === daten.gesucht) return position;\n    knoten = knoten.next;\n    position += 1;\n  }\n  return -1;\n}",
    explanation: "Jeder Knoten wird der Reihe nach geprüft. return beendet die Funktion beim ersten Treffer, sodass spätere gleiche Werte nicht die Position überschreiben. Die strikte Gleichheit erhält die Werttypen; der Endmarker wird unabhängig von den Nutzdaten geprüft.",
  }),
  lesson({
    id: "js-linked-delete", name: "Ersten Treffer löschen", title: "Einen Knoten entfernen und die übrigen Werte erhalten",
    description: "Beim Entfernen soll die Kette ohne den ausgewählten Knoten weiterführen. In dieser Übung entsteht eine neue Liste, damit die ursprüngliche Kette unverändert bleibt.",
    syntax: "if (!entfernt && knoten.wert === gesucht) {\n  entfernt = true;\n} else {\n  ende.next = { wert: knoten.wert, next: null };\n  ende = ende.next;\n}",
    parts: [["entfernt", "Merkt sich, ob der erste Treffer schon übersprungen wurde."], ["!entfernt && …", "Erlaubt genau eine Entfernung, auch bei mehreren gleichen Werten."], ["Hilfsknoten", "Ein zusätzlicher Startknoten vereinfacht Kopf, leere Liste und erste Einfügung."], ["ende.next = neuerKnoten", "Verknüpft einen neu erzeugten Knoten mit der neuen Ergebnisliste."], ["start.next", "Gibt die echte Liste ohne den zusätzlichen Hilfsknoten zurück."]],
    note: "Die Zuweisung ende.next verändert hier nur neu erzeugte Knoten. Würdest du next eines Eingabeknotens ändern, würdest du die alte Liste mutieren; das ist in dieser Aufgabe nicht erlaubt.",
    detail: "Der erste passende Wert wird ausgelassen, weitere gleiche Werte bleiben erhalten. Ohne Treffer enthält die Ergebnisliste alle Werte. Beim letzten verbleibenden Knoten endet next mit null. Die Lösung kopiert alle erhaltenen Knoten; auch andere Lösungen mit unveränderter Eingabe und gleichem Ergebnis sind erlaubt. In-place-Löschen wäre eine andere Aufgabenstellung.",
    functionName: "erstenWertEntfernen", parameter: "daten",
    task: "Schreibe erstenWertEntfernen(daten) für {kopf, gesucht}. Gib eine Liste zurück, in der nur der erste Knoten mit wert === gesucht fehlt. Erhalte Reihenfolge und spätere Duplikate. Bei keinem Treffer bleiben alle Werte erhalten; ist das Ergebnis leer, gib null zurück. Kein Eingabeknoten darf verändert werden. Die Werte sind primitive JSON-Werte.",
    tests: [
      { input: { kopf: chain(["A", "B", "A"]), gesucht: "A" }, expected: chain(["B", "A"]) },
      { input: { kopf: chain(["A", "B", "C"]), gesucht: "B" }, expected: chain(["A", "C"]) },
      { input: { kopf: chain(["A", "B"]), gesucht: "B" }, expected: chain(["A"]) },
      { input: { kopf: null, gesucht: "A" }, expected: null },
      { input: { kopf: chain(["A"]), gesucht: "A" }, expected: null },
      { input: { kopf: chain(["A", "B"]), gesucht: "X" }, expected: chain(["A", "B"]) },
      { input: { kopf: chain([false, 0, false]), gesucht: false }, expected: chain([0, false]) },
      { input: { kopf: chain([1, "1", null, ""]), gesucht: "1" }, expected: chain([1, null, ""]) },
      { input: { kopf: chain([0, null, ""]), gesucht: null }, expected: chain([0, ""]) },
    ],
    hints: ["Lege start = { next: null }, ende = start und entfernt = false an. Durchlaufe die alte Liste, ohne ihre next-Felder zu ändern.", "Überspringe den ersten Treffer und setze entfernt auf true. Für jeden anderen Wert erzeuge einen neuen Knoten, hänge ihn an ende.next und bewege ende weiter. Gib start.next zurück."],
    solution: "function erstenWertEntfernen(daten) {\n  const start = { next: null };\n  let ende = start;\n  let entfernt = false;\n  let knoten = daten.kopf;\n  while (knoten !== null) {\n    if (!entfernt && knoten.wert === daten.gesucht) {\n      entfernt = true;\n    } else {\n      ende.next = { wert: knoten.wert, next: null };\n      ende = ende.next;\n    }\n    knoten = knoten.next;\n  }\n  return start.next;\n}",
    explanation: "Der Hilfsknoten ist nur ein Anker für die neue Kette. Die erste Übereinstimmung wird übersprungen; die Markierung verhindert das Entfernen weiterer Duplikate. Alle anderen Werte werden in ihrer Reihenfolge kopiert. Die Eingabeknoten bleiben unverändert.",
  }),
  lesson({
    id: "js-linked-reverse", name: "Liste umkehren", title: "Eine verkettete Liste ohne Eingabemutation umkehren",
    description: "Du kannst eine Liste umkehren, indem du ihre Werte von vorne liest und für jeden Wert einen neuen Knoten vor die bisherige Ergebnisliste setzt.",
    syntax: "let umgekehrt = null;\numgekehrt = { wert: knoten.wert, next: umgekehrt };\n// A → B → C wird C → B → A",
    parts: [["umgekehrt = null", "Beginnt mit einer leeren Ergebnisliste."], ["neuer Knoten vor dem Ergebnis", "Der zuletzt gelesene Wert wird zum neuen Kopf."], ["next: umgekehrt", "Verknüpft den neuen Knoten mit dem bisherigen Ergebnis."], ["knoten = knoten.next", "Liest die Eingabe weiter, ohne ihre Verweise zu ändern."]],
    note: "Das klassische Umkehren durch Überschreiben der vorhandenen next-Verweise verändert die Eingabe. Hier sollen alte und umgekehrte Liste gleichzeitig nutzbar bleiben; erzeuge deshalb neue Knoten.",
    detail: "Bei n Knoten benötigt diese Lösung einen Durchlauf und n neue Knoten. Sie braucht also lineare Zeit und zusätzlichen linearen Speicher. In-place-Umkehren mit konstantem Hilfsspeicher wäre möglich, wenn Mutation erlaubt wäre. Die Tests prüfen Ergebnis und unveränderte Eingabe, keine bestimmte Syntax oder gemessene Laufzeit.",
    functionName: "listeUmkehren", parameter: "kopf",
    task: "Schreibe listeUmkehren(kopf). Gib eine Liste mit allen Werten in umgekehrter Reihenfolge zurück. Die ursprünglichen Knoten und next-Verweise bleiben unverändert. Eine leere Liste ergibt null. Erhalte primitive Werte einschließlich null, 0, false und ''. Die Eingabe ist eine endliche gültige Liste ohne Zyklen.",
    tests: [
      { input: chain(["A", "B", "C"]), expected: chain(["C", "B", "A"]) },
      { input: null, expected: null },
      { input: chain([7]), expected: chain([7]) },
      { input: chain([0, false, "", null]), expected: chain([null, "", false, 0]) },
      { input: chain([1, 1, 2]), expected: chain([2, 1, 1]) },
      { input: chain([null, "A"]), expected: chain(["A", null]) },
    ],
    hints: ["Beginne mit umgekehrt = null und einer lokalen Referenz auf den aktuellen Eingabeknoten.", "Setze für jeden gelesenen Wert einen neuen Knoten vor umgekehrt und gehe danach in der Eingabe zu next."],
    solution: "function listeUmkehren(kopf) {\n  let umgekehrt = null;\n  let knoten = kopf;\n  while (knoten !== null) {\n    umgekehrt = { wert: knoten.wert, next: umgekehrt };\n    knoten = knoten.next;\n  }\n  return umgekehrt;\n}",
    explanation: "Zuerst wird der erste Wert zum letzten Knoten der Ergebnisliste. Jeder weitere gelesene Wert wird davor gesetzt. So entsteht die umgekehrte Reihenfolge, während die ursprüngliche Liste unverändert bleibt.",
  }),
];
