function lesson(data) {
  return {
    course: "js", category: "Verkettete Listen", preserveInput: true, ...data,
    starter: `function ${data.functionName}(${data.parameter}) {\n  // Schreibe hier deine Lösung.\n}\n\nconsole.log(${data.functionName}(${JSON.stringify(data.tests[0].input)}));`,
    example: `${data.solution}\n\nconsole.log(${data.functionName}(${JSON.stringify(data.tests[0].input)}));`,
  };
}

export const linkedStructureLessons = [
  lesson({
    id: "js-stack-brackets", category: "Stack & Queue", name: "Klammern prüfen", title: "Verschachtelte Klammern mit einem Stack prüfen",
    description: "Eine schließende Klammer muss zur zuletzt geöffneten Klammer passen. Ein Stack merkt sich die noch offenen Klammern in genau dieser Reihenfolge.",
    syntax: "const passend = { ')': '(', ']': '[', '}': '{' };\nif (passend[zeichen] !== stapel.pop()) return false;",
    parts: [[".push(zeichen)", "Legt eine öffnende Klammer auf den Stack."], ["passend[zeichen]", "Liest aus einem Objekt die passende öffnende Klammer."], [".pop()", "Entnimmt die zuletzt noch offene Klammer."], ["!==", "Erkennt unterschiedliche Klammerarten oder einen leeren Stack."], ["stapel.length === 0", "Am Ende dürfen keine ungeschlossenen Klammern übrig bleiben."]],
    note: "Nur die Anzahl der Klammern zu zählen reicht nicht: ([)] hat gleich viele öffnende und schließende Klammern, ist aber falsch verschachtelt.",
    detail: "Die Aufgabe prüft die drei Klammerarten (), [] und {} in einem gewöhnlichen Text. Andere Zeichen werden ignoriert. Sie ist kein JavaScript-Parser: Auch Klammern innerhalb von Anführungszeichen oder Kommentaren werden als Klammern behandelt. Eine leere Zeichenfolge ist gültig. Jede Klammer wird einmal verarbeitet; der Stack kann im schlimmsten Fall so groß wie der Text werden.",
    functionName: "klammernGueltig", parameter: "text",
    task: "Schreibe klammernGueltig(text). Gib true zurück, wenn (), [] und {} vollständig und in korrekter Reihenfolge verschachtelt sind, sonst false. Ignoriere alle anderen Zeichen. Jede schließende Klammer muss zur zuletzt geöffneten passen; am Ende muss der Stack leer sein.",
    tests: [{ input: "{[()]}", expected: true }, { input: "([)]", expected: false }, { input: ")(", expected: false }, { input: "(", expected: false }, { input: "", expected: true }, { input: "()[]{}", expected: true }, { input: "(a + [b * c])", expected: true }, { input: "Text ohne Klammern", expected: true }, { input: "[}", expected: false }],
    hints: ["Sammle öffnende Klammern auf einem Stack. Ein Objekt ordnet ')', ']' und '}' ihren Partnern zu.", "Prüfe bei jeder schließenden Klammer passend[zeichen] !== stapel.pop(). Wenn sie nicht passt, gib false zurück. Am Ende prüfst du die Länge."],
    solution: "function klammernGueltig(text) {\n  const stapel = [];\n  const passend = { ')': '(', ']': '[', '}': '{' };\n  for (const zeichen of text) {\n    if ('([{'.includes(zeichen)) {\n      stapel.push(zeichen);\n    } else if (')]}'.includes(zeichen)) {\n      if (passend[zeichen] !== stapel.pop()) return false;\n    }\n  }\n  return stapel.length === 0;\n}",
    explanation: "Öffnende Klammern werden abgelegt. Eine schließende Klammer muss zum obersten Stackeintrag passen; bei leerem Stack ergibt pop undefined und der Vergleich schlägt ebenfalls fehl. Übrig gebliebene offene Klammern machen den Text am Ende ungültig.",
  }),
  lesson({
    id: "js-linked-build", name: "Liste aufbauen", title: "Eine verkettete Liste aus Knoten aufbauen",
    description: "Eine einfach verkettete Liste besteht aus Knoten. Jeder Knoten enthält einen Wert und eine Referenz auf den nächsten Knoten; null markiert das Ende.",
    syntax: "const letzter = { wert: 'B', next: null };\nconst kopf = { wert: 'A', next: letzter };\n// A → B → null",
    parts: [["{ wert, next }", "Ein gewöhnliches JavaScript-Objekt als Knoten."], ["kopf", "Referenz auf den ersten Knoten; bei einer leeren Liste null."], ["next", "Referenz auf den nächsten Knoten, kein Arrayindex."], ["null", "Kennzeichnet ausdrücklich das Ende der Kette."], ["kopf = { wert, next: kopf }", "Setzt einen neuen Knoten vor die bisherige Liste."]],
    note: "next ist hier unser gewählter Eigenschaftsname, keine eingebaute JavaScript-Methode. Durch kopf = neuerKnoten wird die Variable neu zugewiesen; dadurch ändert sich der bisherige Knoten nicht.",
    detail: "In JavaScript werden Objekte über Referenzen verknüpft; du verwaltest keine rohen Speicheradressen. Ein Array erlaubt den Zugriff per Index. In einer verketteten Liste musst du dagegen next-Verweisen folgen. Für viele Alltagssituationen bleiben Arrays einfacher. Diese Übung baut eine endliche Liste ohne Zyklen auf.",
    functionName: "listeBauen", parameter: "werte",
    task: "Schreibe listeBauen(werte). Baue aus den primitiven Werten eine neue Liste mit Knoten {wert, next}. Die Reihenfolge entspricht dem Array. Der letzte Knoten hat next: null; bei leerem Array gib null zurück. Verändere das Array nicht. Tipp: Gehe rückwärts durch die Werte und setze neue Knoten vor den bisherigen Kopf.",
    tests: [{ input: ["A", "B"], expected: { wert: "A", next: { wert: "B", next: null } } }, { input: [], expected: null }, { input: [0, false, ""], expected: { wert: 0, next: { wert: false, next: { wert: "", next: null } } } }, { input: [null], expected: { wert: null, next: null } }, { input: [1, 1, 2], expected: { wert: 1, next: { wert: 1, next: { wert: 2, next: null } } } }],
    hints: ["Beginne mit let kopf = null. Starte die Schleife bei werte.length - 1.", "Solange i >= 0 ist: kopf = { wert: werte[i], next: kopf }. Gib danach kopf zurück."],
    solution: "function listeBauen(werte) {\n  let kopf = null;\n  for (let i = werte.length - 1; i >= 0; i -= 1) {\n    kopf = { wert: werte[i], next: kopf };\n  }\n  return kopf;\n}",
    explanation: "Zuerst entsteht der letzte Knoten mit next: null. Jeder weitere Knoten wird davor gesetzt und verweist auf die bisherige Liste. Weil die Eingabe rückwärts durchlaufen wird, stehen die Knoten am Ende in der ursprünglichen Reihenfolge.",
  }),
  lesson({
    id: "js-linked-read", name: "next durchlaufen", title: "Eine verkettete Liste Knoten für Knoten lesen",
    description: "Du durchläufst eine verkettete Liste, indem du beim Kopf beginnst und wiederholt next liest. Beim Endmarker null endet der Durchlauf.",
    syntax: "let knoten = kopf;\nwhile (knoten !== null) {\n  werte.push(knoten.wert);\n  knoten = knoten.next;\n}",
    parts: [["let knoten = kopf", "Eine bewegliche Referenz auf den aktuell gelesenen Knoten."], ["knoten !== null", "Prüft den Knoten selbst, nicht dessen Wert."], ["knoten.wert", "Liest die Nutzdaten des aktuellen Knotens."], ["knoten = knoten.next", "Wechselt zum nächsten Knoten ohne die Liste zu ändern."]],
    note: "Ein Knoten mit wert: null ist ein vorhandener Knoten. Erst eine Knotenreferenz null markiert das Ende. Auch 0, false und '' dürfen den Durchlauf nicht abbrechen.",
    detail: "Die Eingabe enthält nur gültige endliche Ketten aus {wert, next}; der letzte next-Verweis ist null. Zyklenerkennung und ungültige Knotenschemata folgen später. Zum Lesen des letzten Knotens brauchst du zuerst dessen Wert und erst danach den Wechsel zu next. Das bloße Umsetzen deiner lokalen Referenz verändert keine next-Eigenschaft.",
    functionName: "listeLesen", parameter: "kopf",
    task: "Schreibe listeLesen(kopf). Sammle alle Knotenwerte vom Kopf bis zum Ende in einem neuen Array. Bei kopf === null gib [] zurück. Erhalte auch Werte null, 0, false und ''. Verändere keinen Knoten und keinen next-Verweis.",
    tests: [{ input: { wert: "A", next: { wert: "B", next: null } }, expected: ["A", "B"] }, { input: null, expected: [] }, { input: { wert: 0, next: { wert: false, next: { wert: "", next: null } } }, expected: [0, false, ""] }, { input: { wert: null, next: { wert: 7, next: null } }, expected: [null, 7] }, { input: { wert: 1, next: null }, expected: [1] }],
    hints: ["Erzeuge ein Ergebnisarray und verwende eine lokale Variable knoten für den aktuellen Knoten.", "Solange knoten !== null ist: Sammle knoten.wert, dann gehe zu knoten.next."],
    solution: "function listeLesen(kopf) {\n  const werte = [];\n  let knoten = kopf;\n  while (knoten !== null) {\n    werte.push(knoten.wert);\n    knoten = knoten.next;\n  }\n  return werte;\n}",
    explanation: "Die lokale Referenz wandert durch die Kette, während die Knoten unverändert bleiben. Jeder Wert wird gelesen, bevor next zum folgenden Knoten führt. Die Schleife prüft das Ende der Liste, nicht den Wahrheitswert ihrer Nutzdaten.",
  }),
  lesson({
    id: "js-linked-prepend", name: "Vorne einfügen", title: "Einen neuen Knoten vor eine Liste setzen",
    description: "Vorne einfügen benötigt einen neuen Knoten, dessen next auf den bisherigen Kopf zeigt. Der neue Knoten wird zum Kopf; die bestehende Kette bleibt erhalten.",
    syntax: "const neuerKopf = { wert: neuerWert, next: bisherigerKopf };",
    parts: [["neuer Knoten", "Ein neu erzeugtes Objekt mit wert und next."], ["next: bisherigerKopf", "Verknüpft den neuen Knoten mit der bestehenden Liste."], ["kopf: null", "Auch vor einer leeren Liste funktioniert dieselbe Einfügeoperation."], ["Referenz teilen", "Neue und alte Liste verwenden die bestehenden Knoten gemeinsam."]],
    note: "Vorne einfügen verändert in dieser Aufgabe den alten Kopf nicht. Die bestehenden Knoten werden aber auch nicht tief kopiert: Wenn du sie später mutierst, ist die Änderung über beide Listen sichtbar.",
    detail: "Am bekannten Kopf kannst du ohne Durchlaufen einen Knoten einfügen. Zum Einfügen am Ende müsstest du bei einer Liste ohne gespeicherte Endreferenz zunächst den letzten Knoten suchen. Die Tests prüfen Struktur und unveränderte Eingabe; eine tiefe Kopie mit gleichem Ergebnis wird ebenfalls akzeptiert.",
    functionName: "vorneEinfuegen", parameter: "daten",
    task: "Schreibe vorneEinfuegen(daten). daten enthält {wert, kopf}. Gib einen neuen Knoten {wert: daten.wert, next: daten.kopf} als neuen Kopf zurück. Der alte Kopf und alle bestehenden Knoten bleiben unverändert. kopf darf null sein. Der neue Wert darf ebenfalls null sein.",
    tests: [{ input: { wert: "A", kopf: { wert: "B", next: null } }, expected: { wert: "A", next: { wert: "B", next: null } } }, { input: { wert: 0, kopf: null }, expected: { wert: 0, next: null } }, { input: { wert: null, kopf: { wert: false, next: null } }, expected: { wert: null, next: { wert: false, next: null } } }, { input: { wert: "", kopf: { wert: "B", next: { wert: "C", next: null } } }, expected: { wert: "", next: { wert: "B", next: { wert: "C", next: null } } } }],
    hints: ["Du musst den alten Kopf weder ändern noch durchlaufen.", "Erzeuge ein neues Objekt und verwende daten.kopf als dessen next-Wert."],
    solution: "function vorneEinfuegen(daten) {\n  return { wert: daten.wert, next: daten.kopf };\n}",
    explanation: "Der neue Knoten enthält den neuen Wert und zeigt auf die bisherige Kette. Bei einer leeren Liste wird next automatisch null. Die neue Objektinstanz ergänzt die Struktur, ohne alte Knoten zu überschreiben.",
  }),
];
