function lesson(data) {
  return {
    course: "js", category: "Operatoren", preserveInput: true, ...data,
    starter: `function ${data.functionName}(${data.parameter || "daten"}) {\n  // Schreibe hier deine Lösung.\n}\n\nconsole.log(${data.functionName}(${JSON.stringify(data.tests[0].input)}));`,
    example: `${data.solution}\n\nconsole.log(${data.functionName}(${JSON.stringify(data.tests[0].input)}));`,
  };
}

export const logicLessons = [
  lesson({
    id: "js-or", name: "||", title: "Alternativen erlauben mit logischem Oder",
    description: "|| verbindet Alternativen. Bei Boolean-Werten reicht eine wahre Aussage, damit das Ergebnis true ist.",
    syntax: "daten.admin || daten.inhaber",
    parts: [["||", "Logisches Oder: mindestens eine der beiden Aussagen muss wahr sein."], ["daten.admin", "Erste Alternative: Administratorzugriff."], ["daten.inhaber", "Zweite Alternative: Zugriff als Inhaber."]],
    note: "|| ist inklusiv: Sind beide Aussagen true, bleibt das Ergebnis true. | mit nur einem Strich ist ein anderer, bitweiser Operator.",
    detail: "JavaScript wertet zuerst links aus. Ist links truthy, wird rechts nicht ausgewertet. || gibt einen Operanden zurück, nicht grundsätzlich einen Boolean. In dieser Aufgabe sind beide Eingabewerte ausdrücklich Booleans.",
    functionName: "darfBearbeiten",
    task: "Schreibe darfBearbeiten(daten). Gib true zurück, wenn daten.admin oder daten.inhaber true ist. Sind beide false, gib false zurück. Beide Eigenschaften sind Booleans.",
    tests: [{input:{admin:true,inhaber:false},expected:true},{input:{admin:false,inhaber:true},expected:true},{input:{admin:true,inhaber:true},expected:true},{input:{admin:false,inhaber:false},expected:false}],
    hints: ["Du brauchst mindestens eine erfüllte Alternative, nicht beide.", "Verbinde daten.admin und daten.inhaber mit ||."],
    solution: "function darfBearbeiten(daten) {\n  return daten.admin || daten.inhaber;\n}",
    explanation: "Ist admin true, liefert || sofort true. Nur bei false wird inhaber gelesen. Auch zwei wahre Alternativen erlauben die Bearbeitung.",
  }),
  lesson({
    id: "js-not", name: "!", title: "Aussagen mit ! umkehren",
    description: "! wandelt seinen Operanden zunächst in einen Boolean um und kehrt diesen Wahrheitswert um.",
    syntax: "!daten.gesperrt",
    parts: [["!", "Logische Negation: truthy wird false, falsy wird true."], ["daten.gesperrt", "Hier ein Boolean, der den Sperrzustand beschreibt."], ["!!wert", "Zweimalige Negation ergibt den Boolean-Wert wie Boolean(wert)."]],
    note: "! ist kein Test auf ausschließlich fehlende Werte: !0, !false und !'' sind ebenfalls true. !'false' ist dagegen false.",
    detail: "! bindet stärker als && und ||. !a && b bedeutet (!a) && b. Soll eine ganze Verknüpfung umgekehrt werden, schreibe !(a && b).",
    functionName: "darfStarten",
    task: "Schreibe darfStarten(daten). Die Eingabeeigenschaft gesperrt ist ein Boolean. Gib true zurück, wenn nicht gesperrt ist, und andernfalls false.",
    tests: [{input:{gesperrt:true},expected:false},{input:{gesperrt:false},expected:true}],
    hints: ["Das Ergebnis soll genau das Gegenteil von gesperrt sein.", "return !daten.gesperrt;"],
    solution: "function darfStarten(daten) {\n  return !daten.gesperrt;\n}",
    explanation: "! macht aus einer aktiven Sperre false und aus einer fehlenden Sperre true. Das Ergebnis ist immer ein Boolean.",
  }),
  lesson({
    id: "js-or-fallback", name: "|| als Ersatzwert", title: "Was || tatsächlich zurückgibt",
    description: "|| liefert den linken Operanden, wenn er truthy ist. Andernfalls liefert es den rechten Operanden. Das Ergebnis kann Text, eine Zahl oder ein anderer Wert sein.",
    syntax: "wert || 'Standard'",
    parts: [["wert", "Wird zuerst nach den truthy/falsy-Regeln bewertet."], ["||", "Liefert einen der beiden Werte; wandelt den Rückgabewert nicht automatisch in einen Boolean um."], ["'Standard'", "Ersatzwert für eine falsy Eingabe."]],
    note: "0, false und '' werden durch || ersetzt. Sollen diese gültigen Werte erhalten bleiben, ist ?? für null/undefined oft passender.",
    detail: "'Mira' || 'Gast' ergibt 'Mira'; 0 || 10 ergibt 10. Dagegen ergibt 0 ?? 10 den Wert 0. Der Ausdruck rechts läuft nur, wenn der linke Wert falsy ist.",
    functionName: "mitStandard", parameter: "wert",
    task: "Schreibe mitStandard(wert). Gib wert zurück, wenn er truthy ist, andernfalls den String 'Standard'. In dieser Aufgabe sollen 0, false und leerer Text bewusst ersetzt werden.",
    tests: [{input:"Mira",expected:"Mira"},{input:7,expected:7},{input:0,expected:"Standard"},{input:false,expected:"Standard"},{input:"",expected:"Standard"},{input:null,expected:"Standard"},{input:"false",expected:"false"}],
    hints: ["Boolean(wert) wäre nur eine Prüfung, aber nicht der geforderte Rückgabewert.", "return wert || 'Standard';"],
    solution: "function mitStandard(wert) {\n  return wert || 'Standard';\n}",
    explanation: "|| erhält truthy Werte wie 7 und 'false'. Falsy Werte führen zum Ersatztext. Anders als ?? behandelt || also auch 0, false und leeren Text als Grund für einen Ersatz.",
  }),
  lesson({
    id: "js-short-circuit", name: "Kurzschluss mit &&", title: "Unsichere Zugriffe durch Kurzschluss vermeiden",
    description: "&& wertet die rechte Seite nur aus, wenn links truthy ist. So kann eine erste Prüfung einen folgenden Eigenschaftszugriff absichern.",
    syntax: "Boolean(daten.konto && daten.konto.aktiv)",
    parts: [["daten.konto", "Prüft zunächst, ob das Konto vorhanden und truthy ist."], ["&&", "Bei falsy links wird rechts übersprungen und der linke Wert zurückgegeben."], ["daten.konto.aktiv", "Wird erst bei vorhandenem Konto gelesen."], ["Boolean(...)", "Sorgt dafür, dass das Gesamtergebnis ausdrücklich true oder false ist."]],
    note: "null.aktiv oder undefined.aktiv würden einen Fehler auslösen. Die Reihenfolge der Prüfung ist entscheidend.",
    detail: "null && irgendEineFunktion() ergibt null, ohne die Funktion aufzurufen. true || irgendEineFunktion() überspringt den Aufruf ebenfalls. Seitenwirkungen auf der rechten Seite passieren daher nicht immer. && selbst liefert nicht grundsätzlich einen Boolean.",
    functionName: "kontoAktiv",
    task: "Schreibe kontoAktiv(daten). daten.konto fehlt, ist null oder ein Objekt mit einer optionalen Boolean-Eigenschaft aktiv. Gib immer einen Boolean zurück: nur bei aktiv: true soll er true sein. Fehlende Konten und fehlendes aktiv sollen ohne Fehler false ergeben.",
    tests: [{input:{konto:{aktiv:true}},expected:true},{input:{konto:{aktiv:false}},expected:false},{input:{konto:null},expected:false},{input:{},expected:false},{input:{konto:{}},expected:false}],
    hints: ["Prüfe das Konto vor dem Zugriff auf seine Eigenschaft.", "Boolean(daten.konto && daten.konto.aktiv) liefert auch bei fehlenden Werten false."],
    solution: "function kontoAktiv(daten) {\n  return Boolean(daten.konto && daten.konto.aktiv);\n}",
    explanation: "Ein fehlendes oder null-Konto beendet && bereits links, sodass kein unsicherer Zugriff passiert. Bei einem Konto wird aktiv gelesen. Boolean wandelt auch null oder undefined als Zwischenergebnis zuverlässig in false um.",
  }),
  lesson({
    id: "js-logic-order", name: "! → && → ||", title: "Auswertungsreihenfolge mit Klammern klären",
    description: "! bindet stärker als &&, und && stärker als ||. Klammern machen die gewünschte Gruppierung ausdrücklich sichtbar.",
    syntax: "(daten.admin || daten.inhaber) && !daten.gesperrt",
    parts: [["(admin || inhaber)", "Gruppiert die erlaubten Rollen zu einer gemeinsamen Aussage."], ["!gesperrt", "Die Sperre muss ausgeschaltet sein."], ["&&", "Beide Bedingungen müssen gelten: erlaubte Rolle und keine Sperre."]],
    note: "admin || inhaber && !gesperrt entspricht admin || (inhaber && !gesperrt). Ein gesperrter Admin käme damit trotzdem durch.",
    detail: "true || false && false ergibt true. (true || false) && false ergibt false. Operatorrangfolge bestimmt die Gruppierung; Kurzschluss bestimmt zusätzlich, welche Teile überhaupt ausgewertet werden. JavaScript erlaubt ?? nicht direkt gemischt mit && oder || ohne passende Klammern.",
    functionName: "zugriffErlaubt",
    task: "Schreibe zugriffErlaubt(daten). admin, inhaber und gesperrt sind Booleans. Erlaube Zugriff für Admins oder Inhaber, aber nur ohne Sperre. Eine Sperre gilt auch für Admins.",
    tests: [{input:{admin:true,inhaber:false,gesperrt:false},expected:true},{input:{admin:true,inhaber:false,gesperrt:true},expected:false},{input:{admin:false,inhaber:true,gesperrt:false},expected:true},{input:{admin:false,inhaber:true,gesperrt:true},expected:false},{input:{admin:false,inhaber:false,gesperrt:false},expected:false},{input:{admin:false,inhaber:false,gesperrt:true},expected:false}],
    hints: ["Fasse zuerst die erlaubten Rollen zusammen.", "(daten.admin || daten.inhaber) && !daten.gesperrt berücksichtigt die Sperre für beide Rollen."],
    solution: "function zugriffErlaubt(daten) {\n  return (daten.admin || daten.inhaber) && !daten.gesperrt;\n}",
    explanation: "Die Klammer verbindet die Rollen. && verlangt zusätzlich eine inaktive Sperre. Ist keine Rolle erlaubt, wird der Rest übersprungen. Ist eine Rolle erlaubt, entscheidet !gesperrt über den Zugriff.",
  }),
];
