function lesson(data) {
  return {
    course: "js", category: "Schleifen", preserveInput: true, ...data,
    starter: `function ${data.functionName}(${data.parameter}) {\n  // Schreibe hier deine Lösung.\n}\n\nconsole.log(${data.functionName}(${JSON.stringify(data.tests[0].input)}));`,
    example: `${data.solution}\n\nconsole.log(${data.functionName}(${JSON.stringify(data.tests[0].input)}));`,
  };
}

export const loopLessons = [
  lesson({
    id: "js-while", name: "while", title: "Wiederholen, solange eine Bedingung gilt",
    description: "while prüft eine Bedingung vor jedem Durchlauf. Solange sie truthy ist, wird der Schleifenblock erneut ausgeführt.",
    syntax: "let i = 1;\nwhile (i <= n) {\n  summe += i;\n  i++;\n}",
    parts: [["while (i <= n)", "Prüft vor jedem Durchlauf, ob der Zähler noch innerhalb der Grenze liegt."], ["summe += i", "Addiert den aktuellen Zähler zum bisherigen Ergebnis."], ["i++", "Erhöht i um 1, damit die Schleife ihre Grenze erreichen kann."]],
    note: "Fehlt eine Änderung, die die Bedingung irgendwann falsch macht, kann eine Endlosschleife entstehen. Der Spielplatz bricht solche Ausführungen nach zwei Sekunden ab.",
    detail: "Bei while stehen Startwert und Zähleränderung außerhalb beziehungsweise innerhalb des Blocks, statt im Schleifenkopf wie bei for. Ist die Bedingung schon anfangs falsch, läuft der Block kein einziges Mal. <= schließt die Grenze n ein.",
    functionName: "summeBis", parameter: "n",
    task: "Schreibe summeBis(n). Addiere die ganzen Zahlen von 1 bis einschließlich n und gib die Summe zurück. n ist eine ganze Zahl von 0 bis 100. Für n = 0 soll das Ergebnis 0 sein. Probiere eine while-Schleife; die Tests prüfen das Ergebnis.",
    tests: [{input:5,expected:15},{input:0,expected:0},{input:1,expected:1},{input:10,expected:55}],
    hints: ["Beginne mit i = 1 und ergebnis = 0.", "Solange i <= n gilt, addiere i und erhöhe danach i. Gib das Ergebnis erst nach der Schleife zurück."],
    solution: "function summeBis(n) {\n  let i = 1;\n  let ergebnis = 0;\n  while (i <= n) {\n    ergebnis += i;\n    i++;\n  }\n  return ergebnis;\n}",
    explanation: "Der Zähler läuft von 1 bis n. Jeder Durchlauf addiert einen Wert und erhöht den Zähler. Bei n = 0 ist 1 <= 0 sofort falsch und die Summe bleibt 0. Die Erhöhung sorgt dafür, dass die Schleife endet.",
  }),
  lesson({
    id: "js-for-of", name: "for…of", title: "Arraywerte direkt mit for…of durchlaufen",
    description: "for…of liefert nacheinander die Werte eines iterierbaren Objekts. Bei Arrays kannst du damit jedes Element ohne eigenen Indexzähler lesen.",
    syntax: "for (const zahl of zahlen) {\n  produkt *= zahl;\n}",
    parts: [["const zahl", "Eine neue Bindung für den aktuellen Wert in jedem Durchlauf."], ["of zahlen", "Liest die Arraywerte in ihrer Reihenfolge."], ["*=", "produkt *= zahl bedeutet hier produkt = produkt * zahl."]],
    note: "for…of liest Werte. for…in liest Eigenschaftsnamen und ist für diese Arrayaufgabe nicht die passende Alternative.",
    detail: "for…of selbst verändert das Eingabe-Array nicht. Bei Objekten als Elementen könntest du jedoch deren Eigenschaften verändern. Strings sind ebenfalls iterierbar; gewöhnliche Objektliterale wie {name: 'Mira'} sind es nicht automatisch.",
    functionName: "produkt", parameter: "zahlen",
    task: "Schreibe produkt(zahlen). Multipliziere alle Zahlen des Arrays und gib das Produkt zurück. Für ein leeres Array gilt in dieser Aufgabe das Ergebnis 1. Verändere die Eingabe nicht.",
    tests: [{input:[2,3,4],expected:24},{input:[],expected:1},{input:[-2,3],expected:-6},{input:[0,4],expected:0},{input:[0.5,4],expected:2}],
    hints: ["Beginne mit ergebnis = 1, dem neutralen Wert der Multiplikation.", "Multipliziere in for (const zahl of zahlen) das Ergebnis mit zahl."],
    solution: "function produkt(zahlen) {\n  let ergebnis = 1;\n  for (const zahl of zahlen) {\n    ergebnis *= zahl;\n  }\n  return ergebnis;\n}",
    explanation: "Die Schleife liest jeden Zahlenwert genau einmal. Der Startwert 1 verändert das erste Produkt nicht und liefert auch bei einer leeren Liste das geforderte Ergebnis. 0 macht das gesamte Produkt zu 0.",
  }),
  lesson({
    id: "js-break", name: "break", title: "Eine Schleife mit break beenden",
    description: "break beendet die umgebende Schleife sofort. Anschließend läuft der Code hinter der Schleife weiter.",
    syntax: "for (const zahl of zahlen) {\n  if (zahl < 0) {\n    break;\n  }\n  summe += zahl;\n}",
    parts: [["if (zahl < 0)", "Erkennt hier den Wert, bei dem abgebrochen werden soll."], ["break", "Beendet die Schleife; spätere Elemente werden nicht mehr verarbeitet."], ["summe += zahl", "Wird nur erreicht, solange vorher kein Abbruch passiert ist."]],
    note: "break beendet nicht die gesamte Funktion. return würde die Funktion beenden und kann dabei einen Wert zurückgeben.",
    detail: "Bei verschachtelten Schleifen beendet ein einfaches break nur die innerste Schleife. break wird auch in switch verwendet. Hier ist wichtig, die Abbruchprüfung vor dem Addieren auszuführen, damit der negative Stopwert nicht in die Summe eingeht.",
    functionName: "summeBisStop", parameter: "zahlen",
    task: "Schreibe summeBisStop(zahlen). Addiere die Werte nur bis zur ersten negativen Zahl. Die negative Zahl und alle folgenden Werte zählen nicht mehr. Ohne negative Zahl addiere alles; bei leerem Array oder negativem ersten Wert ist das Ergebnis 0. Verändere die Eingabe nicht.",
    tests: [{input:[3,2,-1,9],expected:5},{input:[-1,8],expected:0},{input:[],expected:0},{input:[0,4,1],expected:5},{input:[2,0,-3,5],expected:2}],
    hints: ["Prüfe in jedem Durchlauf zuerst, ob zahl < 0 ist.", "Verwende in diesem Fall break. Addiere erst hinter dieser Prüfung und gib die Summe nach der Schleife zurück."],
    solution: "function summeBisStop(zahlen) {\n  let ergebnis = 0;\n  for (const zahl of zahlen) {\n    if (zahl < 0) {\n      break;\n    }\n    ergebnis += zahl;\n  }\n  return ergebnis;\n}",
    explanation: "Die erste negative Zahl beendet die Schleife, bevor sie addiert wird. Spätere positive Werte bleiben ebenfalls unberücksichtigt. return hinter der Schleife liefert die bis dahin gesammelte Summe.",
  }),
  lesson({
    id: "js-continue", name: "continue", title: "Einzelne Durchläufe mit continue überspringen",
    description: "continue überspringt den Rest des aktuellen Durchlaufs. Die Schleife prüft oder liest anschließend den nächsten Durchlauf.",
    syntax: "for (const zahl of zahlen) {\n  if (zahl <= 0) {\n    continue;\n  }\n  summe += zahl;\n}",
    parts: [["zahl <= 0", "Wählt hier die Werte aus, die übersprungen werden sollen."], ["continue", "Überspringt diesen Durchlauf, beendet aber nicht die gesamte Schleife."], ["summe += zahl", "Wird nur für positive Werte erreicht."]],
    note: "Bei for wird nach continue noch die Zähleraktualisierung ausgeführt. Bei while musst du selbst verhindern, dass continue eine nötige Zähleränderung überspringt und eine Endlosschleife erzeugt.",
    detail: "break stoppt alle weiteren Durchläufe; continue stoppt nur den aktuellen. Bei for…of wird nach continue der nächste Wert gelesen. Deshalb kann die Funktion hier auch positive Zahlen nach einem negativen Eintrag noch verarbeiten.",
    functionName: "positiveSumme", parameter: "zahlen",
    task: "Schreibe positiveSumme(zahlen). Addiere ausschließlich Zahlen größer als 0. Negative Zahlen und 0 sollen übersprungen werden, spätere positive Werte aber weiterhin zählen. Für ein leeres Array gib 0 zurück. Verändere die Eingabe nicht.",
    tests: [{input:[3,-2,4],expected:7},{input:[0,-5,0],expected:0},{input:[],expected:0},{input:[-2,10,-1,2],expected:12},{input:[5],expected:5}],
    hints: ["Beginne mit einer Summe von 0.", "Bei zahl <= 0 überspringst du mit continue den Durchlauf. Sonst addierst du zahl."],
    solution: "function positiveSumme(zahlen) {\n  let ergebnis = 0;\n  for (const zahl of zahlen) {\n    if (zahl <= 0) {\n      continue;\n    }\n    ergebnis += zahl;\n  }\n  return ergebnis;\n}",
    explanation: "continue verhindert das Addieren eines nicht positiven Werts, lässt aber die weiteren Durchläufe zu. So ergeben auch positive Einträge hinter negativen Zahlen einen Beitrag zur Summe. Bei einer leeren Liste bleibt das Ergebnis 0.",
  }),
];
