function lesson(data) {
  const exampleFiles = { ...data.solutionFiles, "main.js": data.solutionFiles["main.js"] + `\n\nconsole.log(${data.functionName}(${JSON.stringify(data.tests[0].input)}));` };
  return {
    course: "js", category: "Imports & Module", preserveInput: true,
    ...data, exampleFiles,
    example: exampleFiles["main.js"], starter: data.starterFiles["main.js"], solution: data.solutionFiles["main.js"],
  };
}

export const moduleLessons = [
  lesson({
    id: "js-module-named", name: "import { … }", title: "Benannte Exports zwischen Dateien verwenden",
    description: "export macht ausgewählte Werte eines Moduls zugänglich. Ein benannter Import liest sie unter dem passenden Exportnamen aus einer anderen Datei.",
    syntax: "// mathe.js\nexport function doppelt(zahl) { return zahl * 2; }\n// main.js\nimport { doppelt } from './mathe.js';",
    parts: [["export function", "Exportiert eine Funktion unter ihrem Namen."], ["import { doppelt }", "Benannter Import: Der Name muss im Zielmodul existieren."], ["'./mathe.js'", "Relativer Dateipfad mit Endung; ./ beginnt beim aktuellen Modul."], ["main.js", "Einstiegsdatei, deren exportierte Aufgabenfunktion geprüft wird."]],
    note: "Ein Modul hat seinen eigenen Gültigkeitsbereich. Eine Funktion aus mathe.js ist in main.js erst nach einem passenden Import verfügbar.",
    detail: "Die Datei-Reiter bilden ein kleines virtuelles Projekt. Der Spielplatz nutzt echte ES-Module, aber nur die mitgelieferten lokalen Dateien. Falsche Pfade und fehlende Exporte erzeugen Fehler. npm-Paketnamen und externe URLs sind hier nicht eingebunden.",
    functionName: "modulDoppelt",
    task: "Öffne mathe.js und korrigiere die exportierte Funktion doppelt: Sie soll den Zahlenwert verdoppeln. main.js importiert diese Funktion bereits und exportiert modulDoppelt. Geprüft werden beide Dateien gemeinsam.",
    tests: [{input:3,expected:6},{input:-2,expected:-4},{input:0,expected:0}],
    starterFiles: {"main.js":"import { doppelt } from './mathe.js';\n\nexport function modulDoppelt(zahl) {\n  return doppelt(zahl);\n}","mathe.js":"export function doppelt(zahl) {\n  return zahl;\n}"},
    solutionFiles: {"main.js":"import { doppelt } from './mathe.js';\n\nexport function modulDoppelt(zahl) {\n  return doppelt(zahl);\n}","mathe.js":"export function doppelt(zahl) {\n  return zahl * 2;\n}"},
    hints: ["Wechsle zum Reiter mathe.js. Die Rechnung findet dort statt.", "Lass export stehen und gib zahl * 2 zurück."],
    explanation: "mathe.js exportiert doppelt. Der benannte Import in main.js bindet diese Funktion, und modulDoppelt ruft sie auf. Eine Änderung im Hilfsmodul wirkt sich damit auf die gemeinsame Ausführung aus.",
  }),
  lesson({
    id: "js-module-default", name: "export default", title: "Standard-Exports ohne geschweifte Klammern importieren",
    description: "Ein Modul kann genau einen Standard-Export haben. Beim Standard-Import darfst du dessen lokalen Namen frei wählen.",
    syntax: "// gruss.js\nexport default function begruessen(name) { return `Hallo ${name}!`; }\n// main.js\nimport willkommen from './gruss.js';",
    parts: [["export default", "Bestimmt den Standard-Export des Moduls."], ["import willkommen", "Importiert ihn ohne geschweifte Klammern; willkommen ist ein frei gewählter lokaler Name."], ["{ … }", "Geschweifte Klammern stehen bei Imports für benannte Exporte, nicht für den Standard-Import."]],
    note: "Standard- und benannte Exports sind zwei unterschiedliche Exportarten. import { willkommen } würde einen benannten Export willkommen verlangen.",
    detail: "Ein Modul darf zusätzlich zu seinem Standard-Export mehrere benannte Exports besitzen. Ein kombinierter Import ist möglich, etwa import standard, { hilfe } from './datei.js'. Der Name des Standard-Imports muss nicht dem Funktionsnamen im Zielmodul entsprechen.",
    functionName: "modulGruss",
    task: "Korrigiere gruss.js so, dass der Standard-Export 'Hallo NAME!' zurückgibt. main.js importiert ihn unter dem lokalen Namen willkommen und exportiert modulGruss. Verändere den eingegebenen Namen nicht.",
    tests: [{input:"Mira",expected:"Hallo Mira!"},{input:"Ali Can",expected:"Hallo Ali Can!"},{input:"",expected:"Hallo !"}],
    starterFiles: {"main.js":"import willkommen from './gruss.js';\n\nexport function modulGruss(name) {\n  return willkommen(name);\n}","gruss.js":"export default function begruessen(name) {\n  return name;\n}"},
    solutionFiles: {"main.js":"import willkommen from './gruss.js';\n\nexport function modulGruss(name) {\n  return willkommen(name);\n}","gruss.js":"export default function begruessen(name) {\n  return `Hallo ${name}!`;\n}"},
    hints: ["Die Begrüßung wird im Reiter gruss.js erzeugt.", "Behalte export default und gib einen Template-String mit dem Namen zurück."],
    explanation: "gruss.js stellt seine Funktion als Standard-Export bereit. main.js wählt dafür den Namen willkommen. Der Aufruf verwendet trotzdem die exportierte Funktion aus gruss.js.",
  }),
  lesson({
    id: "js-module-alias", name: "import … as", title: "Einen benannten Import lokal umbenennen",
    description: "as gibt einem benannten Import einen anderen lokalen Namen. Der Exportname in der anderen Datei bleibt unverändert.",
    syntax: "import { berechnen as plusFuenf } from './rechnung.js';",
    parts: [["berechnen", "Der tatsächlich exportierte Name im Hilfsmodul."], ["as plusFuenf", "Legt den lokalen Namen in der importierenden Datei fest."], ["plusFuenf(wert)", "Verwendet nach dem Import den Alias."]],
    note: "Der Alias ist nur lokal. Die ursprüngliche Datei exportiert weiterhin berechnen.",
    detail: "Aliase helfen bei Namenskonflikten oder wenn ein klarerer Name den Zweck besser beschreibt. Export-Aliase sind ebenfalls möglich: export { intern as extern }. In diesem Schritt übst du das Umbenennen beim Import.",
    functionName: "mitAlias",
    task: "main.js ruft plusFuenf auf, importiert aber bisher nur berechnen. Korrigiere den Import mit einem Alias. rechnung.js ist bereits fertig und soll unverändert bleiben. mitAlias soll die Eingabe um 5 erhöhen.",
    tests: [{input:2,expected:7},{input:-5,expected:0},{input:0,expected:5}],
    starterFiles: {"main.js":"import { berechnen } from './rechnung.js';\n\nexport function mitAlias(wert) {\n  return plusFuenf(wert);\n}","rechnung.js":"export function berechnen(wert) {\n  return wert + 5;\n}"},
    solutionFiles: {"main.js":"import { berechnen as plusFuenf } from './rechnung.js';\n\nexport function mitAlias(wert) {\n  return plusFuenf(wert);\n}","rechnung.js":"export function berechnen(wert) {\n  return wert + 5;\n}"},
    hints: ["Bearbeite die import-Zeile in main.js.", "Schreibe innerhalb der Klammern berechnen as plusFuenf."],
    explanation: "Der Import findet den Export berechnen und bindet ihn lokal als plusFuenf. Dadurch ist der bereits vorhandene Funktionsaufruf gültig. Die Tests prüfen das Verhalten und verlangen keinen bestimmten Lösungsstil.",
  }),
  lesson({
    id: "js-module-reexport", name: "export … from", title: "Exporte über eine gemeinsame Datei weiterreichen",
    description: "Ein Re-Export reicht einen Export aus einer anderen Datei weiter. Eine zentrale Datei kann so mehrere Hilfsmodule zugänglich machen.",
    syntax: "// index.js\nexport { addieren } from './mathe.js';\n// main.js\nimport { addieren } from './index.js';",
    parts: [["export { addieren } from", "Reicht den benannten Export weiter, ohne eine eigene Implementierung zu kopieren."], ["index.js", "Gemeinsame Anlaufstelle für importierende Dateien."], ["mathe.js", "Enthält die tatsächliche Implementierung."], ["export * from", "Kann alle benannten Exporte weiterreichen; der Standard-Export wird dabei nicht automatisch mitgenommen."]],
    note: "Ein Re-Export allein legt keinen lokal nutzbaren Namen in index.js an. Für einen eigenen Aufruf dort wäre zusätzlich ein Import nötig.",
    detail: "Der Spielplatz unterstützt diese lokalen Importketten. Zyklische Imports und dynamisches import() gehören zu späteren Lernstufen. In eigenen Vite-/Node-Projekten kannst du npm-Pakete mit npm install installieren und über Paketnamen importieren; dieses virtuelle Projekt enthält solche Pakete nicht.",
    functionName: "modulSumme",
    task: "Ergänze in index.js den Re-Export von addieren aus mathe.js. main.js soll weiter aus index.js importieren. modulSumme(daten) soll daten.a und daten.b addieren. Die beiden anderen Dateien sind bereits fertig.",
    tests: [{input:{a:2,b:3},expected:5},{input:{a:-2,b:2},expected:0},{input:{a:0,b:7},expected:7}],
    starterFiles: {"main.js":"import { addieren } from './index.js';\n\nexport function modulSumme(daten) {\n  return addieren(daten.a, daten.b);\n}","index.js":"// Reiche addieren aus mathe.js hier weiter.\n","mathe.js":"export function addieren(a, b) {\n  return a + b;\n}"},
    solutionFiles: {"main.js":"import { addieren } from './index.js';\n\nexport function modulSumme(daten) {\n  return addieren(daten.a, daten.b);\n}","index.js":"export { addieren } from './mathe.js';","mathe.js":"export function addieren(a, b) {\n  return a + b;\n}"},
    hints: ["Öffne index.js. Der Export muss unter dem Namen addieren verfügbar sein.", "export { addieren } from './mathe.js';"],
    explanation: "main.js importiert über index.js. Der Re-Export verbindet index.js mit der Implementierung in mathe.js. Alle drei Module werden als gemeinsames Projekt geladen.",
  }),
];
