function lesson(data) {
  return {
    course: "js", category: "Rekursion", preserveInput: true, ...data,
    starter: `function ${data.functionName}(${data.parameter}) {\n  // Schreibe hier deine Lösung.\n}\n\nconsole.log(${data.functionName}(${JSON.stringify(data.tests[0].input)}));`,
    example: `${data.solution}\n\nconsole.log(${data.functionName}(${JSON.stringify(data.tests[0].input)}));`,
  };
}

export const recursionLessons = [
  lesson({
    id: "js-recursion-countdown", name: "Basisfall & Aufruf", title: "Mit Basisfall und kleinerem Problem rekursiv zählen",
    description: "Bei Rekursion ruft eine Funktion sich selbst auf. Ein Basisfall beendet die Aufrufe; jeder weitere Aufruf muss dem Basisfall näherkommen.",
    syntax: "if (n === 0) return [0];\nreturn [n, ...runterZaehlen(n - 1)];",
    parts: [["n === 0", "Der Basisfall, der keinen weiteren Funktionsaufruf benötigt."], ["runterZaehlen(n - 1)", "Ruft dieselbe Funktion mit einer kleineren Eingabe auf."], ["...", "Spread übernimmt die einzelnen Werte des zurückgegebenen Arrays."], ["return", "Gibt das zusammengesetzte Ergebnis an den vorherigen Aufruf zurück."]],
    note: "Jeder Aufruf hat seine eigene lokale Variable n. Rekursion ist ein Ablaufmuster mit gewöhnlichen Funktionsaufrufen, kein besonderer JavaScript-Operator.",
    detail: "Für n = 2 entstehen Aufrufe mit 2, 1 und 0. Der Basisfall liefert [0], der Aufruf mit 1 baut [1, 0], und der Aufruf mit 2 liefert [2, 1, 0]. Die Aufrufe liegen auf dem Aufrufstapel (Call Stack). Ohne erreichbaren Basisfall kann der Stack überlaufen. Für einfache Zählaufgaben ist auch eine Schleife sinnvoll; hier lernst du das rekursive Muster.",
    functionName: "runterZaehlen", parameter: "n",
    task: "Schreibe runterZaehlen(n). Gib ein Array mit allen ganzen Zahlen von n bis einschließlich 0 in absteigender Reihenfolge zurück. Die Eingabe ist eine ganze Zahl zwischen 0 und 20. Nutze zum Üben einen Basisfall bei 0 und einen Aufruf mit n - 1. Auch andere korrekte Lösungen werden akzeptiert.",
    tests: [{ input: 3, expected: [3, 2, 1, 0] }, { input: 0, expected: [0] }, { input: 1, expected: [1, 0] }, { input: 5, expected: [5, 4, 3, 2, 1, 0] }],
    hints: ["Bei n === 0 ist das vollständige Ergebnis [0].", "Stelle n vor das Ergebnis von runterZaehlen(n - 1): return [n, ...runterZaehlen(n - 1)]."],
    solution: "function runterZaehlen(n) {\n  if (n === 0) return [0];\n  return [n, ...runterZaehlen(n - 1)];\n}",
    explanation: "Jeder Aufruf verkleinert n um 1. Beim Basisfall wird kein weiterer Aufruf gestartet. Beim Zurückkehren ergänzt jede Ebene ihre eigene Zahl vor dem Ergebnis der nächsten Ebene.",
  }),
  lesson({
    id: "js-recursion-factorial", name: "Rückgabewerte", title: "Eine Fakultät aus rekursiven Rückgabewerten berechnen",
    description: "Die Fakultät n! multipliziert die Zahlen von 1 bis n. Die rekursive Regel lautet n! = n · (n - 1)!; der Basisfall 0! ist 1.",
    syntax: "if (n === 0) return 1;\nreturn n * fakultaet(n - 1);",
    parts: [["0! = 1", "Der mathematisch festgelegte Basisfall."], ["n - 1", "Verkleinert das Problem bei jedem Aufruf."], ["n * fakultaet(n - 1)", "Verwendet das zurückgegebene Ergebnis des kleineren Problems."], ["! in n!", "Mathematische Schreibweise; in JavaScript bedeutet ! logisches NICHT und berechnet keine Fakultät."]],
    note: "Der Basisfall muss 1 zurückgeben. Mit 0 würde jede Multiplikation am Ende 0 ergeben. Ein rekursiver Aufruf ohne return reicht ebenfalls nicht, um das berechnete Ergebnis zurückzugeben.",
    detail: "fakultaet(3) wartet auf fakultaet(2), dieser Aufruf auf fakultaet(1), und dieser auf fakultaet(0). Danach kehren die Werte 1, 1, 2 und 6 zurück. Die Eingaben sind klein: Number kann große ganze Zahlen nicht beliebig genau darstellen, und sehr tiefe Rekursion kann den Aufrufstapel überlaufen. BigInt und Alternativen kommen später.",
    functionName: "fakultaet", parameter: "n",
    task: "Schreibe fakultaet(n). Berechne n! für ganze Zahlen von 0 bis 10. Bei 0 gib 1 zurück. Nutze zum Üben die Regel n * fakultaet(n - 1) und gib das Ergebnis zurück. Negative oder nicht ganze Eingaben sind nicht Teil dieser Aufgabe.",
    tests: [{ input: 4, expected: 24 }, { input: 0, expected: 1 }, { input: 1, expected: 1 }, { input: 6, expected: 720 }, { input: 10, expected: 3628800 }],
    hints: ["Behandle zuerst n === 0 mit return 1.", "Für alle anderen erlaubten Eingaben: return n * fakultaet(n - 1)."],
    solution: "function fakultaet(n) {\n  if (n === 0) return 1;\n  return n * fakultaet(n - 1);\n}",
    explanation: "Der Basisfall liefert den Startwert für die Multiplikation. Beim Zurückkehren multipliziert jede Ebene ihr n mit dem schon berechneten Ergebnis. Deshalb braucht die rekursive Zeile ein return.",
  }),
  lesson({
    id: "js-recursion-list-length", name: "Knoten zählen", title: "Die Länge einer Liste rekursiv bestimmen",
    description: "Eine verkettete Liste ist ein Knoten mit einer restlichen Liste. Ihre Länge ist 1 plus die Länge des Rests; die leere Liste hat Länge 0.",
    syntax: "if (kopf === null) return 0;\nreturn 1 + listenLaenge(kopf.next);",
    parts: [["kopf === null", "Der Basisfall für eine leere Liste."], ["1", "Zählt den aktuellen vorhandenen Knoten."], ["kopf.next", "Der Kopf der kleineren, restlichen Liste."], ["1 + …", "Addiert den aktuellen Knoten zur rekursiv ermittelten Restlänge."]],
    note: "Prüfe die Knotenreferenz auf null, nicht den Knotenwert. Auch ein Knoten mit wert: null, 0, false oder '' zählt zur Länge.",
    detail: "Jeder Aufruf folgt einem next-Verweis. Bei der leeren Restliste endet die Rekursion und die Zähler werden beim Zurückkehren addiert. Die Liste bleibt unverändert. Die Eingabe ist eine kurze, gültige, endliche Kette ohne Zyklen. Für sehr lange Listen vermeidet eine Schleife die wachsende Zahl verschachtelter Funktionsaufrufe.",
    functionName: "listenLaenge", parameter: "kopf",
    task: "Schreibe listenLaenge(kopf). Gib die Anzahl aller Knoten der verketteten Liste zurück. Bei kopf === null ist die Länge 0. Jeder vorhandene Knoten zählt unabhängig von seinem Wert. Nutze zum Üben 1 + listenLaenge(kopf.next), ohne die Knoten zu verändern.",
    tests: [{ input: { wert: "A", next: { wert: "B", next: { wert: "C", next: null } } }, expected: 3 }, { input: null, expected: 0 }, { input: { wert: 7, next: null }, expected: 1 }, { input: { wert: null, next: { wert: 0, next: { wert: false, next: { wert: "", next: null } } } }, expected: 4 }],
    hints: ["Die leere Liste hat Länge 0. Prüfe das vor dem Zugriff auf next.", "Bei einem vorhandenen Knoten gib 1 plus die Länge der Liste ab kopf.next zurück."],
    solution: "function listenLaenge(kopf) {\n  if (kopf === null) return 0;\n  return 1 + listenLaenge(kopf.next);\n}",
    explanation: "Die Funktion zerlegt die Liste in einen aktuellen Knoten und den Rest. Der Basisfall liefert 0, und jeder vorhandene Knoten ergänzt 1. Die Nutzdaten haben keinen Einfluss auf die Anzahl.",
  }),
  lesson({
    id: "js-recursion-nested-sum", name: "Verschachtelte Daten", title: "Zahlen in verschachtelten Arrays rekursiv summieren",
    description: "Bei verschachtelten Daten kann ein Element wieder eine Sammlung enthalten. Rekursion verarbeitet jede Ebene nach derselben Regel, ohne die Tiefe vorher kennen zu müssen.",
    syntax: "if (!Array.isArray(daten)) return daten;\nlet summe = 0;\nfor (const teil of daten) summe += verschachteltSummieren(teil);\nreturn summe;",
    parts: [["Array.isArray(daten)", "Erkennt Arrays zuverlässig; typeof liefert für Arrays lediglich 'object'."], ["Zahl als Basisfall", "Eine einzelne Zahl liefert direkt ihren eigenen Wert zurück."], ["for…of", "Durchläuft die direkten Elemente der aktuellen Arrayebene."], ["rekursiver Aufruf pro Element", "Verarbeitet Zahlen oder weitere Arrays nach derselben Regel."], ["summe += …", "Addiert die Ergebnisse aller Teilprobleme."]],
    note: "Die Aufgabe enthält ausschließlich Zahlen und Arrays daraus. Leere Arrays ergeben 0; negative Zahlen und 0 sind gültig. Diese erste Variante prüft keine anderen Datentypen.",
    detail: "Für [1, [2, [3]], 4] werden die Unterarrays getrennt verarbeitet und ihre Summen addiert. Eine einzelne Zahl beendet einen Zweig; ein leeres Array endet ohne weitere Aufrufe. Genau dieses Aufteilen in Teilstrukturen hilft später beim Durchlaufen von Bäumen. Die Beispiele sind klein und zyklusfrei; sehr große Tiefen können den Call Stack überfordern.",
    functionName: "verschachteltSummieren", parameter: "daten",
    task: "Schreibe verschachteltSummieren(daten). daten ist eine Zahl oder ein Array mit Zahlen und weiteren solchen Arrays. Gib die Summe aller enthaltenen Zahlen zurück, unabhängig von der Verschachtelung. Eine Zahl allein ergibt diese Zahl, ein leeres Array 0. Verändere kein Array. Nutze zum Üben Array.isArray und rekursive Aufrufe.",
    tests: [{ input: [1, [2, [3]], 4], expected: 10 }, { input: [], expected: 0 }, { input: 0, expected: 0 }, { input: [[], [-2, [0, 5]], 1], expected: 4 }, { input: [1, [-1, [2]], -2], expected: 0 }, { input: -7, expected: -7 }, { input: [[0], [], [[-1], 2]], expected: 1 }],
    hints: ["Wenn daten kein Array ist, ist es laut Aufgabenvertrag eine Zahl. Gib sie direkt zurück.", "Bei einem Array beginne mit summe = 0. Addiere für jedes Element verschachteltSummieren(teil) und gib die Summe zurück."],
    solution: "function verschachteltSummieren(daten) {\n  if (!Array.isArray(daten)) return daten;\n  let summe = 0;\n  for (const teil of daten) {\n    summe += verschachteltSummieren(teil);\n  }\n  return summe;\n}",
    explanation: "Zahlen bilden den Basisfall. Arrays werden in Teilprobleme zerlegt, deren Ergebnisse zusammengezählt werden. Eine eigene lokale summe pro Aufruf verhindert, dass unterschiedliche Ebenen versehentlich denselben Zähler verwenden.",
  }),
];
