function lesson(data) {
  return {
    course: "js", category: "Sortieren & Suchen", preserveInput: true, ...data,
    starter: `function ${data.functionName}(${data.parameter}) {\n  // Schreibe hier deine Lösung.\n}\n\nconsole.log(${data.functionName}(${JSON.stringify(data.tests[0].input)}));`,
    example: `${data.solution}\n\nconsole.log(${data.functionName}(${JSON.stringify(data.tests[0].input)}));`,
  };
}

export const sortingLessons = [
  lesson({
    id: "js-sort-numbers", name: ".sort() mit Zahlen", title: "Zahlen numerisch sortieren, ohne die Eingabe zu verändern",
    description: "Ohne Vergleichsfunktion sortiert JavaScript Werte als Text. Für eine Zahlenliste brauchst du einen numerischen Vergleich und eine Kopie, wenn die Originalreihenfolge erhalten bleiben soll.",
    syntax: "const zahlen = [10, 2, 1];\nconst textSortiert = [...zahlen].sort(); // [1, 10, 2]\nconst numerisch = [...zahlen].sort((a, b) => a - b); // [1, 2, 10]",
    parts: [["[...zahlen]", "Kopiert das Array. sort verändert danach nur diese Kopie."], [".sort(vergleichen)", "Ordnet das Array anhand der Rückgabewerte deiner Vergleichsfunktion."], ["(a, b) => a - b", "Negativ: a vor b. Positiv: a nach b. Null: beide gleich eingeordnet."], ["b - a", "Kehrt die numerische Ordnung um: große Zahlen zuerst."]],
    note: "Eine Vergleichsfunktion muss einen negativen Wert, null oder einen positiven Wert liefern. a > b liefert nur true oder false und ist kein vollständiger Sortiervergleich.",
    detail: "Die Eingabe enthält ausschließlich endliche Zahlen, einschließlich negativer Werte, Dezimalzahlen und Duplikaten. Die Lösung kopiert nur das Array; für primitive Zahlen reicht das. sort gibt dasselbe Array zurück, das es verändert. Moderne JavaScript-Engines sortieren stabil: Bei Vergleichswert 0 bleibt die relative Reihenfolge erhalten. Die genaue Laufzeit von sort hängt von der Engine ab.",
    functionName: "zahlenSortieren", parameter: "zahlen",
    task: "Schreibe zahlenSortieren(zahlen). Gib eine aufsteigend numerisch sortierte Kopie zurück. Behalte doppelte Zahlen. Verändere das Eingabearray nicht.",
    tests: [{input:[10,2,1],expected:[1,2,10]},{input:[-3,0,-12,-1,4],expected:[-12,-3,-1,0,4]},{input:[2.5,2.05,2],expected:[2,2.05,2.5]},{input:[3,1,3,1],expected:[1,1,3,3]},{input:[],expected:[]},{input:[0],expected:[0]}],
    hints: ["Erzeuge zuerst mit Spread eine neue Liste.", "Rufe sort mit (a, b) => a - b auf und gib die sortierte Kopie zurück."],
    solution: "function zahlenSortieren(zahlen) {\n  return [...zahlen].sort((a, b) => a - b);\n}",
    explanation: "Bei a = 10 und b = 2 ergibt a - b den positiven Wert 8: 10 soll hinter 2 stehen. Bei a = 1 und b = 2 ist das Ergebnis -1: 1 kommt davor. Die Kopie schützt die Eingabe vor der Mutation durch sort.",
  }),
  lesson({
    id: "js-sort-ranking", name: "Objekte sortieren", title: "Eine Bestenliste mit mehreren Sortierregeln ordnen",
    description: "Eine Spiele-Bestenliste sortiert zuerst nach Punkten. Bei Gleichstand entscheidet der Name. Die Vergleichsfunktion kann mehrere Regeln miteinander verbinden.",
    syntax: "const unterschied = b.punkte - a.punkte;\nif (unterschied !== 0) return unterschied;\nif (a.name < b.name) return -1;\nif (a.name > b.name) return 1;\nreturn 0;",
    parts: [["b.punkte - a.punkte", "Sortiert absteigend: größere Punktzahlen zuerst."], ["if (unterschied !== 0)", "Verwendet die Namensregel nur bei gleicher Punktzahl."], ["a.name < b.name", "Vergleicht hier Namen nach JavaScripts Stringordnung."], ["return 0", "Beide Regeln ergeben Gleichstand; die ursprüngliche Reihenfolge bleibt erhalten."]],
    note: "Für menschliche Namen mit Umlauten kann localeCompare sinnvoll sein. In dieser Aufgabe verwenden wir bewusst die feste JavaScript-Stringordnung und einfache ASCII-Namen, damit das Ergebnis unabhängig von der Systemsprache ist.",
    detail: "Jeder Eintrag enthält name (ASCII-String), punkte (endliche Zahl) und id (String). Sortiere absteigend nach Punkten, bei Gleichstand aufsteigend nach Name. Bei gleicher Punktzahl und gleichem Namen bleibt die ursprüngliche Reihenfolge erhalten. Die id hilft, solche Gleichstände in den Tests zu unterscheiden; sie ist keine Sortierregel. Spread kopiert das äußere Array, teilt aber die Objektreferenzen. Da die Lösung keine Objekte verändert, genügt das hier.",
    functionName: "bestenliste", parameter: "spieler",
    task: "Schreibe bestenliste(spieler). Gib eine neue Liste nach Punkten absteigend und bei Gleichstand nach Name aufsteigend zurück. Erhalte die Eingabereihenfolge bei Gleichstand beider Regeln. Verändere weder die Liste noch ihre Objekte.",
    tests: [
      {input:[{id:"a",name:"Ada",punkte:10},{id:"b",name:"Ben",punkte:40},{id:"c",name:"Cara",punkte:20}],expected:[{id:"b",name:"Ben",punkte:40},{id:"c",name:"Cara",punkte:20},{id:"a",name:"Ada",punkte:10}]},
      {input:[{id:"b",name:"Ben",punkte:5},{id:"a",name:"Ada",punkte:5}],expected:[{id:"a",name:"Ada",punkte:5},{id:"b",name:"Ben",punkte:5}]},
      {input:[{id:"z",name:"Ada",punkte:5},{id:"a",name:"Ada",punkte:5}],expected:[{id:"z",name:"Ada",punkte:5},{id:"a",name:"Ada",punkte:5}]},
      {input:[{id:"a",name:"Ada",punkte:-2},{id:"b",name:"Ben",punkte:0}],expected:[{id:"b",name:"Ben",punkte:0},{id:"a",name:"Ada",punkte:-2}]},
      {input:[],expected:[]},
    ],
    hints: ["Kopiere das Array und beginne die Vergleichsfunktion mit b.punkte - a.punkte.", "Bei gleichem Punktestand vergleiche die Namen. Gib -1, 1 oder 0 zurück; ändere keine Eigenschaften."],
    solution: "function bestenliste(spieler) {\n  return [...spieler].sort((a, b) => {\n    const unterschied = b.punkte - a.punkte;\n    if (unterschied !== 0) return unterschied;\n    if (a.name < b.name) return -1;\n    if (a.name > b.name) return 1;\n    return 0;\n  });\n}",
    explanation: "Die Punkteregel entscheidet zuerst. Nur wenn sie 0 ergibt, folgt der Namensvergleich. Ergibt auch dieser 0, erhält die stabile Sortierung die Eingabereihenfolge. Für eine sichtbare Bestenliste könntest du danach map verwenden, um Rangnummern und Namen auszugeben.",
  }),
  lesson({
    id: "js-find-index", name: ".findIndex()", title: "Die erste passende Position mit findIndex finden",
    description: "findIndex sucht von links nach rechts und liefert den Index des ersten Treffers. Das funktioniert auch in unsortierten Arrays.",
    syntax: "const index = zahlen.findIndex(wert => wert === gesucht);\n// [7, 2, 7], gesucht = 7 → 0\n// Kein Treffer → -1",
    parts: [["wert => wert === gesucht", "Ein Prädikat: Die Funktion entscheidet für jedes Element, ob es passt."], [".findIndex()", "Beendet die Suche beim ersten passenden Element und gibt dessen Index zurück."], ["Index 0", "Das erste Element steht an Position 0. Dieser gültige Treffer ist falsy."], ["-1", "Bedeutet kein Treffer. -1 ist truthy: Ein einfacher if(index)-Test ist ungeeignet."]],
    note: "Prüfe index !== -1, wenn du wissen willst, ob etwas gefunden wurde. find liefert dagegen das Element selbst, nicht seine Position.",
    detail: "Die Eingabe ist {zahlen, gesucht} mit einem dichten Array endlicher Zahlen. Die Liste muss nicht sortiert sein; gleiche Werte dürfen mehrfach vorkommen. findIndex läuft schlimmstenfalls durch alle n Elemente: O(n). Die Vergleichsfunktion verändert die Eingabe nicht.",
    functionName: "erstePosition", parameter: "daten",
    task: "Schreibe erstePosition(daten) für {zahlen, gesucht}. Gib den Index des ersten strikt gleichen Zahlenwerts zurück, sonst -1. Verändere die Liste nicht.",
    tests: [{input:{zahlen:[7,2,7],gesucht:7},expected:0},{input:{zahlen:[9,1,4],gesucht:4},expected:2},{input:{zahlen:[0,-2,3],gesucht:0},expected:0},{input:{zahlen:[1,2],gesucht:3},expected:-1},{input:{zahlen:[],gesucht:1},expected:-1},{input:{zahlen:[5,8,5],gesucht:8},expected:1}],
    hints: ["Lies zahlen und gesucht aus daten.", "Gib zahlen.findIndex(wert => wert === gesucht) zurück. Wandle 0 oder -1 nicht mit || in einen anderen Wert um."],
    solution: "function erstePosition(daten) {\n  return daten.zahlen.findIndex(wert => wert === daten.gesucht);\n}",
    explanation: "Der Callback gibt einen Boolean zurück, weil findIndex eine Trefferaussage erwartet. Anders als sort benötigt diese Methode keinen negativen oder positiven Vergleichswert. Der erste passende Index wird direkt zurückgegeben, einschließlich 0; ohne Treffer liefert die Methode -1.",
  }),
  lesson({
    id: "js-binary-search", name: "Binäre Suche", title: "In einer sortierten Liste den ersten Treffer binär suchen",
    description: "Ist eine Liste bereits numerisch aufsteigend sortiert, kannst du den Suchbereich nach jedem Vergleich ungefähr halbieren. Bei doppelten Werten suchen wir die erste Position.",
    syntax: "const mitte = Math.floor((links + rechts) / 2);\nif (zahlen[mitte] < gesucht) links = mitte + 1;\nelse rechts = mitte - 1;",
    parts: [["links / rechts", "Begrenzen den noch möglichen Suchbereich einschließlich beider Enden."], ["Math.floor()", "Rundet nach unten und erzeugt einen ganzzahligen Arrayindex."], ["mitte + 1 / mitte - 1", "Schließt die gerade geprüfte Position aus. Der Suchbereich wird wirklich kleiner."], ["treffer = mitte", "Merkt einen gefundenen Index, während die Suche links nach früheren gleichen Werten weitergeht."]],
    note: "Binäre Suche setzt die passende Sortierung voraus. Sortiere die Eingabe hier nicht selbst: Das würde ursprüngliche Positionen verändern und kostet zusätzliche Zeit.",
    detail: "zahlen ist garantiert numerisch aufsteigend sortiert und enthält nur endliche Zahlen. gleiche Zahlen dürfen mehrfach vorkommen. Gesucht ist der erste Index, nicht irgendein Treffer. Die gezeigte Schleife benötigt O(log n) Vergleiche und O(1) zusätzlichen Speicher. Die automatische Prüfung bewertet Ergebnis und unveränderte Eingaben; eine lineare Lösung kann ebenfalls bestehen, übe hier aber bewusst das Halbieren des Suchbereichs.",
    functionName: "binaerSuchen", parameter: "daten",
    task: "Schreibe binaerSuchen(daten) für {zahlen, gesucht}. Finde mit binärer Suche den ersten Index von gesucht in der bereits aufsteigend sortierten Liste. Gib -1 zurück, wenn der Wert fehlt. Verändere die Eingabe nicht.",
    tests: [{input:{zahlen:[1,3,5,7,9],gesucht:7},expected:3},{input:{zahlen:[1,2,2,2,5],gesucht:2},expected:1},{input:{zahlen:[0,0,0,1],gesucht:0},expected:0},{input:{zahlen:[-8,-3,0,4],gesucht:-8},expected:0},{input:{zahlen:[1,3,5],gesucht:5},expected:2},{input:{zahlen:[1,3,5],gesucht:4},expected:-1},{input:{zahlen:[],gesucht:1},expected:-1},{input:{zahlen:[2],gesucht:2},expected:0},{input:{zahlen:[2],gesucht:1},expected:-1},{input:{zahlen:[1,2],gesucht:2},expected:1}],
    hints: ["Starte mit links = 0, rechts = zahlen.length - 1 und treffer = -1. Suche solange links <= rechts.", "Ist der Mittelwert zu klein, suche rechts davon. Sonst suche links davon weiter und merke bei Gleichheit die aktuelle Position. Gib nach der Schleife treffer zurück."],
    solution: "function binaerSuchen(daten) {\n  const { zahlen, gesucht } = daten;\n  let links = 0;\n  let rechts = zahlen.length - 1;\n  let treffer = -1;\n  while (links <= rechts) {\n    const mitte = Math.floor((links + rechts) / 2);\n    if (zahlen[mitte] < gesucht) {\n      links = mitte + 1;\n    } else {\n      if (zahlen[mitte] === gesucht) treffer = mitte;\n      rechts = mitte - 1;\n    }\n  }\n  return treffer;\n}",
    explanation: "Bei [1,2,2,2,5] ist die erste Mitte Index 2. Sie trifft, aber Index 1 könnte ebenfalls passen. Deshalb merken wir 2 und suchen links weiter. Dort finden wir 1 und speichern ihn. Sobald links > rechts ist, bleibt der früheste gefundene Index. Bei einer leeren Liste startet rechts mit -1 und die Schleife wird übersprungen.",
  }),
];
