function lesson(data) {
  return {
    course: "js", category: "Datenstrukturen", preserveInput: true, ...data,
    starter: `function ${data.functionName}(${data.parameter}) {\n  // Schreibe hier deine Lösung.\n}\n\nconsole.log(${data.functionName}(${JSON.stringify(data.tests[0].input)}));`,
    example: `${data.solution}\n\nconsole.log(${data.functionName}(${JSON.stringify(data.tests[0].input)}));`,
  };
}

export const structureLessons = [
  lesson({
    id: "js-object-keys", category: "Objekte", name: "Object.keys()", title: "Eigenschaftsnamen mit Object.keys lesen",
    description: "Object.keys(objekt) gibt ein Array der eigenen, aufzählbaren Eigenschaftsnamen zurück. Die Namen sind Strings.",
    syntax: "const namen = Object.keys(person);\nconst sortiert = namen.sort();",
    parts: [["Object.keys(objekt)", "Erzeugt ein neues Array mit den Eigenschaftsnamen, nicht ihren Werten."], [".sort()", "Sortiert ohne Vergleichsfunktion lexikografisch als Text."], ["Eigenschaft", "Ein benannter Bestandteil des Objekts, etwa name oder alter."]],
    note: "sort verändert das Array, auf dem du es aufrufst. Hier sortierst du das neue keys-Array, nicht das Eingabeobjekt.",
    detail: "Object.keys({name: 'Mira', alter: 20}) ergibt ['name', 'alter']. Object.values liefert dagegen die Werte. Symbol-Schlüssel und geerbte Eigenschaften stehen nicht in Object.keys. Zahlartige Schlüssel werden als Strings ausgegeben; Textsortierung ist nicht dasselbe wie numerische Sortierung.",
    functionName: "eigenschaften", parameter: "objekt",
    task: "Schreibe eigenschaften(objekt). Gib ein lexikografisch sortiertes Array aller eigenen aufzählbaren Eigenschaftsnamen zurück. Verändere das Objekt nicht. Die Tests verwenden einfache JSON-Objekte.",
    tests: [{input:{name:"Mira",alter:20},expected:["alter","name"]},{input:{z:1,a:2,m:3},expected:["a","m","z"]},{input:{},expected:[]},{input:{"2":"b","10":"a"},expected:["10","2"]}],
    hints: ["Lies die Namen mit Object.keys(objekt).", "Sortiere dieses neue Array mit .sort() und gib es zurück."],
    solution: "function eigenschaften(objekt) {\n  return Object.keys(objekt).sort();\n}",
    explanation: "keys liefert ein neues Array mit String-Schlüsseln. sort ordnet sie als Text: '10' steht dabei vor '2'. Nur dieses neue Array wird verändert; das Eingabeobjekt bleibt erhalten.",
  }),
  lesson({
    id: "js-object-entries", category: "Objekte", name: "Object.entries()", title: "Schlüssel und Werte gemeinsam durchlaufen",
    description: "Object.entries(objekt) erzeugt ein Array von Paaren: Jeder Eintrag enthält einen Eigenschaftsnamen und seinen Wert.",
    syntax: "for (const [name, punkte] of Object.entries(team)) {\n  zeilen.push(`${name}: ${punkte}`);\n}",
    parts: [["Object.entries(team)", "Liefert Paare wie ['Mira', 8]."], ["[name, punkte]", "Array-Destrukturierung: verteilt beide Paarwerte auf zwei Variablen."], ["for…of", "Durchläuft die Paare nacheinander."], [".push()", "Hängt die formatierte Zeile an das Ergebnisarray an."]],
    note: "Object.entries liest eigene, aufzählbare String-Eigenschaften. Die Werte werden nicht automatisch tief kopiert.",
    detail: "Bei einer festen Struktur wie einem Profil sind Objekte praktisch. entries eignet sich zum Auflisten oder Zusammenfassen ihrer Inhalte. Zahlenartige Eigenschaftsnamen haben besondere Reihenfolgeregeln; die Aufgabe verlangt deshalb eine ausdrückliche Textsortierung der erzeugten Zeilen.",
    functionName: "punkteZeilen", parameter: "team",
    task: "Schreibe punkteZeilen(team). Das Objekt ordnet Namen Zahlenwerte zu. Erzeuge für jede Eigenschaft den String 'NAME: PUNKTE'. Gib die Zeilen lexikografisch sortiert zurück. Verändere team nicht.",
    tests: [{input:{Mira:8,Ali:5},expected:["Ali: 5","Mira: 8"]},{input:{Jo:0,Lea:-2},expected:["Jo: 0","Lea: -2"]},{input:{},expected:[]},{input:{Mira:12},expected:["Mira: 12"]}],
    hints: ["Durchlaufe Object.entries(team) mit for…of und lies jedes Paar mit [name, punkte].", "Sammle `${name}: ${punkte}` in einem neuen Array und sortiere dieses zum Schluss."],
    solution: "function punkteZeilen(team) {\n  const zeilen = [];\n  for (const [name, punkte] of Object.entries(team)) {\n    zeilen.push(`${name}: ${punkte}`);\n  }\n  return zeilen.sort();\n}",
    explanation: "entries macht jedes Schlüssel-Wert-Paar zugänglich. Destrukturierung benennt die beiden Bestandteile. Die Ausgabe wird unabhängig von der ursprünglichen Eigenschaftsreihenfolge sortiert.",
  }),
  lesson({
    id: "js-map-count", name: "Map: set & get", title: "Häufigkeiten mit Map zählen",
    description: "Eine Map speichert Schlüssel-Wert-Zuordnungen. set setzt einen Wert, get liest ihn. Die Reihenfolge richtet sich nach dem ersten Einfügen eines Schlüssels.",
    syntax: "const anzahl = new Map();\nanzahl.set(wort, (anzahl.get(wort) ?? 0) + 1);",
    parts: [["new Map()", "Erzeugt eine leere Schlüssel-Wert-Sammlung."], [".get(wort)", "Liest den bisherigen Wert; bei fehlendem Schlüssel ergibt sich undefined."], [".set(wort, wert)", "Setzt oder ersetzt den Wert und gibt die Map selbst zurück."], ["?? 0", "Verwendet beim ersten Vorkommen den Startwert 0."], ["[...anzahl.entries()]", "Wandelt die Paare für die Ausgabe in ein normales Array um."]],
    note: "Map ist eine Datenstruktur. Die Array-Methode .map() erzeugt dagegen durch Umwandlung ein neues Array; sie erstellt keine Map-Sammlung.",
    detail: "Maps eignen sich für dynamische Zuordnungen und können auch Zahlen oder Objekte als Schlüssel verwenden. .size liefert die Anzahl unterschiedlicher Schlüssel. Ein erneutes set für einen bestehenden Schlüssel ersetzt dessen Wert, ohne seine Einfügereihenfolge zu ändern.",
    functionName: "woerterZaehlen", parameter: "woerter",
    task: "Schreibe woerterZaehlen(woerter). Zähle jeden String genau nach seiner Schreibweise. Gib ein Array von [wort, anzahl]-Paaren in der Reihenfolge des ersten Vorkommens zurück. Verändere die Liste nicht.",
    tests: [{input:["Apfel","Birne","Apfel"],expected:[["Apfel",2],["Birne",1]]},{input:[],expected:[]},{input:["a","A","a"],expected:[["a",2],["A",1]]},{input:["x","x","x"],expected:[["x",3]]}],
    hints: ["Lege eine neue Map an und erhöhe für jedes Wort den bisherigen Zähler.", "Nutze get mit ?? 0, dann set. Gib [...anzahl.entries()] zurück."],
    solution: "function woerterZaehlen(woerter) {\n  const anzahl = new Map();\n  for (const wort of woerter) {\n    anzahl.set(wort, (anzahl.get(wort) ?? 0) + 1);\n  }\n  return [...anzahl.entries()];\n}",
    explanation: "Beim ersten Wort liefert get undefined; ?? setzt den Zähler auf 0. Jedes Vorkommen erhöht ihn um 1. entries liefert die Paare in Einfügereihenfolge, Spread sammelt sie in einem Array.",
  }),
  lesson({
    id: "js-map-has", name: "Map.has()", title: "Vorhandene Map-Schlüssel gezielt prüfen",
    description: "Map.has(schluessel) prüft, ob ein Schlüssel vorhanden ist. Das ist unabhängig davon, ob der zugehörige Wert 0, false, null oder undefined ist.",
    syntax: "const zuordnung = new Map(daten.paare);\nif (zuordnung.has(daten.schluessel)) {\n  return zuordnung.get(daten.schluessel);\n}",
    parts: [["new Map(paare)", "Erzeugt eine Map aus [schlüssel, wert]-Paaren."], [".has(schluessel)", "Liefert true bei vorhandenem Schlüssel, sonst false."], [".get(schluessel)", "Liest den gespeicherten Wert."], ["Schlüsseltyp", "Die Zahl 1 und der String '1' sind unterschiedliche Map-Schlüssel."]],
    note: "if (map.get(key)) kann vorhandene Werte wie 0 oder false fälschlich als fehlend behandeln. Prüfe das Vorhandensein mit has.",
    detail: "Bei einem mehrfach vorkommenden Schlüssel bleibt der zuletzt gesetzte Wert erhalten. Objekt-Schlüssel werden nach ihrer Identität unterschieden, nicht nach gleichem Inhalt. .delete(key) entfernt einen Schlüssel; .clear() leert die gesamte Map.",
    functionName: "zuordnungLesen", parameter: "daten",
    task: "Schreibe zuordnungLesen(daten). Erzeuge aus daten.paare eine Map und suche daten.schluessel. Gib {gefunden: true, wert: GESPEICHERTER_WERT} zurück, wenn der Schlüssel vorhanden ist. Sonst gib {gefunden: false, wert: 'Fehlt'} zurück. Erhalte insbesondere 0, false und null.",
    tests: [{input:{paare:[["preis",0]],schluessel:"preis"},expected:{gefunden:true,wert:0}},{input:{paare:[["aktiv",false]],schluessel:"aktiv"},expected:{gefunden:true,wert:false}},{input:{paare:[["leer",null]],schluessel:"leer"},expected:{gefunden:true,wert:null}},{input:{paare:[],schluessel:"name"},expected:{gefunden:false,wert:"Fehlt"}},{input:{paare:[[1,"Zahl"],["1","Text"]],schluessel:1},expected:{gefunden:true,wert:"Zahl"}},{input:{paare:[["x",1],["x",2]],schluessel:"x"},expected:{gefunden:true,wert:2}}],
    hints: ["new Map(daten.paare) liest die Paare ein.", "Verzweige anhand von has, nicht anhand des Wahrheitswerts von get."],
    solution: "function zuordnungLesen(daten) {\n  const zuordnung = new Map(daten.paare);\n  if (zuordnung.has(daten.schluessel)) {\n    return { gefunden: true, wert: zuordnung.get(daten.schluessel) };\n  }\n  return { gefunden: false, wert: 'Fehlt' };\n}",
    explanation: "has trennt Vorhandensein von Wertinhalt. Dadurch bleiben 0, false und null als gültige Werte erhalten. Unterschiedliche Schlüsseltypen werden getrennt gespeichert; doppelte Schlüssel verwenden den letzten Wert.",
  }),
  lesson({
    id: "js-set-unique", name: "Set", title: "Doppelte Werte mit Set entfernen",
    description: "Ein Set speichert jeden unterschiedlichen Wert höchstens einmal. Bei der Ausgabe bleibt die Reihenfolge des ersten Einfügens erhalten.",
    syntax: "const eindeutig = new Set(werte);\nreturn [...eindeutig];",
    parts: [["new Set(werte)", "Liest die Werte ein und entfernt Duplikate."], [".add(wert)", "Fügt einen Wert hinzu und gibt das Set zurück."], [".has(wert)", "Prüft, ob ein Wert im Set enthalten ist."], [".size", "Anzahl unterschiedlicher Werte; kein length."], ["[...eindeutig]", "Erzeugt ein Array aus den Set-Werten."]],
    note: "Die Zahl 1 und der String '1' bleiben unterschiedliche Werte. Verschiedene Objekte mit gleichem Inhalt werden ebenfalls nicht automatisch zusammengefasst.",
    detail: "Set eignet sich für eindeutige Werte und Mitgliedschaftsprüfungen; es speichert keine eigenen Schlüssel-Wert-Paare wie Map. .delete(wert) entfernt einen Wert, .clear() leert das Set. Bei der Vergleichsregel SameValueZero gelten auch NaN-Werte untereinander als gleich sowie 0 und -0.",
    functionName: "eindeutigeWerte", parameter: "werte",
    task: "Schreibe eindeutigeWerte(werte). Gib ein neues Array ohne doppelte Werte zurück. Behalte die Reihenfolge des ersten Vorkommens und die Werttypen bei. Die Tests verwenden nur primitive JSON-Werte. Verändere das Eingabe-Array nicht.",
    tests: [{input:[3,1,3,2,1],expected:[3,1,2]},{input:[],expected:[]},{input:[1,"1",1,false,false],expected:[1,"1",false]},{input:[null,null,0,0,""],expected:[null,0,""]}],
    hints: ["Erzeuge ein Set aus der Eingabeliste.", "Wandle das Set mit Spread zurück in ein Array, ohne zusätzlich zu sortieren oder die Werte in Strings umzuwandeln."],
    solution: "function eindeutigeWerte(werte) {\n  return [...new Set(werte)];\n}",
    explanation: "Das Set übernimmt nur das erste Vorkommen jedes Werts. Spread erzeugt daraus ein neues Array. Die Werte behalten ihre Typen und ihre erste Einfügereihenfolge.",
  }),
];
