function lesson(data) {
  return {
    course: "js", category: "Bäume", preserveInput: true, ...data,
    starter: `function ${data.functionName}(${data.parameter}) {\n  // Schreibe hier deine Lösung.\n}\n\nconsole.log(${data.functionName}(${JSON.stringify(data.tests[0].input)}));`,
    example: `${data.solution}\n\nconsole.log(${data.functionName}(${JSON.stringify(data.tests[0].input)}));`,
  };
}
const node = (wert, links = null, rechts = null) => ({ wert, links, rechts });
const inputs = () => [
  node("A", node("B"), node("C")),
  null,
  node(0),
  node(1, null, node(2, null, node(3))),
  node(0, node(false), node(null)),
  node(5, node(8, node(3)), node(1, null, node(2))),
  node("A", node("A"), node("B")),
];
const cases = (expected) => inputs().map((input, i) => ({ input, expected: expected[i] }));

export const treeLessons = [
  lesson({
    id: "js-tree-count", name: "Knoten zählen", title: "Binärbäume verstehen und ihre Knoten zählen",
    description: "Ein Binärbaum besteht aus Knoten mit höchstens zwei Kindern. Jeder Teilbaum hat dieselbe Struktur wie der gesamte Baum und kann rekursiv verarbeitet werden.",
    syntax: "const baum = {\n  wert: 'A',\n  links: { wert: 'B', links: null, rechts: null },\n  rechts: { wert: 'C', links: null, rechts: null }\n};\n// A\n// ├─ links: B\n// └─ rechts: C",
    parts: [["Wurzel", "Der oberste Knoten, von dem aus du den Baum erreichst."], ["links und rechts", "Referenzen auf die beiden Teilbäume; null bedeutet, dass ein Kind fehlt."], ["Blatt", "Ein Knoten ohne Kinder: links und rechts sind null."], ["1 + links + rechts", "Zählt die Wurzel und die Knoten beider Teilbäume."], ["baum === null", "Der leere Baum ist der Basisfall und enthält 0 Knoten."]],
    note: "links und rechts sind gewählte Objekteigenschaften, keine eingebauten JavaScript-Methoden. Ein Binärbaum ist nicht automatisch ein binärer Suchbaum; die Werte sind hier nicht nach Größe geordnet.",
    detail: "Ein Knoten darf kein, ein oder zwei Kinder besitzen. Ein Baum hat in dieser Aufgabe weder Zyklen noch gemeinsam genutzte Kindknoten: Jeder vorhandene Knoten wird genau einmal erreicht. wert kann auch 0, false oder null sein. Nur die Baumreferenz null bedeutet, dass kein Knoten vorhanden ist.",
    functionName: "baumKnoten", parameter: "baum",
    task: "Schreibe baumKnoten(baum). Zähle alle Knoten des Binärbaums {wert, links, rechts}. Ein leerer Baum ist null und ergibt 0. Jeder vorhandene Knoten zählt 1, unabhängig von seinem Wert. Addiere die Anzahlen des linken und rechten Teilbaums. Verändere keinen Knoten.",
    tests: cases([3, 0, 1, 3, 3, 5, 3]),
    hints: ["Prüfe zuerst baum === null und gib dann 0 zurück.", "Ein vorhandener Knoten ergibt 1 + baumKnoten(baum.links) + baumKnoten(baum.rechts)."],
    solution: "function baumKnoten(baum) {\n  if (baum === null) return 0;\n  return 1 + baumKnoten(baum.links) + baumKnoten(baum.rechts);\n}",
    explanation: "Der leere Teilbaum liefert 0. Jeder vorhandene Knoten ergänzt 1 und lässt beide Teilbäume nach derselben Regel zählen. Dadurch werden auch einseitige Bäume und Knoten mit falsy-Werten vollständig erfasst.",
  }),
  lesson({
    id: "js-tree-height", name: "Höhe bestimmen", title: "Die Höhe eines Baums mit Math.max berechnen",
    description: "Die Höhe beschreibt hier die Anzahl der Knoten auf dem längsten Weg von der Wurzel bis zu einem Blatt. Entscheidend ist der höhere Teilbaum, nicht die Summe beider Seiten.",
    syntax: "if (baum === null) return 0;\nreturn 1 + Math.max(baumHoehe(baum.links), baumHoehe(baum.rechts));",
    parts: [["Leerer Baum: 0", "Ohne Knoten gibt es keinen Weg mit einem Knoten."], ["Blatt: 1", "Ein einzelner Knoten ist eine Ebene hoch."], ["Math.max(a, b)", "Liefert die größere der beiden berechneten Höhen."], ["1 + …", "Ergänzt die Ebene des aktuellen Knotens."]],
    note: "Manche Bücher messen Höhe in Kanten statt Knoten. Diese Aufgabe zählt ausdrücklich Knoten: null hat Höhe 0, ein Blatt Höhe 1. Die Knotenzahl eines Baums ist etwas anderes als seine Höhe.",
    detail: "Ein Baum mit Wurzel und zwei Blättern enthält 3 Knoten, ist aber nur 2 Ebenen hoch. Eine Kette aus 3 Knoten ist 3 Ebenen hoch. Rekursion berechnet beide Teilhöhen; Math.max wählt den längeren Weg. Kurze, gültige Bäume ohne Zyklen werden verwendet.",
    functionName: "baumHoehe", parameter: "baum",
    task: "Schreibe baumHoehe(baum). Gib die Höhe als Anzahl der Knoten auf dem längsten Wurzel-Blatt-Weg zurück. null ergibt 0, ein Blatt 1. Verwende zum Üben 1 + Math.max(linkeHoehe, rechteHoehe). Verändere den Baum nicht.",
    tests: cases([2, 0, 1, 3, 2, 3, 2]),
    hints: ["Der Basisfall ist baum === null mit Rückgabe 0.", "Berechne die Höhe beider Teilbäume rekursiv, wähle Math.max und ergänze 1."],
    solution: "function baumHoehe(baum) {\n  if (baum === null) return 0;\n  return 1 + Math.max(baumHoehe(baum.links), baumHoehe(baum.rechts));\n}",
    explanation: "Jeder Aufruf ermittelt die längste Strecke innerhalb seines Teilbaums. Die größere Teilhöhe plus die aktuelle Ebene ergibt die Gesamthöhe. Addieren beider Teilhöhen würde Seitenzweige mitzählen, die nicht auf einem einzigen Weg liegen.",
  }),
  lesson({
    id: "js-tree-preorder", name: "Preorder", title: "Einen Baum in Preorder durchlaufen",
    description: "Preorder liest zuerst die Wurzel, danach den linken und schließlich den rechten Teilbaum. Dieselbe Regel gilt an jedem Knoten.",
    syntax: "if (baum === null) return [];\nreturn [baum.wert, ...preorder(baum.links), ...preorder(baum.rechts)];",
    parts: [["Preorder", "Reihenfolge: Wurzel → links → rechts."], ["baum.wert", "Der Wert des aktuellen Knotens steht zuerst in seiner Teilbaum-Ausgabe."], ["...preorder(baum.links)", "Übernimmt alle Werte des linken Teilbaums."], ["...preorder(baum.rechts)", "Übernimmt danach alle Werte des rechten Teilbaums."], ["[]", "Der leere Teilbaum trägt keine Werte zur Ausgabe bei."]],
    note: "Spread ... übernimmt Arrayelemente, statt ein Unterarray einzufügen. [baum.wert, preorder(baum.links)] wäre daher ein verschachteltes Ergebnis. Auch null als Knotenwert gehört in die Ausgabe.",
    detail: "Bei einer Wurzel A mit linkem Blatt B und rechtem Blatt C ergibt sich [A, B, C]. Preorder ist eine Variante der Tiefensuche und verarbeitet Eltern vor ihren Kindern. Die Ausgabe bewahrt die Baumstruktur als Besuchsreihenfolge, nicht als vollständige Serialisierung: Ohne weitere Strukturinformationen lässt sich daraus nicht jeder Baum eindeutig rekonstruieren.",
    functionName: "preorder", parameter: "baum",
    task: "Schreibe preorder(baum). Gib ein flaches Array aller Knotenwerte in der Reihenfolge Wurzel, linker Teilbaum, rechter Teilbaum zurück. Wiederhole diese Regel rekursiv. Bei null gib [] zurück. Erhalte Werttypen, Duplikate und den unveränderten Baum.",
    tests: cases([["A", "B", "C"], [], [0], [1, 2, 3], [0, false, null], [5, 8, 3, 1, 2], ["A", "A", "B"]]),
    hints: ["Der Basisfall null liefert ein leeres Array.", "Stelle baum.wert vor ...preorder(baum.links) und ...preorder(baum.rechts)."],
    solution: "function preorder(baum) {\n  if (baum === null) return [];\n  return [baum.wert, ...preorder(baum.links), ...preorder(baum.rechts)];\n}",
    explanation: "Jeder Teilbaum liefert ein eigenes Array in Preorder. Das Ergebnis beginnt mit dem aktuellen Wert und übernimmt anschließend die beiden Teilbaum-Ausgaben. Fehlende Kinder tragen leere Arrays bei.",
  }),
  lesson({
    id: "js-tree-inorder", name: "Inorder", title: "Einen Baum in Inorder durchlaufen",
    description: "Inorder besucht zuerst den linken Teilbaum, dann die Wurzel und zuletzt den rechten Teilbaum. Schon diese kleine Änderung erzeugt eine andere Reihenfolge als Preorder.",
    syntax: "if (baum === null) return [];\nreturn [...inorder(baum.links), baum.wert, ...inorder(baum.rechts)];",
    parts: [["Inorder", "Reihenfolge: links → Wurzel → rechts."], ["linker Teilbaum", "Wird vollständig gelesen, bevor der aktuelle Knotenwert ausgegeben wird."], ["baum.wert", "Steht zwischen den Ausgaben beider Teilbäume."], ["rechter Teilbaum", "Wird nach dem aktuellen Knotenwert gelesen."]],
    note: "Inorder liefert nur bei einem passend geordneten binären Suchbaum eine sortierte Folge. Diese Aufgabe verwendet allgemeine Binärbäume; sortiere die Ausgabe deshalb nicht.",
    detail: "Die Wurzel A mit linkem Blatt B und rechtem Blatt C ergibt [B, A, C]. An jedem Kind wird dieselbe Inorder-Regel wiederholt. Preorder, Inorder und später Postorder unterscheiden sich darin, wann der aktuelle Knoten im Verhältnis zu seinen Teilbäumen verarbeitet wird.",
    functionName: "inorder", parameter: "baum",
    task: "Schreibe inorder(baum). Gib ein flaches Array aller Werte in der Reihenfolge linker Teilbaum, Wurzel, rechter Teilbaum zurück. Ein leerer Baum ergibt []. Sortiere die Werte nicht und verändere keinen Knoten. Bewahre alle Werttypen.",
    tests: cases([["B", "A", "C"], [], [0], [1, 2, 3], [false, 0, null], [3, 8, 5, 1, 2], ["A", "A", "B"]]),
    hints: ["Behandle zuerst den leeren Baum mit return [].", "Setze die Ausgabe zusammen als [...inorder(baum.links), baum.wert, ...inorder(baum.rechts)]."],
    solution: "function inorder(baum) {\n  if (baum === null) return [];\n  return [...inorder(baum.links), baum.wert, ...inorder(baum.rechts)];\n}",
    explanation: "Der linke Teilbaum liefert seine Werte vor dem aktuellen Knoten. Der rechte Teilbaum folgt danach. Die Reihenfolge ergibt sich aus den Verweisen im Baum, nicht aus einer numerischen oder lexikografischen Sortierung.",
  }),
  lesson({
    id: "js-tree-postorder", name: "Postorder", title: "Teilbäume vor der Wurzel in Postorder besuchen",
    description: "Postorder verarbeitet zuerst den linken Teilbaum, dann den rechten und zuletzt die Wurzel. Die Kinder werden damit vor ihrem Elternknoten besucht.",
    syntax: "if (baum === null) return [];\nreturn [...postorder(baum.links), ...postorder(baum.rechts), baum.wert];",
    parts: [["Postorder", "Besuchsreihenfolge: links → rechts → Wurzel."], ["rekursive Teilbaum-Aufrufe", "Wenden dieselbe Reihenfolge auf jedes Kind an."], ["baum.wert am Ende", "Verarbeitet die Wurzel erst nach ihren Teilbäumen."], ["...", "Übernimmt die Werte der Teilbaum-Arrays in ein flaches Ergebnis."]],
    note: "Postorder ist nicht einfach eine umgekehrte Preorder-Ausgabe: Preorder umkehren würde rechts → links → Wurzel ergeben.",
    detail: "Bei A mit den Blättern B links und C rechts ergibt Postorder [B, C, A]. Die Reihenfolge hilft, wenn ein Eltern-Ergebnis erst nach seinen Kind-Ergebnissen berechnet werden kann, etwa bei einer Ausdrucksauswertung. Die Aufgabe liest kleine allgemeine Binärbäume, ohne sie zu verändern.",
    functionName: "postorder", parameter: "baum",
    task: "Schreibe postorder(baum). Gib alle Knotenwerte als flaches Array in der Reihenfolge linker Teilbaum, rechter Teilbaum, Wurzel zurück. null ergibt []. Bewahre Werttypen und Duplikate und verändere den Baum nicht.",
    tests: cases([["B", "C", "A"], [], [0], [3, 2, 1], [false, null, 0], [3, 8, 2, 1, 5], ["A", "B", "A"]]),
    hints: ["Der leere Baum liefert ein leeres Array.", "Setze erst ...postorder(baum.links), danach ...postorder(baum.rechts) und zuletzt baum.wert in die Ausgabe."],
    solution: "function postorder(baum) {\n  if (baum === null) return [];\n  return [...postorder(baum.links), ...postorder(baum.rechts), baum.wert];\n}",
    explanation: "Beide Teilbäume werden nach derselben Regel vollständig verarbeitet, bevor ihr Elternwert angehängt wird. Die Reihenfolge der beiden Kinder bleibt links vor rechts.",
  }),
  lesson({
    id: "js-tree-bfs", name: "Breitensuche", title: "Einen Baum mit einer Queue Ebene für Ebene lesen",
    description: "Breitensuche besucht zuerst die Wurzel, dann alle Knoten der nächsten Ebene und so weiter. Eine Queue hält die noch zu besuchenden Knoten in ihrer Ankunftsreihenfolge.",
    syntax: "const queue = [baum];\nlet kopf = 0;\nwhile (kopf < queue.length) {\n  const knoten = queue[kopf];\n  kopf += 1;\n  if (knoten.links !== null) queue.push(knoten.links);\n  if (knoten.rechts !== null) queue.push(knoten.rechts);\n}",
    parts: [["Queue", "Speichert offene Knoten nach FIFO statt LIFO."], ["queue[kopf]", "Liest den ältesten noch nicht besuchten Knoten."], ["kopf += 1", "Markiert diesen Queueeintrag als verarbeitet."], ["links vor rechts einreihen", "Legt die Reihenfolge innerhalb einer Ebene fest."], ["Kind !== null", "Prüft, ob ein Kindknoten vorhanden ist, unabhängig von dessen Wert."]],
    note: "Mit pop statt FIFO würdest du einen Stack verwenden und keine Breitensuche durchführen. Der Kopfindex vermeidet wiederholtes Verschieben durch shift.",
    detail: "Bei Wurzel A, linkem Kind B mit Kind D und rechtem Kind C ist die Ausgabe [A, B, C, D]. Tiefensuche könnte D vor C besuchen. Diese erste Queue behält verbrauchte Einträge im Array; für langlebige Queues kämen Kompaktierung oder Ringpuffer infrage. Die Eingabe ist ein kleiner echter Baum ohne Zyklen; Graphen benötigen zusätzlich eine Besuchsmarkierung.",
    functionName: "breitensuche", parameter: "baum",
    task: "Schreibe breitensuche(baum). Gib die Knotenwerte Ebene für Ebene von oben nach unten aus. Innerhalb jeder Ebene besuche die Kinder von links nach rechts. null ergibt []. Nutze zum Üben eine Queue mit Kopfindex. Verändere keinen Knoten und behalte alle Werttypen und Duplikate.",
    tests: cases([["A", "B", "C"], [], [0], [1, 2, 3], [0, false, null], [5, 8, 1, 3, 2], ["A", "A", "B"]]),
    hints: ["Behandle null zuerst. Starte sonst queue = [baum], kopf = 0 und werte = [].", "Lies den aktuellen Queueknoten, sammle seinen Wert und füge vorhandene Kinder links, dann rechts hinzu. Wiederhole, solange kopf < queue.length."],
    solution: "function breitensuche(baum) {\n  if (baum === null) return [];\n  const queue = [baum];\n  const werte = [];\n  let kopf = 0;\n  while (kopf < queue.length) {\n    const knoten = queue[kopf];\n    kopf += 1;\n    werte.push(knoten.wert);\n    if (knoten.links !== null) queue.push(knoten.links);\n    if (knoten.rechts !== null) queue.push(knoten.rechts);\n  }\n  return werte;\n}",
    explanation: "Die Queue verarbeitet ältere Einträge vor den neu hinzugefügten Kindern. Deshalb werden alle Knoten einer Ebene abgeschlossen, bevor die nächste Ebene folgt. Das Einreihen von links vor rechts erhält die gewünschte Reihenfolge.",
  }),
  lesson({
    id: "js-bst-search", category: "Binäre Suchbäume", name: "Wert suchen", title: "Einen Wert entlang eines binären Suchbaums suchen",
    description: "In einem binären Suchbaum sind alle Werte links kleiner und alle Werte rechts größer als der aktuelle Wert. Diese Ordnung gilt für den ganzen jeweiligen Teilbaum und erlaubt eine gezielte Suche.",
    syntax: "if (daten.wert === knoten.wert) return true;\nknoten = daten.wert < knoten.wert ? knoten.links : knoten.rechts;",
    parts: [["===", "Erkennt einen vorhandenen Wert."], ["<", "Entscheidet, ob nur der linke Teilbaum infrage kommt."], ["? links : rechts", "Der ternäre Operator wählt den nächsten Suchzweig."], ["null", "Das Ende eines erfolglosen Suchpfads."], ["Suchbaum-Invariante", "Alle linken Werte sind kleiner, alle rechten größer – auch tiefer liegende Knoten."]],
    note: "Diese Suche setzt einen gültigen Suchbaum mit unterschiedlichen endlichen Zahlen voraus. Bei einem beliebigen Binärbaum ist das Verwerfen eines Zweigs nicht korrekt. Die Aufgabe validiert die Ordnung nicht selbst.",
    detail: "Vergleiche am aktuellen Knoten, suche bei kleinerem Ziel links und bei größerem Ziel rechts weiter. In einem ausgeglichenen Baum ist der Pfad kurz. Ein unbalancierter Suchbaum kann jedoch zu einer Kette werden; dann ist die Suche im schlechtesten Fall linear. Einfache Suchbäume sind nicht automatisch balanciert.",
    functionName: "suchbaumEnthaelt", parameter: "daten",
    task: "Schreibe suchbaumEnthaelt(daten) für {baum, wert}. Gib true zurück, wenn die endliche Zahl wert im gültigen binären Suchbaum vorkommt, sonst false. Ein leerer Baum ist null. Folge jeweils nur dem passenden Teilbaum und verändere keinen Knoten. Alle Baumwerte sind unterschiedliche endliche Zahlen.",
    tests: [
      { input: { baum: node(5, node(2, node(0), node(3)), node(8, node(7), node(9))), wert: 7 }, expected: true },
      { input: { baum: node(5, node(2), node(8)), wert: 5 }, expected: true },
      { input: { baum: node(5, node(2), node(8)), wert: 6 }, expected: false },
      { input: { baum: null, wert: 0 }, expected: false },
      { input: { baum: node(0, node(-4), node(5)), wert: -4 }, expected: true },
      { input: { baum: node(5, node(0)), wert: 0 }, expected: true },
      { input: { baum: node(0, node(-4), node(5)), wert: -6 }, expected: false },
      { input: { baum: node(1, null, node(2, null, node(3))), wert: 3 }, expected: true },
    ],
    hints: ["Starte mit knoten = daten.baum. Bei Übereinstimmung gib sofort true zurück.", "Wähle mit daten.wert < knoten.wert den linken, sonst den rechten Teilbaum. Erreichst du null, gib false zurück."],
    solution: "function suchbaumEnthaelt(daten) {\n  let knoten = daten.baum;\n  while (knoten !== null) {\n    if (daten.wert === knoten.wert) return true;\n    knoten = daten.wert < knoten.wert ? knoten.links : knoten.rechts;\n  }\n  return false;\n}",
    explanation: "Die Suchbaumordnung schließt an jedem Knoten eine Seite aus. Nur ein Suchpfad wird verfolgt. Eine lokale Referenz wandert durch den Baum, ohne Kindverweise umzuschreiben. Der Wert 0 bleibt ein gültiger Treffer.",
  }),
  lesson({
    id: "js-bst-insert", category: "Binäre Suchbäume", name: "Wert einfügen", title: "Einen Suchbaum ohne Eingabemutation erweitern",
    description: "Ein neuer Wert folgt den Vergleichen bis zu einer freien Kindposition. Dort entsteht ein Knoten. Neue Objekte entlang dieses Pfads halten den ursprünglichen Baum unverändert.",
    syntax: "if (baum === null) return { wert, links: null, rechts: null };\nif (wert === baum.wert) return baum;\nif (wert < baum.wert) return { ...baum, links: einfuegen(baum.links) };\nreturn { ...baum, rechts: einfuegen(baum.rechts) };",
    parts: [["null als Einfügestelle", "Erzeugt einen neuen Blattknoten."], ["wert === baum.wert", "Vorhandene Werte werden hier nicht doppelt eingefügt."], ["{ ...baum, links: … }", "Objekt-Spread kopiert den Knoten flach und ersetzt die linke Kindreferenz."], ["{ ...baum, rechts: … }", "Entsprechende Kopie beim Einfügen in den rechten Teilbaum."], ["einfuegen", "Eine selbst geschriebene lokale Hilfsfunktion, keine eingebaute Methode."]],
    note: "Objekt-Spread erstellt keine tiefe Kopie: Unveränderte Teilbäume können von altem und neuem Baum gemeinsam verwendet werden. Solange du sie nicht mutierst, bleibt der alte Baum nutzbar. Referenzidentität wird in dieser Aufgabe nicht geprüft.",
    detail: "Die lokale Hilfsfunktion kann daten.wert aus ihrer umgebenden Funktion lesen. Jeder rekursive Aufruf liefert den neuen Teilbaum zurück; die Elternkopie übernimmt ihn. Vorhandene Werte lassen den Baum unverändert. Die Struktur wird nicht automatisch balanciert. Die Tests erlauben auch tiefe Kopien mit derselben Struktur, wenn die Eingabe erhalten bleibt.",
    functionName: "suchbaumEinfuegen", parameter: "daten",
    task: "Schreibe suchbaumEinfuegen(daten) für {baum, wert}. Füge die endliche Zahl wert in den gültigen Suchbaum mit unterschiedlichen Zahlen ein und gib den neuen Baum zurück. Kleinere Werte stehen links, größere rechts. Vorhandene Werte erzeugen keinen zusätzlichen Knoten. Verändere keinen Eingabeknoten. Der leere Baum wird zu einem einzelnen Blatt.",
    tests: [
      { input: { baum: node(5, node(2), node(8)), wert: 3 }, expected: node(5, node(2, null, node(3)), node(8)) },
      { input: { baum: null, wert: 0 }, expected: node(0) },
      { input: { baum: node(5, node(2), node(8)), wert: 7 }, expected: node(5, node(2), node(8, node(7))) },
      { input: { baum: node(5, node(2), node(8)), wert: 5 }, expected: node(5, node(2), node(8)) },
      { input: { baum: node(5, node(2), node(8)), wert: 2 }, expected: node(5, node(2), node(8)) },
      { input: { baum: node(0, null, node(5)), wert: -4 }, expected: node(0, node(-4), node(5)) },
      { input: { baum: node(-2, null, node(4)), wert: 0 }, expected: node(-2, null, node(4, node(0))) },
    ],
    hints: ["Schreibe eine lokale Funktion einfuegen(baum). Bei null gibt sie einen neuen Knoten mit daten.wert zurück; bei gleichem Wert den vorhandenen Teilbaum.", "Bei kleinerem Wert erzeuge { ...baum, links: einfuegen(baum.links) }, sonst { ...baum, rechts: einfuegen(baum.rechts) }. Die äußere Funktion gibt einfuegen(daten.baum) zurück."],
    solution: "function suchbaumEinfuegen(daten) {\n  function einfuegen(baum) {\n    if (baum === null) return { wert: daten.wert, links: null, rechts: null };\n    if (daten.wert === baum.wert) return baum;\n    if (daten.wert < baum.wert) {\n      return { ...baum, links: einfuegen(baum.links) };\n    }\n    return { ...baum, rechts: einfuegen(baum.rechts) };\n  }\n  return einfuegen(daten.baum);\n}",
    explanation: "Die Vergleiche finden eine freie Position oder einen vorhandenen gleichen Wert. Rückgabewerte bauen neue Knoten entlang des Einfügepfads auf. Unveränderte Seiten werden übernommen, ohne die alten Knoten zu überschreiben.",
  }),
];
