function lesson(data) {
  return {
    course: "js", category: "Datentypen", preserveInput: true, ...data,
    starter: `function ${data.functionName}(${data.parameter || "wert"}) {\n  // Schreibe hier deine Lösung.\n}\n\nconsole.log(${data.functionName}(${JSON.stringify(data.tests[0].input)}));`,
    example: `${data.solution}\n\nconsole.log(${data.functionName}(${JSON.stringify(data.tests[0].input)}));`,
  };
}

export const typeLessons = [
  lesson({
    id: "js-typeof", name: "typeof", title: "Datentypen erkennen mit typeof",
    description: "Ein Wert hat einen Typ. typeof liefert dessen Namen als String, etwa 'number', 'string' oder 'boolean'.",
    syntax: "typeof 42;        // 'number'\ntypeof '42';      // 'string'\ntypeof true;      // 'boolean'\ntypeof undefined; // 'undefined'",
    parts: [["number", "Zahlen wie 42, -3 und 1.5. Auch NaN hat diesen Typ."], ["string", "Text zwischen Anführungszeichen, zum Beispiel '42'."], ["boolean", "Genau zwei Werte: true und false."], ["typeof", "Ein Operator, der den Typnamen zurückgibt; er verändert den Wert nicht."]],
    note: "typeof null ergibt historisch 'object'. Arrays ergeben ebenfalls 'object'; Array.isArray erkennt sie gezielt.",
    detail: "42 und '42' sehen ähnlich aus, sind aber unterschiedliche Typen. Bei 42 + 1 wird gerechnet, bei '42' + 1 wird Text verbunden. typeof ist keine Methode des Werts, sondern ein Operator.",
    functionName: "typErkennen",
    task: "Schreibe typErkennen(wert). Gib das Ergebnis von typeof wert zurück. Die Tests enthalten Zahlen, Text, Booleans, null, ein Array und ein Objekt.",
    tests: [{input:42,expected:"number"},{input:"42",expected:"string"},{input:true,expected:"boolean"},{input:false,expected:"boolean"},{input:null,expected:"object"},{input:[],expected:"object"},{input:{},expected:"object"}],
    hints: ["Keine feste Antwort zurückgeben: Der Eingabewert wechselt.", "return typeof wert;"],
    solution: "function typErkennen(wert) {\n  return typeof wert;\n}",
    explanation: "typeof liefert für jeden übergebenen Wert einen Typnamen als String. null und Arrays ergeben 'object', obwohl null kein gewöhnliches Objekt ist und Arrays speziell erkannt werden können.",
  }),
  lesson({
    id: "js-missing", name: "null & undefined", title: "Fehlende Werte: null und undefined",
    description: "undefined entsteht beispielsweise bei einer fehlenden Eigenschaft. null wird oft bewusst als 'kein Wert' gesetzt. Beide sind eigene primitive Werte.",
    syntax: "const daten = {};\ndaten.wert;            // undefined\nconst auswahl = null;  // bewusst leer",
    parts: [["undefined", "Zum Beispiel: Eigenschaft fehlt, let wurde noch kein Wert zugewiesen oder Funktion endet ohne return."], ["null", "Ein ausdrücklich gesetzter leerer Wert."], ["===", "Vergleicht ohne Typumwandlung: null === undefined ist false."], ["||", "Logisches Oder: Hier reicht einer von zwei zutreffenden Vergleichen."]],
    note: "0, false und '' sind vorhandene Werte. Eine Prüfung auf fehlende Werte darf sie nicht automatisch als fehlend behandeln.",
    detail: "typeof nichtDeklariert ergibt 'undefined', ohne einen unbekannten Namen direkt lesen zu müssen. Eine Ausnahme sind let/const-Namen vor ihrer Initialisierung im selben Gültigkeitsbereich: Dort kann auch typeof einen Fehler werfen.",
    functionName: "wertFehlt", parameter: "daten",
    task: "Schreibe wertFehlt(daten). Prüfe daten.wert. Gib true zurück, wenn die Eigenschaft fehlt oder null ist; sonst false. Behandle 0, false und leeren Text als vorhanden.",
    tests: [{input:{},expected:true},{input:{wert:null},expected:true},{input:{wert:0},expected:false},{input:{wert:false},expected:false},{input:{wert:""},expected:false},{input:{wert:"Hallo"},expected:false}],
    hints: ["Prüfe daten.wert === undefined und daten.wert === null getrennt.", "Verbinde die beiden Vergleiche mit ||. !daten.wert wäre für 0, false und '' zu ungenau."],
    solution: "function wertFehlt(daten) {\n  return daten.wert === undefined || daten.wert === null;\n}",
    explanation: "Eine fehlende Eigenschaft liefert undefined. === prüft beide fehlenden Werte genau, ohne Umwandlung. || verbindet die Vergleiche. Vorhandene Werte wie 0 oder false erfüllen keinen davon.",
  }),
  lesson({
    id: "js-number", name: "Number() & NaN", title: "Text in Zahlen umwandeln mit Number",
    description: "Number(wert) versucht, einen Wert in eine Zahl umzuwandeln. Ein nicht interpretierbarer Text ergibt NaN: 'Not a Number'.",
    syntax: "const zahl = Number('12.5'); // 12.5\nNumber.isNaN(Number('abc')); // true",
    parts: [["Number(wert)", "Explizite Typumwandlung in eine Zahl."], ["NaN", "Ein spezieller Zahlenwert für ein ungültiges Zahlenergebnis."], ["Number.isNaN(zahl)", "Prüft NaN ohne weitere Typumwandlung."], ["+", "Addiert bei zwei Zahlen. Sind Strings beteiligt, kann Textverkettung entstehen."]],
    note: "Number('') und Number('   ') ergeben 0. Number('1,5') ergibt NaN; der Dezimaltrenner ist hier ein Punkt. NaN === NaN ist false.",
    detail: "Eingaben aus HTML-Textfeldern sind typischerweise Strings. '10' + 5 ergibt '105', Number('10') + 5 ergibt 15. Number wandelt den vollständigen Text um; Number('12px') ergibt NaN. Number(null) ist 0, Number(undefined) ist NaN.",
    functionName: "zahlPlusFuenf",
    task: "Schreibe zahlPlusFuenf(wert). Wandle den übergebenen String mit Number in eine Zahl um. Gib die Zahl plus 5 zurück. Ergibt die Umwandlung NaN, gib den String 'Ungültige Zahl' zurück. Leerer Text soll entsprechend Number als 0 gelten.",
    tests: [{input:"10",expected:15},{input:"-2.5",expected:2.5},{input:"",expected:5},{input:" 7 ",expected:12},{input:"abc",expected:"Ungültige Zahl"},{input:"12px",expected:"Ungültige Zahl"},{input:"1,5",expected:"Ungültige Zahl"}],
    hints: ["Speichere const zahl = Number(wert).", "Prüfe zuerst Number.isNaN(zahl). Gib nur bei einer gültigen Umwandlung zahl + 5 zurück."],
    solution: "function zahlPlusFuenf(wert) {\n  const zahl = Number(wert);\n  if (Number.isNaN(zahl)) {\n    return 'Ungültige Zahl';\n  }\n  return zahl + 5;\n}",
    explanation: "Die Umwandlung findet vor der Addition statt. Number.isNaN erkennt ungültige Ergebnisse. Die if-Verzweigung liefert dann einen verständlichen Text; andernfalls werden zwei Zahlen addiert.",
  }),
  lesson({
    id: "js-string", name: "String()", title: "Werte in Text umwandeln mit String",
    description: "String(wert) erzeugt eine Textdarstellung des Werts. Danach kannst du Text gezielt zusammensetzen.",
    syntax: "String(42);    // '42'\nString(false); // 'false'\n'Wert: ' + String(42);",
    parts: [["String(wert)", "Gibt einen primitiven String zurück; verändert die Eingabe nicht."], ["'Wert: '", "Ein fester Text mit Leerzeichen nach dem Doppelpunkt."], ["+", "Verbindet hier zwei Strings zu einem neuen Text."]],
    note: "String(null) ist 'null', String(undefined) ist 'undefined'. String ist keine JSON-Serialisierung: Ein gewöhnliches Objekt wird oft '[object Object]'.",
    detail: "42 bleibt eine Zahl, wenn du String(42) nur aufrufst und den Rückgabewert nicht nutzt. String([1, 2]) ergibt '1,2'. Für eine strukturierte Datendarstellung eignet sich JSON.stringify statt String.",
    functionName: "wertAlsText",
    task: "Schreibe wertAlsText(wert). Gib 'Wert: ' gefolgt von String(wert) zurück. Achte auf das Leerzeichen, und erhalte auch 0 und false im Text.",
    tests: [{input:42,expected:"Wert: 42"},{input:0,expected:"Wert: 0"},{input:false,expected:"Wert: false"},{input:null,expected:"Wert: null"},{input:"",expected:"Wert: "},{input:[1,2],expected:"Wert: 1,2"}],
    hints: ["Wandle den Wert mit String(wert) in Text um.", "Verbinde 'Wert: ' und den umgewandelten Text mit +."],
    solution: "function wertAlsText(wert) {\n  return 'Wert: ' + String(wert);\n}",
    explanation: "String liefert die Textdarstellung. + fügt den festen Anfang hinzu. Ein leerer Eingabestring erzeugt nur den Anfang; null wird ausdrücklich als Text 'null' dargestellt.",
  }),
  lesson({
    id: "js-boolean", name: "Boolean()", title: "Wahrheitswerte und Boolean verstehen",
    description: "Boolean(wert) wandelt einen Wert nach festen Regeln in true oder false um. Diese Regeln nutzt auch if.",
    syntax: "Boolean(0);       // false\nBoolean('false'); // true\nBoolean([]);      // true",
    parts: [["Boolean(wert)", "Liefert einen Boolean entsprechend der truthy/falsy-Regeln."], ["falsy", "Unter anderem false, 0, -0, 0n, '', null, undefined und NaN."], ["truthy", "Die übrigen üblichen Werte, einschließlich leerer Arrays und Objekte."]],
    note: "Der Text 'false' ist nicht der Boolean false. Jeder nicht leere gewöhnliche String ist truthy, auch '0'.",
    detail: "Boolean prüft nicht, ob eine Liste Elemente enthält, und interpretiert keinen Textinhalt wie 'false'. Für nicht leere Listen prüfe liste.length > 0. Für fehlende Werte nutze eine gezielte null/undefined-Prüfung.",
    functionName: "alsBoolean",
    task: "Schreibe alsBoolean(wert). Gib Boolean(wert) zurück. Achte insbesondere auf leere Arrays, Objekte und die Strings 'false' und '0'.",
    tests: [{input:0,expected:false},{input:"",expected:false},{input:null,expected:false},{input:false,expected:false},{input:"false",expected:true},{input:"0",expected:true},{input:[],expected:true},{input:{},expected:true},{input:-1,expected:true}],
    hints: ["Gib den Rückgabewert von Boolean(wert) zurück.", "Ein leerer String ist falsy; ein leeres Array ist truthy."],
    solution: "function alsBoolean(wert) {\n  return Boolean(wert);\n}",
    explanation: "Boolean folgt den festgelegten Umwandlungsregeln. Es interpretiert Text nicht als Wahrheitsangabe. Deshalb ist 'false' true, während false false bleibt. Auch leere Arrays und Objekte sind truthy.",
  }),
];
